### ISSUE TITLE
test target dependencies are incomplete

### ISSUE THREAD

**Issue by qcolombet** [pytorch/glow#1086]
One thing I noticed, the dependencies are not correct in the cmake. In effect, if you run `ninja test` without building glow first, it will fail because the tests don't depend on glow being built. This is problematic as we may update glow, forget to rebuild, and run the tests and think that everything is okay whereas we would run the old code.

**Comment by qcolombet** [comment]
Had a quick look at this today.
This is actually a bug/feature in cmake with the add_test command (https://gitlab.kitware.com/cmake/cmake/issues/8774).

There are two possible workarounds:
1. Run all then test (basically do it manually)
2. Add a custom target that depends on all the test executables and that invokes ctest

The problem with #2 is:
A. We have to manually maintain the list of executables. (Though with can hide that in some cmake function.)
B. We cannot use `test` for the target (e.g., we have to use check.)

Note: LLVM does exactly #2.

Let me know what you guys think and I'll either do a quick attempt at #2 or I'll close the issue.

**Comment by nadavrot** [comment]
I am okay with calling ninja check instead of ninja test.

**Comment by nadavrot** [comment]
CC @compnerd

**Comment by jfix71** [comment]
RE: 1. I always use `alias ntest="ninja all && ninja test"` in place of `ninja test`.

**Comment by qcolombet** [comment]
In case people are interested into a check target that does exactly what @jfix71 said, I've given a stab at it and posted a PR:
https://github.com/pytorch/glow/pull/1104

**Comment by qcolombet** [comment]
Fixed with commit 1116b5a.

Now, ninja check will do the re-build + test.
