### ISSUE TITLE
Support non-square padding for Convolution operator

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1107]
[Convolution](https://adeshpande3.github.io/A-Beginner%27s-Guide-To-Understanding-Convolutional-Neural-Networks-Part-2/) is the most important operator for Computer Vision NNs.

The simplest implementation (our Interpreter backend) could be found here:
https://github.com/pytorch/glow/blob/405e632ef138f1d49db9c3181182f7efd837bccc/lib/Backends/Interpreter/InterpreterNodes.cpp#L40
It has parameters, such as group, pad, stride, filterSize.

Convolution is 2D operation (it always works with 2D image and 2D filter, and produces 2D result). Right now all our Convolution implementations assume that pad is the same for both dimensions (image height and width). But for some models (very rarely) it's not true. In general case, there could be 4 different pads: left side, right side, top side, bottom side. We need to change "pad" to be a vector instead of a single number (for ConvolutionNode and ConvolutionInstr). And change all the implementations: Interpreter (float and quantized), CPU (float and quantized). Later, we also need to support uneven paddings in ConvolutionGradNode (which is backward pass for Convolution).

Note, that our Convolution for CPU backend is [highly optimized](https://github.com/pytorch/glow/blob/master/docs/JIT.md#use-case-optimizing-resnet50-for-the-cpu), and in theory complicating its code may lead to losing performance. In practice, I highly doubt that this could happen, but worth to check performance after the change just to be sure. One can run `tests/images/run.sh -cpu -iterations=100` with and without the change, and make sure that average performance numbers are within 1%.

Here is ONNX specification of Conv operator:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#conv
One can notice that not only padding is represented as array there, but also stride and filterSize are represented as array. Changing these is lower priority, and there's no immediate need. Just good thing to have.

Another direction of future work: support non-square padding in PoolMax and PoolAvg operators.

**Comment by rdzhabarov** [comment]
@beicy is this fixed? Can you update this issue?

**Comment by beicy** [comment]
@rdzhabarov Yes, this issue can be closed. So for, for convolution, we support non-square padding, non-square kernels and non-square strides.
