### ISSUE TITLE
Consider enabling OpenCL in CI by using pocl.

### ISSUE THREAD

**Issue by lygstate** [pytorch/glow#1181]
And currently the CPU jit version is far slower than the Interpreter version, that's werid.

**Comment by rdzhabarov** [comment]
> And currently the CPU jit version is far slower than the Interpreter version, that's werid.

where do you see this?

**Comment by lygstate** [comment]
@rdzhabarov  from the ci， maybe because the compiling time is long

**Comment by rdzhabarov** [comment]
it's because CPU version uses ASAN build.

**Comment by rdzhabarov** [comment]
Some of the issues that could be caught in CI:
* https://github.com/pytorch/glow/pull/1185

**Comment by opti-mix** [comment]
@lygstate Do you have more information about using POCL with Travis? 

What needs to be done to use POCL on Linux (and MacOS)? 
Are there pre-built binary packages for it? 
To use pocl, does the program just needs to link against the library and that's it?
If pocl is installed, would CMake be able to find and use it automatically when we look for OpenCL?

**Comment by qcolombet** [comment]
+1 on enabling opencl testing in our CI.
It bit us again in #1959

**Comment by opti-mix** [comment]
It seems like if pocl is installed on the system (by means of apt-get or any other package manager), we would need to add something like `GLOW_WITH_POCL` option to cmake and then in the CMake file in the OpenCL backend we'd need to replace this:

```
target_link_libraries(OpenCL
                      PRIVATE
                      OpenCL::OpenCL)
```

by something like:
```
if(NOT pocl_FOUND)
   set (OPENCL_LIBS OpenCL::OpenCL)
else()
   set (OPENCL_LIBS pocl)
endif()   

target_link_libraries(OpenCL
                      PRIVATE
                      ${OPENCL_LIBS})
```

This would prefer pocl to the native OpenCL libraries if GLOW_WITH_POCL was configured.
