### ISSUE TITLE
Add support for BUCK build

### ISSUE THREAD

**Issue by rdzhabarov** [pytorch/glow#1189]
We should be able to build Glow compiler with the Buck.

You can get more details on BUCK [here](https://github.com/facebook/buck).

**Comment by bertmaher** [comment]
I'm doing this for FB's internal build system, but it'd be pretty cool to build externally with buck as well.  I know this is do-able since [watchman](https://github.com/facebook/watchman) does it currently.

**Comment by bertmaher** [comment]
This task is done, at least internally to FB.  Since I suspect OSS users are happy with cmake/ninja, I'm going to go ahead and close this out.  If any external users want Buck support please re-open and I'll be happy to port the internal stuff.
