### ISSUE TITLE
[Broadcasting] Concat inputs scale with the broadcast size.

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#1318]
We represent a broadcast as a series of concats. For example if we want to broadcast a tensor `A` with `dims = {1}` to a tensor `B` with `dims = {10}`, `B` is a ConcatNode with `A` repeatedly input 10 times.

This works nicely because we do not need a BroadcastNode. Additionally, [we IRGen this ConcatNode](https://github.com/pytorch/glow/blob/master/lib/IR/IRGen.cpp#L265) with repeated inputs into a single InsertTensorInst with some `count` value, i.e. the InsertTensorInst does not have its input count scale with the broadcast size.

However, this scaling issue does occur at the Node level. If the broadcast size is large, for example if the destination tensor `B` has ` dims = {2048}`, then `B` will be a ConcatNode with 2048 inputs. Not great.

To improve this, one option I am considering is to add a vector member to ConcatNode that represents how many times to concatenate each input. For example, instead of the above ConcatNode `B` having `A` input 2048 times, it has `A` input once, as well as a new "count" member vector `{2048}`, signaling that `A` should be inserted `2048` times.

If we wanted to also Concat some other Node `C` 10 times at the end, then this "count" member vector would be `{2048, 10}`, and `B` would have `A` and `C` input once each.

This would mean ConcatNode more closely matches our InsertTensorInst, which ConcatNode is IRGen'd into anyway. However, it adds some complexity to the ConcatNode.

What does everyone think?

**Comment by qcolombet** [comment]
Sounds sensible.
One thing I would suggest is to tie the input and number of times more closely if possible: i.e., (A, B) (2048, 10) vs. (A, 2048) (B, 10).

**Comment by rdzhabarov** [comment]
Sounds like a good idea to me. Do we anticipate that we'd need the flexibility to use: A,5 times; B,4 times; A,10 times again etc? Maybe not, but I think what @qcolombet suggests will help us to support this case pretty easy if needed.

**Comment by qcolombet** [comment]
One thing that came to mind.
We could also introduce a new splat node that would repeat the input x time.
E.g.,
instead of doing
concat A, 2040, B 10

We would have, (concat (splat A, 2048), (splat B, 10)).

I am just suggesting that because I think we were thinking of adding such a "splat" node.

**Comment by jfix71** [comment]
@rdzhabarov Good point, I actually don't think we actually need the flexibility as far as I've seen. I think we will generally see either all inputs to the concat with `count = 1`, or a single repeated input (through a Broadcast or Tile).

An alternative that is less complex and doesn't provide this unnecessary flexibility is to add `count` and `axis` to the InsertTensorNode. The InsertTensorInst currently already has `count` and `axis`, so this is a somewhat natural change. Then we could move `createTile()` (which `createBroadcast()` uses) to create an InsertTensorNode with a count instead of ConcatNode with repeated input as it currently does.

@qcolombet I would imagine the input data for a Splat with a repeat count needs to be statically known, similar to how current splats only take a statically known float value? If so, I don't think it is applicable in this case, because the data here that is to be concatenated isn't statically known.

**Comment by jfix71** [comment]
Done by https://github.com/pytorch/glow/pull/1332
