### ISSUE TITLE
Minimize #ifdef FACEBOOK_INTERNAL in GlowJIT

### ISSUE THREAD

**Issue by bertmaher** [pytorch/glow#1359]
PR #1357 introduced some #ifdefs to GlowJIT.{h,cpp} to work around the shifting ORC JIT API in llvm 7.0.  We can probably minimize those by:
* switching to the C API, if that is stable (OrcBindings.h, as mentioned by @qcolombet in #1357)
* thinning out the GlowJIT API (with a bit of work we can actually remove some of its API functions and types, so there's less to guard)
* figuring out the llvm 7.0 API for GDB registration listeners so we can do something sensible with `NotifyLoadedFunctor`

And at some point the LLVM  7.0 API will stabilize and we can shift to major version guards instead of `FACEBOOK_INTERNAL`.

**Comment by vedanuj** [comment]
@bertmaher Can I take a stab at this if no one else is working on it?

**Comment by bertmaher** [comment]
@vedanuj Be my guest!
