### ISSUE TITLE
Need to implement the CPU support for SparseLengthsSum

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#1436]
At the moment the CPU backend does not support the SparseLengthsSum operation. We need to make sure that we have a high-performance implementation for the operation.

**Comment by artemrakhov** [comment]
Small correction: I'm generalizing SparseLengthsSum to become SparseLengths**Weighted**Sum in this PR: https://github.com/pytorch/glow/pull/1439

**Comment by rdzhabarov** [comment]
Also, it needs to be implemented for ONNX loader for ONNXIFI.

**Comment by rdzhabarov** [comment]
@jackm321 one more warmup task

**Comment by jojivk73** [comment]
I am new to this operator. Can anyone point me to an example that uses SparseLengthsSum for sparse data?
Thanks

**Comment by nadavrot** [comment]
CC @artemrakhov @beicy @rdzhabarov

**Comment by rdzhabarov** [comment]
@jojivk73 you can check Caffe2 docs for the operator specifics: https://caffe2.ai/docs/operators-catalogue.html#sparselengthssum

IIRC, we do not have publicly available models which uses this op.

**Comment by artemrakhov** [comment]
You can look at a unit test to learn the semantics:
https://github.com/pytorch/glow/blob/c34d59929c00d287ba441a7a332a480550047a41/tests/unittests/OperatorTest.cpp#L3753

**Comment by jojivk73** [comment]
Thanks! I will check it out!
