### ISSUE TITLE
vgg19: Some FP weights are not used after quantization anymore, but they are not removed

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#1441]
Sometimes, when an NN model is quantized, the FP weights are replaced by Int8 weights. But it looks like the old FP weights are not removed, even though they are not used.

![vgg19_unused_weights](https://user-images.githubusercontent.com/33707249/43972189-6df0e412-9c88-11e8-9f27-325ca07d5f89.png)

Most likely the DCE pass in the GraphOptimizer.cpp decides to keep these weights around for some reason (e.g. they are public, etc).

This issue needs to be fixes, because keeping these weights around increases the amount of memory required to run a quantized model, whereas one of the main goals of quantization is to reduce the memory consumption and the amount of data transfers.

**Comment by opti-mix** [comment]
The issue could be fixed either in DCE or in the backends, but fixing it in DCE would be preferable.

The first step would be to debug when these weights become unused and why they are not removed by the DCE.

**Comment by ZchiPitt** [comment]
done
