### ISSUE TITLE
FP16 support

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#1449]
Glow needs to support the FP16 format. This work includes the following subtasks:

1. New tensor data types (new element type, tensor printer, et.). 
2. Support in the interpreter for the new data type in popular operators (such as conv and matmul).
3. Conversion utility. Similar to the quantization procedure, the conversion utility needs to take floating point-based networks and convert them to float-16. This procedure will enable the testing of existing networks (from ONNX and our unit tests). 
4. CPU-support for the operators.

**Comment by qcolombet** [comment]
Related to #1329.

**Comment by nadavrot** [comment]
Thanks @qcolombet . I'll make this issue as a dup of #1329.
