### ISSUE TITLE
On the usage of 'auto' in Glow

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#1468]
I've noticed that `auto` is used extensively in Glow. If I see the advantage when programming templates for instance, or for forcing variables to be initialized, I personally find that it makes the code much harder to read/understand (lots of information becomes implicit) and it can confuse IDEs. What is the current approach of the Glow project with regard to `auto` ?

**Comment by nadavrot** [comment]
@tlepley-cadence I agree that explicitly writing the type can help make the code more readable. In some cases the use of auto is obvious. For example (auto *x = dyn_cast<Variable>(y)), where the type is listed in the second part of the expression. In other cases the use of auto obfuscates the code by omitting the type. 

Could you bring this issue up in code reviews? Let's start having this discussion during code reviews. This will give us a concrete example to talk about and shape the project's conventions. I don't think that this is something that we discussed before and having this discussion can help us make a deliberate decision.

**Comment by tlepley-cadence** [comment]
I think there are pros and cons with `auto` and I agree that the code review is the best place to discuss this and potentially refine where we want or don't want to use `auto`. If `auto` can obfuscate the code and make the code less readable and potentially harder to maintain, it has also advantages. I've for instance seen that `auto` can simplify some refactoring, for example when renaming types.
I'll close this issue for now and we may decide to reopen it after we got enough practical cases from code review.
