### ISSUE TITLE
The quantization method should not delete the original function

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#1482]
A recent change broke the behavior of the quantization function and made it unfit for certain usecases, such as comparing the quantized and unquantized methods. The solution is simple -- just remove the erase method that was added.  

https://github.com/pytorch/glow/blob/master/lib/Quantization/Quantization.cpp#L437

**Comment by opti-mix** [comment]
@ZchiPitt I was pretty sure you fixed it already as we all agreed that this is the way forward. See https://github.com/pytorch/glow/pull/1458#issuecomment-413016807. Could you fix this trivial issue ASAP.

**Comment by ZchiPitt** [comment]
thx @rdzhabarov for fixing it. Sorry i should have done it earlier

**Comment by rdzhabarov** [comment]
no worries!
