### ISSUE TITLE
How do you guys run glow on ARM64 architecture

### ISSUE THREAD

**Issue by tkclimb** [pytorch/glow#1513]
In you guys technical report on arxiv (https://arxiv.org/abs/1805.00907),
there is line says glow machine code emit has been tested on x86 and ARM64 arch.
>> p7, 
>> It uses LLVM to optimize and emit machine code and was tested on x86 and ARM64

How do you guys emit the code for ARM? 
just compile this library on ARM64 machine directory? or cross compile, JIT, thing like not traditional compilation flow.

**Comment by hegemanjwh2** [comment]
@tkclimb -- Please feel free to cc me if you run into any issues.  :-)

**Comment by rdzhabarov** [comment]
@tkclimb closing this as answered, feel free to reopen if something is not addressed.
