### ISSUE TITLE
Random in Glow needs to be portable

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1557]
Currently, we have `PseudoRNG` class, which generates stable numbers from run to run, and each individual test is also stable. However, it uses `std::mt19937` and `std::uniform_int_distribution` inside, which return different results on different platforms: Mac, Linux, Windows. Probably need to rewrite `PseudoRNG` class to implement hand-written, known to be portable pseudo-random numbers generator.

**Comment by nadavrot** [comment]
This is a dup of #1556
