### ISSUE TITLE
[ONNXIFI] Support mandatory information queries 

### ISSUE THREAD

**Issue by rdzhabarov** [pytorch/glow#1567]
There will be some info request that must be
supported by the ONNXIFI implementation see here for details: https://github.com/onnx/onnx/pull/1345.

Make sure to get Glow ONNXIFI backend to the state that it's compatible with the required changes.

**Comment by nickgg** [comment]
@rdzhabarov @jackm321 is this still an issue?

**Comment by rdzhabarov** [comment]
I do not think it's used anyhow by the caller and does not seem to be blocking anything.
Closing for now.
