### ISSUE TITLE
Currently using floats for Select, CmpEQ, CmpLTE

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#1581]
Right now we are using `FloatTy` for Variables that are used as the `Condition` input to `Select`, when it really should be some sort of boolean/predicate type. Similarly our Interpreter backend creates outputs from `CmpEQ`/`CmpLTE` as float. This likely needs to be redesigned with some sort of boolean or predicate ElemKind.

One option could be to do this with a generic (no width-specified) `ElemKind::PredicateTy`. The idea here is to allow the backend to implement it with whatever bit width it wants. One issue is that Variables have their ElemKind specified independently of a backend/prior to picking or setting the backend. So we would need to allocate the tensors backing these Variables with some specific size prior to knowing what size the backend we are running with would like to use. The backend would need to convert them to the size the backend prefers.

Another option could be to add something like `ElemKind::Predicate8Ty`, where the bit width is explicit. The width would stay static and we could allocate tensors backing Variables with this width as such. Backends could still change the size of the predicate if they wanted once the Instruction level IR reaches it, i.e. in `Backend::compile()`.

Either way it does seem we will need the backend to massage the type to fit its internal representation. So in some sense these are different flavors of the same thing; e.g. if we used 8 as the default width for for the `ElemKind::PredicateTy` option it seems almost identical to just using `ElemKind::Predicate8Ty`.

**Comment by qcolombet** [comment]
I vote for using PredicateTy backed by a 8-bit width type for now.
Having the backend specify the size/internal layout of the tensor is something we would need in general in the future and this clean-up would fall in that category. (E.g., int32_t could be represented differently on different targets and we would need something to massage the bits to match what the target wants).

In other words, I don't thing we are ready nor it would get us anything for now to do something different here.
