### ISSUE TITLE
Eliminate runBatch

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#1587]
The execution engine provides a runBatch method that contains an internal static variable (global variable) that keeps track of the batch size. The batch size is calculated based on the first dimension of the input tensors. 

We should remove this method and replace it with some helper utility. The execution engine should not provide this strange interface. The runBatch replacement should rely on the run() interface that the execution engine provides.

**Comment by jfix71** [comment]
@nadavrot This can be closed thanks to https://github.com/pytorch/glow/pull/1594, correct?

**Comment by nadavrot** [comment]
@jfix71 Yes, thank you!
