### ISSUE TITLE
Consider using google benchmark for GemmBench

### ISSUE THREAD

**Issue by bertmaher** [pytorch/glow#1617]
We currently have a handrolled framework for benchmarking matrix multiplication, and it might be valuable to use a more rigorous framework, especially as we add more benchmarks.  (It might also be kind of annoying, hence the title of this issue starting with "Consider" ;-) ).

**Comment by rdzhabarov** [comment]
Since we'd need to run this on fbcode, I'd also look into folly benchmark for easier integration down the road.
https://our.intern.facebook.com/intern/wiki/Cpp/testing--benchmarking/#benchmarking

**Comment by nadavrot** [comment]
@rdzhabarov Before we add a new dependency to the project let's talk about the requirements. What problem are we trying to solve here?

**Comment by rdzhabarov** [comment]
@nadavrot I'm not proposing to add a dependency, but if we do, it would be worthwhile considering commonly used internal alternatives to google benchmark.

**Comment by hpwooten** [comment]
Before seeing these comments, I spent a little time looking into Google benchmark and wasn't convinced it was a good idea for Glow. After talking with Bert, we've decided against this approach.
