### ISSUE TITLE
PyTorch GLOW compilation takes a lot of RAM

### ISSUE THREAD

**Issue by csbenk** [pytorch/glow#1628]
Hey guys, I was trying to install GLOW on my local PC which has 16GB RAM. The RAM usage was 3.5 GB, before I stared building GLOW. After I stared the `ninja all` command, initially the RAM usage was around ~4.5-5GB. Later the RAM usage was full and it started moving stuff to SWAP and that's when my system started to hang. This was due to linking of some libraries. Atlast I could not install it in local PC, and had to install it on a azure machine, to work with it.
Is there a work around to install on a system with 16GB RAM?

**Comment by csbenk** [comment]
`CMAKE_BUILD_TYPE` param was set to `Debug` and I built LLVM using the `build_llvm.sh` script in `utils/` folder. 
I am away from my PC that I was working, I can get back to you on the library causing the issue only after tomorrow. I will let you know the library linking which was causing the issue then.

**Comment by tlepley-cadence** [comment]
I confirm the issue. I think this is due to the memory needed to link with LLVM. Each link process consumes more than 5GB of memory. I've got 24GB of memory, and I had to limit myself to `ninja -j 2` to avoid issues. Otherwise, my computer freezes and potentially crashes due to tremendous swapping.

**Comment by rdzhabarov** [comment]
@csbenk 
* Can you provide the full CMake command you are using
* Please, post the output of instruments or any other top/atop etc output for memory consumption.

I was running with instruments on my mac and `ninja all` did not consume any significant amount of memory.

**Comment by bertmaher** [comment]
Platform information would be useful too: OS and compiler version, as well as the version of LLVM you're linking against.

**Comment by csbenk** [comment]
I am so sorry for claiming that GLOW consumes lot of memory. It was LLVM. `bash build_llvm.sh` initally runs fine but as and on it reaches its end, it starts to consume more and more RAM. 
OS: Ubuntu 16.04

**Comment by csbenk** [comment]
I have not run the `ninja all` command to compile GLOW on my local PC as LLVM cannot be built.

Should I close the issue?

**Comment by rdzhabarov** [comment]
thanks for confirmation @csbenk

**Comment by tlepley-cadence** [comment]
As a side note: I  recompiled LLVM, in `Release` mode this time. It's much faster to link and consumes much less memory.

**Comment by csbenk** [comment]
Thanks @tlepley-cadence. Building LLVM in `Release` mode helped.

**Comment by csbenk** [comment]
Now I can build **GLOW** :smile:
