### ISSUE TITLE
[RFC] Provide a concise and readable textual representation for the Glow Graph

### ISSUE THREAD

**Issue by arnabde03** [pytorch/glow#1652]
Graph optimization unit tests in Glow requires the user to create the input Graph using C++ API which can be quite verbose, unintuitive and error-prone. A textual representation that is easy to read and write would help in writing unit tests and inspecting a Graph. 

### Example of an Graph optimization test written using C++ API
In the following example, an input Graph is created using C++ API and passed to the `optimize` call.
```c++
TEST_F(GraphOptz, optimizeBatchNormAfterConv) {
  Node *A = mod_.createVariable(ElemKind::FloatTy, {1, 10, 20, 3}, "A", 
                                VisibilityKind::Public, false);
  Node *CV = F_->createConv("conv", A, 16, 5, 1, 2, 1);
  Node *BN = F_->createBatchNormalization("batch", CV, 3, 0.0001, 0.9);
  F_->createSave("ret", BN);

  EXPECT_EQ(F_->getNodes().size(), 3);

  ::glow::optimize(F_, CompilationMode::Infer);
  EXPECT_EQ(F_->getNodes().size(), 2);
}
```

### Proposed textual representation of the input Graph and the corresponding unit test
```
@A = public <1 x 10 x 20 x 3>float zero

function @fct() {
  %conv = conv input:@A, depth:16, kernel:5, stride:1, pad:2, group:1
  %batch = batchnorm input:%conv, channel:3, epsilon:0.0001, momentum:0.9:float
  %ret = save input:%batch 
}
```
Global variables start with `@`, local variables start with `%`. A global variable declaration specifies the name of the variable, its type, visibility and initial value. A function is a sequence of "operation" nodes. Each node specifies its kind, has a list of named and optionally typed inputs and an optional output.

The unit test described in the previous section looks like the following:
```
TEST_F(GraphOptz, optimizeBatchNormAfterConv) {
  std::istream is = ... //read the input from a file/string
  readGraph(mod_, is);
  EXPECT_EQ(F_->getNodes().size(), 3);

  ::glow::optimize(F_, CompilationMode::Infer);
  EXPECT_EQ(F_->getNodes().size(), 2);
}
```
### EBNF Grammar for textual representation of a Glow Graph
```
<var_name> = <global_var_name> | <local_var_name>
<value> = <var_name> | <constant>
<scalar_type> = 'i32' | 'float' | ...
<tensor_type> = '<'<int_constant> {'X' <int_constant>} '>' <scalar_type>
<type> = <scalar_type> | <tensor_type>
<op_node> = <var_name> '=' <op_name> {<input_name>':'<value>[':'<type>]}
<function> = 'function '<function_name> '{' {<op_node>} '}'
<visibility> = 'private' | 'public'
<initial_value> = 'zero' | 'xavier'
<global_var_node> = <global_var_name> '=' <visibility> <type> <initial_value>
<module> = {<global_var_node>} {<function>}
```
Omitted some grammar rules such as `<op_name>` that are obvious in this context.

**Comment by qcolombet** [comment]
cc: @hegemanjwh2 @opti-mix @stoklund @nadavrot @beicy @bertmaher @rdzhabarov @artemrakhov @jfix71

**Comment by qcolombet** [comment]
Sounds good to me. Looking forward for a WIP patch to be able to play with it.

**Comment by opti-mix** [comment]
One possible way to create a parser for the textual representation could be to use some kind of a parser generator or a specialized library for parsing. And using a formal grammar could make it easier to maintain such a parser as compared to writing a parser manually. Though our current textual format is so simple that even writing a manual recursive-decent parser should not be a big deal.

The following C++ header-only library seems to be rather powerful and expressive:
https://github.com/yhirose/cpp-peglib

It seems like it should be rather easy to express any format we need using it.

**Comment by arnabde03** [comment]
@qcolombet  and @opti-mix: I have been trying to hand-write the parser. It's painfully slow and error prone. It would also be harder to extend and maintain. Should I abandon that and try cpp-peglib? What do you suggest?

**Comment by qcolombet** [comment]
Starting with peglib sounds reasonable to me, especially while we are designing what the syntax should look like.
If we want to not have this dependency we can decide later.

**Comment by opti-mix** [comment]
Writing a parser is really very easy with `cpp-peglib` and takes just a couple of hours. It is grammar-based and thus easy to understand and extend. Syntactic error handling is rather poor though, but this is not so important for a textual format as it is not a real programming language.

But before you start with any real implementation, it would be nice to first flesh out the concrete format and requirements.

For example, the current grammar your proposed above does not cover all aspects of the graph. It should be possible to express e.g. the following properties:
- weights, which are essentially tensors with pre-defined constant elements
- operations with multiple outputs
- ability to express that a given global variable is trainable
- quantization parameters like scale and offset (which are part of the type)

and there is probably more missing parts, that need to be part of the format.

**Comment by bertmaher** [comment]
This issue and #2098 are the same.  This one has better discussion but that one has a PR, so I'm closing this one (with a ref here from the other).
