### ISSUE TITLE
evaluation result in Glow's paper

### ISSUE THREAD

**Issue by xiaotiancd** [pytorch/glow#1689]
Hello, 
I noticed that you can get 15.5fps with ResNet50 for inference, which is actually very close to the theoretical float peak performance of the chosen CPU. so I am wondering if you already used the Quantization skill for the result, and what is the final accuracy of your inference. Say, TOP1 and TOP5 comparing with the ground truth? Thank you!

Cheers,
Xiaotian

**Comment by xiaotiancd** [comment]
@nadavrot  Thank you for your reply! that is really impressive! the CPU may have theoretical peak about 128 GFLOPS with a single core, a ResNet50 has 8GFLOP, you can handle 15.5 fps, then you got 8x15.5=124GFLOPS... A pure sgemm could only get around 85~90% of the peak(MKL and ESSL), really a perfect work. Let me have a try of your code! 

Cheers,
Xiaotian

**Comment by nadavrot** [comment]
@xiaotiancd  Please take a look at #1687  We actually had a bug in our implementation and we skipped some y-values.  Having said that, the regression that we have is too large, and we are falling back to the slow path too quickly, so we should be able to recover some of the performance that was lost in the regression that was discovered in #1687.
