### ISSUE TITLE
Is windows support on the horizon?

### ISSUE THREAD

**Issue by ankur6ue** [pytorch/glow#1696]
I see a couple PRs about windows support - any ETA on when it may be available?

**Comment by rdzhabarov** [comment]
We do not have a clear timeline for windows support yet, but would be very happy to accept external contributions!

There is currently an open issue for this (https://github.com/pytorch/glow/issues/1144), feel free to use that one if needed.

Closing this as a dup of https://github.com/pytorch/glow/issues/1144.
