### ISSUE TITLE
[New operator] SparseLengthsSumFused8BitRowwise

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1698]
We need to support `SparseLengthsSumFused8BitRowwise` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#sparselengthssumfused8bitrowwise

Also there is weighted version: `SparseLengthsWeightedSumFused8BitRowwise`
We already support float version: `SparseLengthsSum` / `SparseLengthsWeightedSum`

**Comment by rdzhabarov** [comment]
cc: @beicy ^

**Comment by artemrakhov** [comment]
@beicy : any updates on this? It is the most important among our unimplemented ops. Feel free to unassign if its not on your radar.

**Comment by beicy** [comment]
@artemrakhov Sorry,  forget that it is still assigned to me...  Unsigned it for now.

**Comment by jfix71** [comment]
@artemrakhov Were you going to take this? Otherwise I can work on it.

**Comment by artemrakhov** [comment]
No, I wasn't. Thanks for taking this, @jfix71
