### ISSUE TITLE
[New operator] LengthsRangeFill

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1699]
We need to support `LengthsRangeFill` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#lengthsrangefill

This operator requires dynamic memory allocation. Size of the output is the sum of all elements of the input.

**Comment by qcolombet** [comment]
Two questions:
1. Is the input known at compile time or could it come from an activation?
2. What type of network uses this? Put differently, how important is that operator?

**Comment by jfix71** [comment]
@jackm321 Still working/going to work on this, or can I take it from you?

**Comment by jackm321** [comment]
@jfix71 all yours
