### ISSUE TITLE
[New operator] DotProduct

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1701]
We need to support `DotProduct` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#dotproduct

**Comment by SplitInfinity** [comment]
Does it make sense to lower this to a `(1, M) x (M, 1)` `MatMul` followed by a `Reshape`?

**Comment by rdzhabarov** [comment]
can you expand a bit on the above?

The result of `(1, M) x (M, 1) MatMul` is 1*1, but the operator needs to produce a vector for both cases when inputs are vectors and when inputs are 2D matrices.

**Comment by SplitInfinity** [comment]
Ah yes, I should read the code next time before commenting. From Caffe 2 source code:

```
Computes and outputs the dot product of the two input float tensors `X` and `Y`.
Note that `X` and `Y` must be either 1D or 2D, and they must be the same shape.
The output tensor is 1D, which represents either the product of each element in
a respective dimension if the inputs are 1D, or the sum of the products in a
given dimension if the inputs are 2D matrices. Note that the actual dot product
is a scalar value, which is effectively the sum of the elements in the 1D
output tensor.
For 1D inputs:
Given two vectors $X = [x_0, x_1, x_2]$ and $Y = [y_0, y_1, y_2]$; $Z = [x_0 * y_0, x_1 * y_1, x_2 * y_2]$
For 2D inputs:
Given two matrices:
$$X = [[x_0^0, x_1^0, x_2^0], \\ [x_0^1, x_1^1, x_2^1], \\ [x_0^2, x_1^2, x_2^2], \\ ..., \\ [x_0^n, x_1^n, x_2^n]]$$
and
$$Y = [[y_0^0, y_1^0, y_2^0], \\ [y_0^1, y_1^1, y_2^1], \\ [y_0^2, y_1^2, y_2^2], \\ ..., \\ [y_0^n, y_1^n, y_2^n]]$$
then
$$Z =  \biggl[\Big((x_0^0 * y_0^0) + (x_1^0 * y_1^0) + (x_2^0 * y_2^0)\Big), \\ \Big((x_0^1 * y_0^1) + (x_1^1 * y_1^1) + (x_2^1 * y_2^1)\Big), \\ \Big((x_0^2 * y_0^2) + (x_1^2 * y_1^2) + (x_2^2 * y_2^2)\Big), \\ ..., \\ \Big((x_0^n * y_0^n) + (x_1^n * y_1^n) + (x_2^n * y_2^n)\Big)\biggr]$$
```

So it looks like this operator does an elementwise multiply if the inputs are 1D, and an elementwise multiply followed by reduce on one dimension if the inputs are 2D. I think we already have a `Mul` node in Glow, so I think we just need a Reduce operator to implement this.

**Comment by artemrakhov** [comment]
I agree with your last comment. Let's use element-wise `Mul`. And then `BatchedReduceAdd` for 2D case.

If we express this as `BatchedMatMul` and a bunch of reshapes, it won't be performant because vector-to-vector multiplication is quite slow.
