### ISSUE TITLE
[Documentation] libpng-dev missing from apt-get install list in README.md for ubuntu setup

### ISSUE THREAD

**Issue by Oewyn** [pytorch/glow#1703]
Trying to setup a new ubuntu 16.04 VM to test out glow and ran into a little snafu in the documentation.

libpng is listed in the system requirements header (and in the macOS brew header) but not in the ubuntu section. As a result, it took a bit of cmake digging to figure out why image-classifier wasn't being built at first.

**Comment by nadavrot** [comment]
@Oewyn Good catch!  Could you submit a pull request to fix the issue?
