### ISSUE TITLE
[New operator] BatchBoxCox

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1705]
We need to support `BatchBoxCox` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#batchboxcox

**Comment by SplitInfinity** [comment]
The computation performed by the transform is predicated on whether the input `lambda1` is zero, so I lowered this operator in such a way that does both computations and uses a `Select` node to pick between them. However, the `CmpEQ` interpreter instruction only works for `int64_t` (which makes sense). Does anyone have any pointers on how to proceed?

**Comment by SplitInfinity** [comment]
Based on https://en.wikipedia.org/wiki/Power_transform, `lambda1` can be a float tensor.

**Comment by rdzhabarov** [comment]
Some additions.

This needs ONNX loader and to make sure that CPU backend can run this fine.

**Comment by SplitInfinity** [comment]
@rdzhabarov 

Could you include some information about how to test as well?
