### ISSUE TITLE
Assertion failed: (Index < Length && "Invalid index!") when testing glow using onnx

### ISSUE THREAD

**Issue by zrphercule** [pytorch/glow#1736]
When I use onnx test driver to glowm it crashed on AveragePool test because of:
Assertion failed: (Index < Length && "Invalid index!"), function operator[]
This is a llvm related error, so I need to find which command caused this manually.

Finally I found out the crash is caused by this command in ONNX.cpp::loadOperator when dealing with averagepool:
auto *tr = G_.createTranspose(opName, in, NCHW2NHWC);

I wonder what is this G_  for (since I did not see any relative definition in ONNX.cpp), and why we are using NCHW2NHWC here?

**Comment by nadavrot** [comment]
@zrphercule Could you please upload the problematic ONNX file?

We convert NCHW to NHWC because we have one canonical representation of convolutions (and other ops). The optimizer will later clean things up.  G_ is the graph container that keeps the loaded ONNX function.

**Comment by zrphercule** [comment]
> @zrphercule Could you please upload the problematic ONNX file?
> 
> We convert NCHW to NHWC because we have one canonical representation of convolutions (and other ops). The optimizer will later clean things up. G_ is the graph container that keeps the loaded ONNX function.

Thanks, I will upload it tomorrow when I come back to office.

**Comment by bertmaher** [comment]
Will take a look now, thanks for reporting!

**Comment by bertmaher** [comment]
A couple notes for myself:
```
export ONNX_BUILD_TESTS=1
export LD_LIBRARY_PATH=~/src/onnx
mkdir ~/test_example/    # before copying the avgpool data
```
Also I had some stale build products with the bad ONNX_NAMESPACE, and incremental rebuild didn't seem to fix it.  Nuking my build dir and rebuilding from scratch was OK though.
