### ISSUE TITLE
Error when saving mnist example as bundle

### ISSUE THREAD

**Issue by nhynes** [pytorch/glow#1750]
Calling `EE.save` above [`EE.compile`](https://github.com/pytorch/glow/blob/master/examples/mnist.cpp#L137) causes the following error:
```cpp
../lib/Backends/CPU/LLVMIRGen.cpp:315:
llvm::Value* glow::LLVMIRGen::emitValueAddress(llvm::IRBuilder<>&, const glow::Value*):
Assertion
`allocationsInfo_.allocatedAddressed_.count(val) && "Value address was not allocated"'
failed.
```

It seems specific to the `EE.save` since the result of `-dump-llvm-ir` compiles just fine.

**Comment by nadavrot** [comment]
@nhynes I think that my recent changes to Placeholder broke the example. I will plan to work on it this week and see what I can do. At the moment we have a hack in the AOT bundler that splits the two kinds of variables (based on visibility). We need to un-hack this part and pass placeholders as parameters to the generated function.

**Comment by bertmaher** [comment]
This has been fixed, should be good to go.
