### ISSUE TITLE
Fix some "static initialization order fiasco" problems

### ISSUE THREAD

**Issue by bertmaher** [pytorch/glow#1765]
I can't tell that these are causing any problems, but I've seen the following things flagged by tools:

- In char-rnn.cpp, `PseudoRNG PRNG` is declared globally, but its constructor depends on a global variable `pseudoRandomSeed` defined in Random.cpp
- In `GlowJIT.cpp`, the command line parameter `dumpJITSymbolInfo` depends on `CPUBackendCat`, which is a global defined in `CPU/CommandLine.cpp`.

These dependences on global pre-main constructor ordering are dangerous and can lead to mysterious hard-to-debug failures.

**Comment by rdzhabarov** [comment]
Interesting! Nice finds, I'll fix shortly.

**Comment by bertmaher** [comment]
I got this from Infer: https://fbinfer.com/docs/checkers-bug-types.html
