### ISSUE TITLE
Tracking of quantization parameters lacks granularity

### ISSUE THREAD

**Issue by qcolombet** [pytorch/glow#1832]
Right now, the TensorQuantizationParams only tracks one type per NodeValue, whereas we would need one type for the output and one for each user of that value. E.g., for
```
val = node
= use1 val
= use2 val
```

We would want to track independently the types for the result of node, the use of val in use1, and the use of val in use2, in respectively `outTy`, `inTy1`, and `inTy2`, so that we can generate:
```
outTy = node
inTy1 = cast outTy
= use1 inTy1
inTy2 = cast outTy
= use2 inTy2
```

But instead what we track only one type like this:
```
outTy = node
= use1 outTy
= use2 outTy
```

However, sometimes `outTy` is not suitable for the input and sometimes, the outTy is not suitable for the output itself!
What this means basically is `outTy` encodes the `inTy` constraints whereas they may disagree.
This happens for cases where for instance, the quantized parameters for the output have a different scale than the input, whereas the operation itself doesn't allow that.
E.g., the constraints for `outTy = op inTy` are `outTy == inTy`, but the quantization profiling gave different types to `outTy` and `inTy`. To be more concrete here, LocalResponseNormalizationNode is one such node: the quantization of the output type may have different parameters of the quantization of the input type.

I am not sure if we need to fix the tracking of the quantization parameters or if we need to relax the type constraints on those operators. E.g., do we really need LocalResponseNormalizationNode to have the same scale and offset for its input and output, I am not sure. Perhaps we want to fix the verifier to check that the element type and dimensions are the same. Or maybe we want both! (the finer granularity and the relaxed verifier check)

@rdzhabarov what do you think?

**Comment by aturetsk** [comment]
Regarding LRN in particular, we have cases where input and output scales differ significantly, so removing inTy == outTy restriction would help to improve accuracy.

**Comment by rdzhabarov** [comment]
Effectively quantization params just telling you the range which is produced out of the NodeValue (given node and given output of the node).
I do not see how quantization params would be different per usage, effectively it's the same values profiled.

The main motivation for keeping the output type the same as input type was the simplicity of implementation of a particular operator, which admittedly might also reduce accuracy after subsequent rescaling (if such rescaling added).

So, it's not only the question of relaxing checks on input/output params but having interpreter/cpu/etc implementation to handle this. That feels like a way to go.

**Comment by qcolombet** [comment]
I agree with the relaxing part and the implications on the backends.

On a related note should the backend has a say on how things are quantized?

E.g., maybe both inputs of a matmul need to be quantized the same way. Do we want to handle that in the quantization of the function or do we want every backend to fix up the representation the way it needs it later on?
Put differently, do we relax the IR and have the backends constrain it again or do we hand over a backend specific constrained model to the backends?

I suspect the answer lies in the middle: the quantization works without constrain in mind, but we provide a "constrainer" to massage the graph before handing something to a backend.

**Comment by nickgg** [comment]
@jfix71 is this still relevant after your refactor?

**Comment by jfix71** [comment]
None of my changes have impacted this really. I'm not sure there's anything to do here -- we could relax quantization constraints, but that's not even really the point of this issue. I think I'll just close it for now -- @rdzhabarov if you disagree feel free to reopen.
