### ISSUE TITLE
[CI] Migrate to CircleCI and explore better parallelism

### ISSUE THREAD

**Issue by rdzhabarov** [pytorch/glow#1836]
Travic CI runs are slow and there is a lot of contention on concurrent runs which slows down iteration on PRs from serval contributors.
See more details in https://github.com/pytorch/glow/issues/1763.

We would like to run even more tests which might take longer, see [here](https://github.com/pytorch/glow/issues/1257). 

This issue is to track progress on migrating Glow CI infrastructure to CircleCI.
See more details on CircleCI [here](https://circleci.com/docs/2.0).

**Comment by rdzhabarov** [comment]
see https://github.com/pytorch/glow/pull/1833 for some of the configuration added for CircleCI.

**Comment by rdzhabarov** [comment]
@zrphercule it looks like you are planning to tackle this. based on the latest quip I see ;)

**Comment by bertmaher** [comment]
Closing since we're on CircleCI now!  Thanks @zrphercule!
