### ISSUE TITLE
[GraphOptimizer] Single use requirement for constant node in optimizeTranspose

### ISSUE THREAD

**Issue by aturetsk** [pytorch/glow#1839]
In optimizeTranspose we require for constant node to have a single use, however for the optimization to be correct it's not required because we create a new constant node with transposed data.

So why do we have this requirement? To avoid increasing memory footprint, similar to constant folding in optimizeReshape? Does it make sense, because as opposed to folding reshape, folding transpose saves cycles needed for data movement during runtime?

https://github.com/pytorch/glow/blob/f71543d88781ff1a8ed9d7fd30f1487fdd55b69f/lib/Optimizer/GraphOptimizer.cpp#L1301-L1323

**Comment by jfix71** [comment]
>To avoid increasing memory footprint, similar to constant folding in optimizeReshape?

Yes, I believe that is the motivation. There is of course a tradeoff here, and it's absolutely possible some backends may prefer to duplicate the Constant and transpose it instead, but for now there is no way for the backend to control this optimization. This is related to https://github.com/pytorch/glow/issues/1641

**Comment by jfix71** [comment]
@aturetsk I'm going to close this but feel free to re-open if you have further questions or comments.
