### ISSUE TITLE
[CPUBackend] Question about internalization

### ISSUE THREAD

**Issue by aturetsk** [pytorch/glow#1860]
Not really an issue, just a question related to internalization pass in CPU backend...

We internalize the symbols with the following name:
https://github.com/pytorch/glow/blob/f61e6c72abd04462ca25c3917176aabf38830093/lib/Backends/CPU/Pipeline.cpp#L67-L70

Doesn't it make sense to just internalize everything except "jitmain" (and declarations), as we know that this is the function we're going to call to run the model?

**Comment by nadavrot** [comment]
Yes, I think that it would make sense to just keep jitmain. Good catch.

**Comment by opti-mix** [comment]
@aturetsk In principle it makes sense. But there were some rather subtle issues related to what is internalized and when. Unfortunately I don't remember anymore what it was ;-( IIRC, it was something related to debugging support and/or AOT support. So, if we change something here, we need to check that AOT and debugging support still work.

**Comment by aturetsk** [comment]
Thanks for clarifying this. I do see additional symbols (constWeightsBaseAddress, mutableWeightsBaseAddress, activationsBaseAddress) being preserved by the internalization pass, in case debug info is enabled.
If I understand correctly, we don't want them to disappear to be able to access them in debugger.
Closing the issue.
