### ISSUE TITLE
[New operator] LengthsSum

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#1884]
We need to support `LengthsSum` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#lengthssum

One has to create new Graph-level Node (`LengthsSumNode`), create new low-level IR instruction, and implement it for Interpreter and CPU backends, also adding a unit test to `OperatorTest.cpp`.

Note, that this operator is similar to `SparseLengthsSum`. Probably significant part of code can be taken from there.

**Comment by nadavrot** [comment]
@artemrakhov Can we come up with a way to reduce the number of operators by sharing some of the underlying elements (primitive nodes)?

**Comment by artemrakhov** [comment]
Not sure how can we do it with this node. SparseLengthsSum does implicit in-memory gather, it accumulates elements right away. LengthsSum takes what needs to be accumulated as an input (e.g. from GatherNode or some other node), and does same accumulation.

**Comment by SplitInfinity** [comment]
@rdzhabarov 

Do we need ONNX support for this as well? If so, I can do both in one PR this time.

**Comment by rdzhabarov** [comment]
@SplitInfinity 

Yes, ONNX + CPU support will be needed.
Also, make sure that onnxifiGlow could support this operator as well.
