### ISSUE TITLE
Is writePngImage broken?

### ISSUE THREAD

**Issue by qcolombet** [pytorch/glow#1914]
I wrote a simple test in #1913 that reads an image in a tensor, writes the tensor in a new image, and reads the new image in another tensor.
I was expecting the tensors from both read to have the same values, but that's not the case.
Moreover, the file written with writePngImage is black and its size is strange.

Am I using writePngImage incorrectly (e.g., the range parameter) or is there a bug?

Note: The image I used in #1913, cat_285.png, can be obtained with our download scripts.

**Comment by rdzhabarov** [comment]
Fixed by the PR above.
