### ISSUE TITLE
[Runtime] Factor runtime logic out of CompiledFunction

### ISSUE THREAD

**Issue by gcatron** [pytorch/glow#1951]
With the work on #1904  CompiledFunction and it's inherited forms contain the runtime execution logic. It would be better to keep the function as a container that is acted upon. This would keep logic and storage separate. 
Design a runtime API and migrate runtime functionality from CompiledFunction to new API.

**Comment by nickgg** [comment]
@gcatron what's the status of this one?

**Comment by bertmaher** [comment]
Habana is also done so we can close this out :)
