### ISSUE TITLE
[runtime] Pass Input Output Placeholder labels

### ISSUE THREAD

**Issue by gcatron** [pytorch/glow#1953]
From the Context it's not easy to efficiently identify whether a placeholder is an input or output. This means all placeholders may be copied to and from the device. It would be good to pass this information to runtime to make device loading/unloading more efficient.

**Comment by rdzhabarov** [comment]
it's not fixed

**Comment by bertmaher** [comment]
Oh hey this is interesting and I hadn't noticed that it was referenced on my PR #2160.  I don't think that PR was the right solution though.  From the perspective of the runtime, I think we probably care about WeightVars more than Placeholders (does that seem correct?)
