### ISSUE TITLE
Need to support `BatchMatMul` and `ExpandDims` in ONNXIFI loader

### ISSUE THREAD

**Issue by yinghai** [pytorch/glow#1970]
Glow already supports those ops. We just need to update the ONNXIFI loader to do it.

**Comment by rdzhabarov** [comment]
I'll check the expand dims really quick, should be trivial (i hope :D)

**Comment by yinghai** [comment]
`ExpandDims` is very trivial, just move it to loadCommonOperator.

**Comment by rdzhabarov** [comment]
> ExpandDims is very trivial, just move it to loadCommonOperator.

Right on!
