### ISSUE TITLE
[wishlist] Use Jemalloc in one of the CI tests

### ISSUE THREAD

**Issue by yinghai** [pytorch/glow#2003]
Facebook uses Jemalloc for allocation. It seems to have different behavior regarding allocation 0 bytes. We can try to use jemalloc in CI to flush the problem in OSS CI earlier.

**Comment by rdzhabarov** [comment]
The right solution would probably be to have bidirectional sync between fbcode and github on a per commit bases.

**Comment by yinghai** [comment]
Bidirectional sync is very dangerous...

**Comment by rdzhabarov** [comment]
> Bidirectional sync

By this I mean to use standard set of tools like ShipIt and ImportIt.
