### ISSUE TITLE
[ONNXIFI] Top level task for complete ONNXIFI support

### ISSUE THREAD

**Issue by rdzhabarov** [pytorch/glow#2069]
## Introduction
There are two ways to execute neural nets through the Glow compiler:
* Use Glow as a stand alone compiler and load Caffe2/ONNX models, see, [ImageClassifier](https://github.com/pytorch/glow/blob/master/tools/loader/ImageClassifier.cpp) for example
* Make Glow embedded into Pytorch/Caffe2 via [ONNXIFI](https://github.com/onnx/onnx/blob/master/onnx/onnxifi.h) interface

The purpose of this issue is to cover completed work for ONNXIFI support, but more importantly outline future plans.

## Current state
* At this point we've made a lot of progress and can execute CV models, see, [Resnet50](https://github.com/pytorch/glow/issues/1190) support.
* More sophisticated models which involves various operators can be executed as well, see, list of related closed issues [here]().
* Support of concurrent execution was added allowing to throttle incoming Pytorch/Caffe2 concurrency to concurrency level supported by a specific Glow backend.

## Future work
* Stability and error handling is one of the most important aspects that needs to be in place
* Execution of quantized int8 and fp16 models through the ONNXIFI interface
* Improved debugging experience, per operator logging/statistics
* More to come :)

**Comment by yinghai** [comment]
More issue to consider: https://github.com/pytorch/glow/issues/2071

**Comment by nickgg** [comment]
@jackm321 @rdzhabarov feel free to reopen if this is useful.

**Comment by jgong5** [comment]
A question: is this the (only) way how PyTorch would be integrated with GLOW? If so, would the support of PyTorch training model depend on ONNX training support?

**Comment by yinghai** [comment]
@jgong5 We are working on integration of PyTorch/Glow. Stay tuned.

**Comment by wyessen** [comment]
It would be helpful to have an end-to-end, standalone ONNXIFI example.
