### ISSUE TITLE
More initialization kinds and possibly refactor initialization mechanism

### ISSUE THREAD

**Issue by goldsborough** [pytorch/glow#209]
A thing I noticed a while ago was that the initialization algorithm of a variable is currently [embedded in the representation of the `Variable` class itself](https://github.com/facebookexternal/Glow/blob/master/include/glow/Graph/Nodes.h#L15). Given that in practice people may want to use quite a [variety of initialization kinds](https://keras.io/initializers/), it may be a little unscalable to modify the core `Variable` class for each new initialization algorithm, and clutter `Nodes.cpp` with initialization algorithms that may best be put somewhere else. Maybe it's worth thinking of how the initialization code can be kept separate from `Variable` itself. This is just a thought. I'll look into how other libraries and frameworks deal with this.

Either way adding a few more initialization algorithms may be worthwhile for the future.

**Comment by nadavrot** [comment]
@goldsborough I recently refactored Variable and not initialization is not a part of the variable.
