### ISSUE TITLE
How to load low-level IR from a text file

### ISSUE THREAD

**Issue by QiJune** [pytorch/glow#2098]
LLVM provides a method `ParseIRFile` to load LLVM bitcode from a file.
If I write a text file of Glow low-level IR, how can I load it to Glow Compiler? This feature is very useful for debuging if I want to add some new instructions. I can try and verify it quickly.
Is there any suggestion? Thanks!

**Comment by qcolombet** [comment]
We don't have anything like that yet.
@opti-mix made some prototyping as part of #1652, which was for the graph IR, not the low level IR, but we could use something similar for that.
@QiJune would you like to develop this feature?
