### ISSUE TITLE
Add Autoencoder example

### ISSUE THREAD

**Issue by goldsborough** [pytorch/glow#210]
An autoencoder is a very basic neural network that takes in some input, encodes it into a lower-dimensional representation, and then decodes it back into something that should ideally be identical to the input. We should try to implement such an autoencoder with Glow. An extension of this would be to make a variational autoencoder.

**Comment by nadavrot** [comment]
@goldsborough:

@artemrakhov implemented the french-to-english language converted a while ago. I assume that his work satisfies this ticket.
