### ISSUE TITLE
How to solve address space issue

### ISSUE THREAD

**Issue by zakk0610** [pytorch/glow#2108]
Hi glow team,

Currently the Glow does not aware the CopyInstr is working on same address space or not in the backend,
so the IR Optimizer will eliminates different address space CopyInstr if the backend enables `shouldShareBuffers`.

My question is : What's designed purpose of `shouldShareBuffers` parameter? Disable `shouldShareBuffers` can work around this issue but it's not look like a good solution.

another solution is always enabling `shouldShareBuffers` but the backend need to insert custom load/store after optimization to keep the semantic.

Thanks.

**Comment by nadavrot** [comment]
@zakk0610 @opti-mix I agree with opti-mix's comment. I'd like to add that you could add a new kind of copy instruction (like copyToSRAM), and like opti-mix said, the optimizer won't touch these instructions. I wonder if we have good examples of where we perform low-level IR-level optimizations.

**Comment by zakk0610** [comment]
@opti-mix @nadavrot 
This is one backend scenario which has three types of [memory space](https://sophon-edge.gitbook.io/project/getting-started/bmnnsdk-framework#bmmemory). Compiler and runtime are responsible for global/local memory allocation/management.
In this backend HIR, the SaveNode has a semantic of copy result from Local memory to global placeholder

It's look like to adding custom translation to translate `SaveNode` into `SaveSRAMNode` is better solution in this case? Thanks.
