### ISSUE TITLE
Mismatch between CMake required version and Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by bertmaher** [pytorch/glow#2121]
The README claims Glow works with Ubuntu 16.04, but I just tried it and it complains that my CMake is too old -- and indeed, 16.04's cmake package is 3.5.1, and we require 3.7.

Is there any reason to require 3.7?  Can we drop back to something suitable for Ubuntu 16.04?

cc @hegemanjwh2 since I think you did a bunch of the Ubuntu testing.

**Comment by rdzhabarov** [comment]
cc: @compnerd

**Comment by hegemanjwh2** [comment]
Gah...  I will look at what I have set up on my machine...

**Comment by bertmaher** [comment]
I changed our requirements to 3.5 and have heard no complaints, so I'm going to assume everything is resolved here :-)
