### ISSUE TITLE
Error in LLVM GDBRegistrationListener.cpp: "Second attempt to perform debug registration."

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#2123]
Some time ago, we've got some issues running Glow unit tests (operatorTest for instance) with the CPU backend and with LLVM 6 under Linux (Redhat 6): `"Second attempt to perform debug registration."`.  By switching to LLVM 7, this error disappeared. But recently, it reappeared, with LLVM 7.

Observations:
- When Running `tests/operatorTest` multiple times, the error is triggered but for different tests. Running the failing test individually doesn't trigger the error. 
- I can't reproduce the problem when running  `tests/operatorTest` in `gdb`
- I can't reproduce the error when running `tests/operatorTest`  with`valgrind` and valgrind detects no error. 
- The unit tests fail when LLVM is compiled in `RelWithDebInfo` mode. In another environment where LLVM is compiled in `Release` mode, the problem doesn't show up (certainly because `assert` disappear in release mode).

Anyone has an idea what it can be ?

The actual error message:
``
operatorTest: llvm/lib/ExecutionEngine/GDBRegistrationListener.cpp:168: virtual void {anonymous}::GDBJITRegistrationListener::NotifyObjectEmitted(const llvm::object::ObjectFile&, const llvm::RuntimeDyld::LoadedObjectInfo&): Assertion `ObjectBufferMap.find(Key) == ObjectBufferMap.end() && "Second attempt to perform debug registration."' failed.
``

@aturetsk

**Comment by tlepley-cadence** [comment]
Note that under Redhat 6, LLVM 7 is compiled in mode `RelWithDebInfo`. In Fedora, LLVM 7 is compiled in mode `Release`. I assume assert disappear in `Release` mode and it could explain why no issue is detected.

**Comment by tlepley-cadence** [comment]
@aturetsk I've not seen this problem recently. Can we close the issue ?

**Comment by aturetsk** [comment]
I haven’t seen the issue since we switched to LLVM 7, so I guess we can.

Best regards,
Andrey Turetskiy

**Comment by nickgg** [comment]
@tlepley-cadence is this till an issue with llvm 7?

**Comment by aturetsk** [comment]
@nickgg, I don't see this issue for LLVM 7 anymore. It did start appearing again when I tried LLVM 10, so I had to address the problem the same way: #4990
