### ISSUE TITLE
Which clang-format configuration ?

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#2131]
Recently, I started to have more issues with the clang-format formatting. Typically, it seems that my clang-format configuration wants comment a bit shorter than what is sometimes in source files (this is not a general problem, it happens some time to time).

My IDE is configured to run clang-format with the 'LLVM predifined style' (I don't know the exact command).  

For instance, today, clang-format wants to do this change:
``` 
-        // We may be able to optimize this rescale node. Remember to visit this
-        // new node and try to optimize it later.
+        // We may be able to optimize this rescale node. Remember to visit
+        // this new node and try to optimize it later.
```

Which exact clang-format configuration is expected for Glow ? Is it defined somewhere ?

**Comment by nadavrot** [comment]
Clang format changes slightly between versions. To handle the small differences between the versions we've expanded the predefined style into a list of rules that are stored in the .clang-format file at the root of the project. The format scripts use this file when formatting the project. If the IDE does not agree with the formatting scripts then please prefer the formatting scripts.

**Comment by bertmaher** [comment]
In CI we install clang-format-6.0: https://github.com/pytorch/glow/blob/master/.travis.yml#L53, so give that a try if you're seeing version-related differences.

**Comment by bertmaher** [comment]
If there's nothing else to be done here, I'm going to go ahead and close the issue.
