### ISSUE TITLE
text-translator is broken after #2122

### ISSUE THREAD

**Issue by qcolombet** [pytorch/glow#2135]
After #2122 landed, text-translator (and maybe other loaders) fails with a segmentation fault.

To reproduce download the caffe2 models `utils/download_caffe2_models.sh`
Build text-translator (in release mode otherwise that's super slow)
Run:
text-translator -m <pathToDownloadModels>/en2gr -cpu <<< "I love music ."

Noticed because the lit tests are failing in #2097, i.e., the new testing infrastructure is already finding bugs whereas it is not landed yet :P.

**Comment by tlepley-cadence** [comment]
I didn't manage to assign this issue to myself (I guess I'm not allowed to by github), but I reproduced and fixed the issue in #2139 .
