### ISSUE TITLE
[ONNXIFI] Add a doc for ONNXIFI glow integration

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2184]
Add a document to /docs with details about
* Overview of glow's ONNXIFI code
* Which ONNX nodes glow currently supports
* How to run ONNXIFI node tests

**Comment by jackm321** [comment]
@rdzhabarov that's true, maybe we can start with documenting the onnxifi code, I'm not sure exactly what the best way to autogenerate the list of nodes supported is to populate the node documentation yet.

**Comment by nickgg** [comment]
@jackm321 feel free to reopen.
