### ISSUE TITLE
[ONNXIFI] Various fixes for onnxGetBackendCompatibility

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2190]
* onnxGetBackendCompatibility calls `glow::lower()` to lower graph nodes to what the backends would expect to see but doesn't delete the original nodes so DCE should be run.
* `verify()` should be run on the graphs created by `onnxGetBackendCompatibility` in order to check that they are indeed valid graphs
* `Backend::transformPreLowering()` should be called on the loaded graphs before lowering

**Comment by rdzhabarov** [comment]
@jackm321 can you link all those ONNXIFI issues to https://github.com/pytorch/glow/issues/2069 for better tracking.
