### ISSUE TITLE
[ONNXIFI][Top Level Task] Export per-operator stats

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2191]
Export per-operator statistics for profiling operators. This data will need to be collected from the Glow runtime (DeviceManagers specifically) and exported across the ONNXIFI interface (which doesn't yet support the collection of this information). The first thing to do here is to collect a list of useful statistics to be exported.

**Comment by nickgg** [comment]
@jackm321 this is done with @yinghai's addition, right?
