### ISSUE TITLE
[ONNXIFI] Support quantized int8/int16 and fp16 models on the ONNXIFI interface

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2192]
General support for quantized and fp16 models is required.
`onnxGetBackendCompatibility` should check the specific type of each operator with the backend instead of assuming FloatTy.

**Comment by RanACohen** [comment]
Which ONNX proto def will be used to represent the quantized model?

**Comment by jackm321** [comment]
cc @rdzhabarov

**Comment by rdzhabarov** [comment]
@RanACohen 
We recently added C2 support through the ONNXIFI so they could be originated from C2 model, for example (and we have some examples of quantized_resnet50 for c2 models).

**Comment by rdzhabarov** [comment]
This is already fixed: `!glowBackend_->isOpSupported(node)` takes care about input/output types.
