### ISSUE TITLE
[ONNX] Assertion `TR->size() == input.getType()->size() && "Reshape to a different size"' failed.

### ISSUE THREAD

**Issue by rosierm** [pytorch/glow#2195]
I'm running into the following assertion when trying to generate a quantization profile for Resnet50 imported from the ONNX zoo:
glow/lib/Graph/Graph.cpp:649: glow::ReshapeNode *glow::Function::createReshape(llvm::StringRef, glow::NodeValue, llvm::ArrayRef<size_t>): Assertion `TR->size() == input.getType()->size() && "Reshape to a different size"' failed.

Assuming assertion are enabled the command to reproduce the issue is:
$TOOLS_DIR/build/glow-release/bin/image-classifier -use-imagenet-normalization $TOOLS_DIR/glow/tests/images/imagenet/cat_285.png $TOOLS_DIR/glow/tests/images/imagenet/dog_207.png $TOOLS_DIR/glow/tests/images/imagenet/zebra_340.png -image-mode=0to1 -m=$TOOLS_DIR/networks/resnet50/model.onnx -model-input-name=gpu_0/data_0 -quantization-schema=symmetric_with_uint8 -dump-profile=/tmp/resnet50-onnx-symmetric_with_uint8.yaml

Where the TOOLS_DIR is structured as follows:
$TOOLS_DIR/glow - glow source repo
$TOOLS_DIR/build - build directory
$TOOLS_DIR/networks - directory where ONNX models are downloaded

I also noticed you must also use 2 or more input images to reproduce the problem.  The assertion is being hit when createReshape() is called by loadReshape() in the CommonOperatorLoader.

**Comment by rosierm** [comment]
Per https://github.com/onnx/models/issues/114, I believe you're correct, Bert.

One more question:  Given the limitation of this model is there another way to generate a quantization profile using multiple inputs?  For example, can we update a profile when provided new training inputs?  E.g., create a profile using the cat input, update using the dog input, and then update again using the zebra input to get the full profile..

**Comment by bertmaher** [comment]
I can't remember if our quantization profiling allows the model to be run multiple times to accumulate the profile histograms.  If it does, then we should be able to use that approach with image-classifier.  @rdzhabarov do you know off the top of your head?

**Comment by jfix71** [comment]
You can do this using streaming mode in the ImageClassifier (i.e. pass `-` instead of filenames). I used the script at `utils/imagenet_topk_accuracy_driver.py` to generate a profile on a subset of ImageNet in this way.

**Comment by bertmaher** [comment]
Thanks @jfix71!  Looks like this is resolved, then -- I'll close it out but please reopen if that approach isn't working out for you.

**Comment by rosierm** [comment]
Thanks, Bert/Jordan!
