### ISSUE TITLE
[New operator] GatherRanges

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#2210]
We need to support `GatherRanges` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#gatherranges

It is not possible to lower this operation. It needs to be implemented for every backend. See `Gather` for guidance on how to implement, it is very similar op.

**Comment by SplitInfinity** [comment]
I'd like to work on this. But doesn't this require dynamic shapes? The type of `lengths` can be inferred from the types of the inputs but isn't the shape of `output` dynamic?

**Comment by artemrakhov** [comment]
Indeed, exact shape of `output` is only determined at runtime.
I suggest to pass additional argument to `createGatherRanges`: `maxOutputSize`. So we'll allocate memory up to that limit, but possibly won't use it all. `lengths` content will hint users of `output` about what is actual size. It is up to higher level framework to pass correct `maxOutputSize`. It also will need to be added to proto (Caffe2 or ONNX).

**Comment by yinghai** [comment]
> It is up to higher level framework to pass correct maxOutputSize.

We need to communicate this the whoever created the model, right?

**Comment by artemrakhov** [comment]
> We need to communicate this the whoever created the model, right?

Right. Can we change the operator's semantics? Introduce this new argument to the protobuf.
