### ISSUE TITLE
[model zoo] Load more quantized models

### ISSUE THREAD

**Issue by rdzhabarov** [pytorch/glow#2212]
There are some more quantized models available from C2 model zoo which we should be able to load in Glow:
* [MobileNet quantized](https://github.com/caffe2/models/tree/master/mobilenet_v2_quantized)
* [Mask RCNN](https://github.com/caffe2/models/tree/master/mask_rcnn_2go/model/int8)

**Comment by beicy** [comment]
I will take a look at these two models.

**Comment by beicy** [comment]
There are multiple libraries supporting quantization. The quantized operators we supported now are for supporting server side quantization with DNNLOWP. But these two models uses the Caffe2's Int8*** operators lib for mobile quantization. That is, the Int8** ops set is different from what we've supported.  For example, in these 2 models, there is a "Int8Softmax", which is not used/supported in server side quantization. (I haven't  checked that the ops with same name in two libraries have the same functionality yet). If I remember it correctly, Glow is targeting server side. So, do we still need to support the operator library of these 2 models ? Thanks! @rdzhabarov

**Comment by rdzhabarov** [comment]
> If I remember it correctly, Glow is targeting server side. So, do we still need to support the operator library of these 2 models

If it's mobile only I'd skip those. One thing which worthwhile doing is to check list of ops and see what would make sense to have in our C2 loaders. Maybe look at some other real workloads with quantized server models.

**Comment by beicy** [comment]
@rdzhabarov Thanks!
This page lists the quantization ops used in server models: https://github.com/pytorch/pytorch/tree/master/caffe2/quantization/server#quantization-operators
Then I will close this issue and create another one to track implementing these quantization ops.
