### ISSUE TITLE
onnxtxt generation for tests

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#2303]
I'm fixing an issue in the ONNX importer and as usual, I'd like to create a test. 
For this, I need to create a onnxtxt file. 

Until now, I was doing it manually, because it was simple cases. This time, I would prefer to copy-paste a subset of an actual ONNX model. But I'm struggling for converting an onnx file into an onnxtxt file. Looking at the ONNX code, it doesn't seem they have an option to dump the text version and I didn't find much information on the web.

Any idea how to convert onnx models into onnxtxt files ?

**Comment by bertmaher** [comment]
An onnx model is just a protobuf, so you should be able to use a simple python script like
```
import onnx
model = onnx.load("model.onnx")
open("model.onnxtxt", "w").write(str(model))
```

**Comment by tlepley-cadence** [comment]
@bertmaher It works well this way. Thanks !
