### ISSUE TITLE
Breaks windows build __atribute__(format....

### ISSUE THREAD

**Issue by ayermolo** [pytorch/glow#2305]
https://github.com/pytorch/glow/blob/240a78df4d7ee001692b1fe0b25cf62d5ead3ddf/include/glow/Support/Support.h#L116

Poking around doesn't look like there is an equivalent of this for VS. Maybe ifdef __atribute__ part for windows build?

**Comment by nadavrot** [comment]
@ayermolo Good idea. Let's un-break the windows build.

**Comment by opti-mix** [comment]
@ayermolo  Yes, I like the idea of using the` #ifdef`

Do you want to provide a small PR for it? We cannot build for Windows on our CI here, so we need someone with access to Windows and VS to test it.

**Comment by ayermolo** [comment]
Done.
Thanks
