### ISSUE TITLE
[Support] Fix ThreadPool on Windows

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#2309]
Visual Studio has a bug where it uses std::function as the backing for std::packaged_task, which doesn't allow non-copyable types in the lambda capture of tasks. This is an issue for us as we use (at least) std::unique_ptr and std::promise which are both noncopyable.

We probably will need a function wrapper that fixes this. In the comments on #2154 @ayermolo  suggests a shared_function approach that moves the lambda object into a shared_ptr which can be copied.

**Comment by ayermolo** [comment]
@nickgg  Thanks for filing this.
One potential fix: https://github.com/Cadence-TIP-AI/glow/commit/c6d4fa82ce0c1951bd824d3ea64f7a3a962257cf

**Comment by nickgg** [comment]
I shifted it around so it's all transparent in the ThreadPool and only on Windows: https://github.com/nickgg/glow/commit/4c3daaa00f97a40e99e7e47e4b7da08a3e5dc312

I haven't tested this on actual VS yet (will borrow a laptop first thing tomorrow), but I've tested it by forcing a std::function wrapper and it fixes the problem for me.

@ayermolo if you get a chance can you give that branch a try? ninja test should do it.

**Comment by ayermolo** [comment]
Thanks for cleaner implementation.
Entire solution builds, after fixing some type stuff (unrelated).
Rand ThreadPoolTest and UtilsTest Pass. In debugger stepped through moveCaptureTest. Everything seems to be captured correctly, and shared_ptr gets cleaned up on exiting the scope, which cleans up unique_ptr.

**Comment by nickgg** [comment]
I've put up that patch then, thanks for your patience with this one.
