### ISSUE TITLE
[New operator] Mod

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#2330]
We need to support `Mod` operator from Caffe2. Spec can be found here:
https://caffe2.ai/docs/operators-catalogue.html#mod

**Comment by jackm321** [comment]
@artemrakhov are you planning on working on this? If not I could help out with it

**Comment by SplitInfinity** [comment]
@jackm321 

Are you still working on this? If not, can I have it?

**Comment by jackm321** [comment]
@SplitInfinity yes see #2345

**Comment by rdzhabarov** [comment]
We'd also need CPU backend implementation since it's painfully slow for running on ONNXIFI.

**Comment by Squadrick** [comment]
@rdzhabarov Can I work on this? Any help to get started would be appreciated.
