### ISSUE TITLE
Running fr2en quantized is broken

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#2338]
Dumping a profile of `fr2en` appears to work fine. However when loading the profile to quantize and then run, currently it segfaults in Release mode, and fails this assert in Debug mode (inside the FunctionQuantizer):

https://github.com/pytorch/glow/blob/31eb569ab3ce0d3c7d7ad1ef098a3439121e3c64/lib/Quantization/Quantization.cpp#L317-L320

**Comment by nadavrot** [comment]
Thank you for fixing this.
