### ISSUE TITLE
[ONNXIFI] Support function families via caffe2 protos

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2355]
Function families will be provided as different args in [`NetDef.arg`](https://github.com/pytorch/pytorch/blob/c5c831953be2c7e2a4480d07d5d0e0753f9987aa/caffe2/proto/caffe2.proto#L296). This will need to be read as multiple functions in the same module here.

https://github.com/pytorch/glow/blob/53eb17beb3818ea7fe37efcfa44c77f95bb9c192/lib/Importer/Caffe2ModelLoader.cpp#L880

Currently model loaders only work with one function which is passed to the constructor. This will either need to be changed or multiple model loaders will be needed, one per family member, and loadInputs will need to be changed to only load the inputs for one family member.

cc @yinghai

**Comment by yinghai** [comment]
Sounds good to me.

**Comment by rdzhabarov** [comment]
> multiple model loaders will be needed, one per family member

Be careful with the potential weight duplication in any case, we'd want to load that once.

**Comment by jackm321** [comment]
@rdzhabarov yes I'll create a more detailed plan in the next couple of days but we'll have to sort of separate weight loading from the rest of the model loading so that we do that once.

**Comment by nickgg** [comment]
@jackm321 nothing to do here since we dropped function families?
