### ISSUE TITLE
[GLOW] Gray scale png images require replication of 1 channel to 3 channels for networks that require 3 input channel

### ISSUE THREAD

**Issue by suyash-cadence** [pytorch/glow#2380]

**Comment by suyash-cadence** [comment]
When passing gray scale images to glow, alexnet fails due to shape mismatch of input image and input Placeholder.

**Comment by nadavrot** [comment]
The models in our model zoo require 3 channels (RGB). Why is it legal to pass grayscale?

**Comment by suyash-cadence** [comment]
Image datasets like ImageNet is a combination of grayscale (1 channel) and RGB (3 channel) images. Frameworks like caffe, have a preprocessing where grayscale is replicated to more channels if the model requires it that way.

**Comment by nadavrot** [comment]
Okay. Technically this is not a part of the compiler/runtime but we can add this feature to the testing infrastructure, if it's so commonly used. I suggest adding this feature to the model-runner. In any case, the input needs to be adjusted before being fed into the network.

**Comment by suyash-cadence** [comment]
Okay, I think the more appropriate place to add this in image-classifier. I am not sure why and how model-runner is correct place.

**Comment by nadavrot** [comment]
@suyash-cadence sorry, I typed the wrong thing. You are correct.

**Comment by suyash-cadence** [comment]
Input grayscale png images can be converted to 3 channel images. There is no real need to implement this as a feature.
