### ISSUE TITLE
Homebrew's `--with-toolchain` gives `Error: invalid option`

### ISSUE THREAD

**Issue by alannnna** [pytorch/glow#2389]
When running `brew install --with-toolchain llvm@7` as specified [in the README](https://github.com/pytorch/glow#macos), I got `Error: invalid option: --with-toolchain`. It worked after removing the flag and I was able to compile and run tests. This appears to be a bug in the README.

Mac version: 10.14.3
```
$ brew --version
Homebrew 2.0.1
Homebrew/homebrew-core (git revision fc73; last commit 2019-02-14)
```

**Comment by bertmaher** [comment]
Good catch! I think --with-toolchain is an old option from llvm 6.  Could you send a PR to remove it?

**Comment by alannnna** [comment]
PR is up! Thanks!
