### ISSUE TITLE
First time setup: `'string.h' file not found` when running `ninja all`

### ISSUE THREAD

**Issue by alannnna** [pytorch/glow#2391]
When I ran `ninja all` for the first time as specified in the readme, I got a few header errors, including: `'string.h' file not found`. (I don't have the full log anymore, unfortunately.)

This fixed the problem, but it appears to be a temporary solution: https://github.com/neovim/neovim/issues/9050#issuecomment-424417456

Should the readme be updated with the temporary solution?

Mac version: 10.14.3

**Comment by bertmaher** [comment]
Uf yeah, a few of us hit this a while back and should've added it to the README then.  I found this answer on stackoverflow (although it's less concise than the fix you found): https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by bertmaher** [comment]
@alannnna Do you want to create a PR with the header files workaround?

**Comment by alannnna** [comment]
@bertmaher Sure thing, will do!
