### ISSUE TITLE
Cross platform C-based timestamp generation in JIT (CPU) backend

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#2397]
We need to take a timestamp to support tracing the CPU backend. In #2375 we're using C++ chrono library time, which is cross platform but requires C++ symbols. It would be better to use a libc approach to getting timestamps, however:
* gettimeofday is inconistent (e.g. see https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time.html)
* clock_gettime isn't available of all platforms (only Linux and OSX >= 12.12)

Work out some reasonably portable solution here.

**Comment by nadavrot** [comment]
Why do we need to make cross-platform timestamps? Can we use 'cycles' as the measurement unit?

**Comment by nickgg** [comment]
I don't mean timestamps comparable cross platform. I mean a mechanism for getting timestamps which is a) sane, b) portable, and c) not C++. Harder than you'd think.

We prob don't want cycles here since we do want to be able to compare TraceEvents generated on different accelerator cards.

**Comment by nickgg** [comment]
hasn't caused any problems, can reopen if it does.
