### ISSUE TITLE
Is there a plan to support AI hardware accelaretor, as Example?

### ISSUE THREAD

**Issue by zhangfanghn** [pytorch/glow#2411]
I want to use glow on DSP or AI ASIC.
Is there a plan to support AI hardware accelaretor, as Example? I found that many chip vendors are partners of  glow, but  I do not find  AI ASIC example and any plans .

**Comment by rdzhabarov** [comment]
The challenge here is that actual ISA for the real ASICs are often times under NDA and cannot be exposed.

At some point there might be open source ISAs for real devices which we could use as an example here.
I do not think we can share any more details now, though.

**Comment by rdzhabarov** [comment]
I'm closing this now as there is no action could be done as of now.
