### ISSUE TITLE
[New operator] ElementwiseLinear

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2420]
The spec for the `ElementwiseLinear` operator from Caffe2 can be found here https://caffe2.ai/docs/operators-catalogue.html#elementwiselinear.

It should be possible to lower this operator to existing elementwise `Mul` and `Add` operations.

**Comment by rdzhabarov** [comment]
@jackm321 we could source those caffe2 op tasks to bootcampers.
Based on the recent @SplitInfinity experience those get picked up pretty quickly ;)

**Comment by jackm321** [comment]
@rdzhabarov that would amazing

**Comment by jackm321** [comment]
@SplitInfinity I only see one bootcamped task T40166373 in the tool have there been other tasks especially on the order of creating a new operator?

**Comment by SplitInfinity** [comment]
@jackm321 

No, but most of the task template should still be applicable!
