### ISSUE TITLE
bias is always created for convolution operator

### ISSUE THREAD

**Issue by QiJune** [pytorch/glow#2429]
It seems that bias is always created for convolution operator.

https://github.com/pytorch/glow/blob/fd7b735d93479c30592c0d7e44ab3f6be2283494/lib/Importer/ONNXModelLoader.cpp#L481-L494

It will waste some memory and PE cycles if we use a zero bias tensor. Actually bias is an optional input for convolution.

**Comment by jfix71** [comment]
Hi @QiJune -- for now if this is an issue for a backend, then you could use backend-specific IRGen to generate something like a backend-specific `ConvolutionNoBiasInstruction` from a `ConvolutionNode` that has a zero bias input. At the Node level we should keep a single version of `ConvolutionNode`. If the extra zero bias tensor is an issue for many backends then we could consider adding a general `ConvolutionNoBiasInstruction` in the future, but for now I don't think we want to go in that direction.

**Comment by QiJune** [comment]
@jfix71 Got it, Thanks!

**Comment by vuzelac-cadence** [comment]
Hi @jfix71 . I am trying to understand what it means that bias can be NULL, yet  `op.input_size() > 2`.
Is this condition requiring the presence of bias ?

**Comment by jfix71** [comment]
@vuzelac-cadence I'm not sure exactly what your question is. The Bias would not be null. I'm saying to keep the zero Bias tensor there if `op.input_size() <= 2`, and then if we want to get better performance then we would add a new `ConvolutionNoBiasInstruction` that has no Bias input at all.

**Comment by vuzelac-cadence** [comment]
Ah ok, let me clarify - the question asked here, and the answer are clear. Maybe I was supposed to open a new issue but I thought I'll just ask here since it's about the same code.
So, if op.input_size() <=

**Comment by vuzelac-cadence** [comment]
My mistake here, sorry about that. I thought thought I could ask an additional question here, since it's related, however, the question is about Caffe2 Importer (same logic as here, but no error is returned if bias name is not found). I'll have to open a new Issue.
