### ISSUE TITLE
Move the reusable parts of CPUBackend into a LLVMCodeGen library

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#2447]
As more Glow backends are being developed,  some of them need to directly generate code using LLVM for different targets and architectures. Thus it would be nice if it would be possible to reuse some of the `CPUBackend` functionalities (e.g. most of `LLVMIRGen`, bundle saving, may be JIT parts), but with certain backend-specific adjustments.

Glow's `CPUBackend` is not implemented as a reusable component though. For one, all of the implementation is hidden inside this backend's subdirectory and not visible by other backends. Then, in certain places this backend mixes a rather target independent code with x86/CPU-specific code.

It may be interesting to decouple the reusable parts of the `CPUBackend` into a reusable `LLVMCodeGen` library, so that concrete backends can derive from it and add any backend specific functionality and adjustments.

Other possible alternatives, which are less cleaner solutions IMHO:
- Extend the `CPUBackend` with additional logic required by the specific backend. This would essentially result in a situation where we have multiple backends under `lib/Backends/CPUBackend`.
- Copy most of the `CPUBackend` into your new backend subdirectory and adjust it to your liking, which would lead to a lot of code duplication between the new backend and the `CPUBackend`.

**Comment by opti-mix** [comment]
Since this re-factoring may change some of the `CPUBackend` internal APIs and its implementation, it would be nice to know if there is anyone who would be affected by such a change.  Please comment on this issue and let others know what do you think about the proposed refactoring and if you have any concerns about it.

**Comment by opti-mix** [comment]
@tlepley-cadence @aturetsk IIRC, your backends may be based on Glow's CPUBackend. It would be nice to hear your feedback regarding this issue and the related PR #2461. Thanks!

**Comment by aturetsk** [comment]
@opti-mix, Thanks for pointing the PR out, I'll have a look.

**Comment by aturetsk** [comment]
I think this is a step into the right direction and it should resolve some build inconveniences we have in our backend due to the fact that it's based on CPUBackend.
I don't expect any big issues with us transitioning from CPUBackend to LLVMBackend base. In case of any, we'll submit PRs.
Thanks for doing this!

**Comment by nadavrot** [comment]
@opti-mix What is the status of this issue?

**Comment by nickgg** [comment]
@opti-mix feel free to reopen.

**Comment by tlepley-cadence** [comment]
For information, we could rebase our backend on top of  #2461. We've got no particular issue.

**Comment by opti-mix** [comment]
@tlepley-cadence 

> For information, we could rebase our backend on top of #2461. We've got no particular issue.

Awesome! Thanks for the confirmation.
