### ISSUE TITLE
[DeviceManager] Should DeviceManagerTest check network outputs as well?

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/glow#2471]
While working on another implementation of `DeviceManager`, I had a bug in my device manager (more specifically, in my implementation's override of `CompiledFunction::execute`) that `DeviceManagerTest` did not catch because it does not check the output of the networks it runs. `DeviceManagerTest` was all green but my backend integration tests that use an `ExecutionEngine` were all red.

Should DeviceManagerTest check network outputs as well?

**Comment by SplitInfinity** [comment]
cc: @gcatron @nickgg

**Comment by gcatron** [comment]
I think we should have a case. I think even a simple network that just squares the inputs would help catch a lot of bugs.

**Comment by nickgg** [comment]
Sounds good to me.
