### ISSUE TITLE
[Runtime] Runtime should maintain output tensors

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2496]
@gcatron and I observed that currently onnxifi output tensors have to be allocated by glow and then the final results copied into the onnxifi outputs because Glow is overwriting the output tensors in the Context handed to the glow runtime. This should be fixed to avoid unnecessary copies of the output at the last step (and maybe more copies are happening internally as well).

**Comment by nadavrot** [comment]
@jackm321 What is the status of this issue? Is this fixed?

**Comment by jackm321** [comment]
@nadavrot This issue has not been fixed but it should be thought about with the other runtime tensor optimizations that are being considered such as using device-mapped pools of tensors. For example if the last Glow tensor to hold a result is a device-mapped tensor and that can be propagated to the onnxifi layer then this copy won't need to be eliminated.

**Comment by nadavrot** [comment]
1. onnxifi is only one of the users of the RT library. We should design the runtime (or test the runtime) just for this single users. 

2. "Glow is overwriting the output tensors in the Context handed to the glow runtime". -> Why is this happening? We should be passing to the runtime a context that contains pointers to Tensors. The tensors are pre-allocated and the runtime just reads and writes from the content of the tensors. It should not allocate new tensors or do anything other than drive the execution of the network. Are we allocating new tensors in the runtime?

**Comment by jackm321** [comment]
Fixed by #2884
