### ISSUE TITLE
ExecutionEngine.runBatch fails with weird error when it's run on a network compiled with Infer mode

### ISSUE THREAD

**Issue by rdzhabarov** [pytorch/glow#250]
Reproduce: Compile with asan and execute runBatch on network compiled with Infer mode.

We should check how NN was originally compiled and throw an appropriate exception in case of incompatibility.

Upd: Make an assert instead of throwing an exception.

**Comment by nadavrot** [comment]
@rdzhabarov I spent some time refactoring runBatch, and it now has a different implementation. I did not run into problems. It been 9mo since this issue has been filed. I'll close it unless there is anything actionable that you suggest we do.
