### ISSUE TITLE
[ModelZoo] support emotions_ferplus model

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#2504]
Add support for the FER+ Emotion Recognition model in glow (https://github.com/onnx/models/tree/master/emotion_ferplus) and verify via a runnable example we can include in the ModelZoo regression test.

The image format for this model is 64x64 0to1.

This issue blocks #2500.

**Comment by arunm-git** [comment]
@nickgg : is the image format really 0to1?
Looking at https://github.com/onnx/models/tree/master/emotion_ferplus#preprocessing, it seems like 0to255, right? At least, when I run that preprocessing on a bunch of images, I get values that appear to lie within 0 to 255.

**Comment by nickgg** [comment]
Looks like it's not, sorry!
