### ISSUE TITLE
Need to output correct shape for C2 FC op

### ISSUE THREAD

**Issue by yinghai** [pytorch/glow#2522]
Today, if the input X or W for FC op has dim higher than 2, they will be flattened into 2D along `axis` or `axis_w`:
https://github.com/pytorch/glow/blob/143f862e7c5bd19b050c5865f3b465c7e5986185/lib/Importer/Caffe2ModelLoader.cpp#L569

And output will be 2D. This creates semantic difference between Glow and C2 ops, because c2's output shape will have the same dim size as input. The consequence is that if we have ` FC -> Transpose` sequence, with FC having 4D input and Transpose having 4D perms arguement, you will meet with a segfault, as Transpose is trying to access 4D dim of the input. 

The solution should be adding a `Reshape` node after FullyConnect layer when importing C2 FC op and when its input is more than 2D. The spec of the Reshape can be computed using:
https://github.com/pytorch/pytorch/blob/c10662962c5ea7da9762be65eacafee376d9c13c/caffe2/operators/fc_inference.cc#L4-L33

**Comment by jackm321** [comment]
@yinghai the c2 [operator docs](https://caffe2.ai/docs/operators-catalogue.html#fc ) seem to indicate that the output should be 2D and I ran this small example and the output also looks 2D. Where do you see >2D outputs of a c2 FC (or what should I change about this example)?

``` python
from caffe2.python import workspace, model_helper

m = model_helper.ModelHelper(name="net")

data = m.param_init_net.XavierFill([], 'data', shape=[5, 2, 2, 2])
weight = m.param_init_net.XavierFill([], 'fc_w', shape=[3, 8])
bias = m.param_init_net.ConstantFill([], 'fc_b', shape=[3])

fc = m.net.FC(["data", "fc_w", "fc_b"], "fc_output")

workspace.RunNetOnce(m.param_init_net)
workspace.RunNetOnce(m.net)

print "input shape", workspace.FetchBlob("data").shape
print "weight shape", workspace.FetchBlob("fc_w").shape
print "output shape", workspace.FetchBlob("fc_output").shape

# output:
# input shape (5, 2, 2, 2)
# weight shape (3, 8)
# output shape (5, 3)
```
