### ISSUE TITLE
Remove LLVM6 support from Glow

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#2560]
LLVM 7 is the latest LLVM version and LLVM 8 is not too far away. This we should drop any LLVM 6 support to simplify the code.

Specifically, we need to do the following:
- Adjust CMake files to use LLVM >=7 by default and bail if LLVM < 7 is used
- Remove any conditionally compiled LLVM 6-specific code inside #ifdefs

**Comment by opti-mix** [comment]
Comment from a user: "Ubuntu 18.04 LTS provides LLVM 6.0 packages, which might be a motivation to keep supporting this version until the next Ubuntu LTS. At least we currently plan to do so in pocl"

**Comment by mortzur** [comment]
Hi!
I want to start looking into this. I'm ramping up so I'm just getting to know the project.
Anyone else was looking into this? Is this OK that I move on?
I see above the comment from a user, please tell me if there are other issues like this that should be considered.

**Comment by nickgg** [comment]
@mortzur go for it!

**Comment by tlepley-cadence** [comment]
I checked and we are fine with this deprecation (we already use LLVM 7 under both Linux and Windows). Please note that the more Glow will be used in products released to customers, the more problematic/controversial such deprecation will be.
