### ISSUE TITLE
Visual Studio /fp:fast behavior, and unit tests failures

### ISSUE THREAD

**Issue by ayermolo** [pytorch/glow#2574]
I am observing failures in release mode(fail) vs debug mode(pass) on Windows with VS2017. Tensor.equalNAN
OperatorTest.RowwiseQuantizedSparseLengthsWeightedSum

Looking at RowwiseQuantizedSparseLengthsWeightedSum seems like there is slight discrepancy that creeps in during channel wise quantization when Node is created.

Removing /fp:fast from release build in GlowDefaults.cmake fixes both tests.

Any thoughts on this?

**Comment by bertmaher** [comment]
I'm not familiar with VS but for Tensor.equalNAN I had to disable -ffinite-math-only for clang/gcc (since it allows the compiler to assume NAN/Inf does not happen).  Is there something similar for VS?  If not we should probably remove /fp:fast

**Comment by ayermolo** [comment]
Microsoft has this to say: 

> Special values (NaN, +infinity, -infinity, -0.0) may not be propagated or behave strictly according to the IEEE-754 standard.

> Special values (NaN, +infinity, -infinity, -0.0) may not be propagated or behave strictly according to the IEEE-754 standard.

Looking deeper in to equalNAN comparison with NAN. Comment in isEqualImpl mentions that comparison with NAN supposed to always return false, so to me it looks like with /fp:fast this is no longer the case.

This confirms it: 
https://developercommunity.visualstudio.com/content/problem/325931/suggestion-to-help-catch-nan-comparison-errors-wit.html

To me it seems like safe thing to do is disable /fp:fast.

**Comment by ayermolo** [comment]
@bertmaher I would like to just remove it from windows config. Any objections?

**Comment by bertmaher** [comment]
Yep, that's fine by me.
