### ISSUE TITLE
[quantization] Quantized resnext results differ on Interpreter and CPU backends

### ISSUE THREAD

**Issue by artemrakhov** [pytorch/glow#2581]
This is what I see on Interpreter backend:
```
Model: /home/artem/glow/release_build/resnext_int8/predict_net.pbtxt
 File: tests/images/imagenet/cat_285.png	Label-K1: 281 (probability: 0.5911)
 File: tests/images/imagenet/dog_207.png	Label-K1: 207 (probability: 0.8373)
 File: tests/images/imagenet/zebra_340.png	Label-K1: 340 (probability: 0.9986)
```
On CPU backend:
```
Model: /home/artem/glow/release_build/resnext_int8/predict_net.pbtxt
 File: tests/images/imagenet/cat_285.png	Label-K1: 281 (probability: 0.7793)
 File: tests/images/imagenet/dog_207.png	Label-K1: 207 (probability: 0.9691)
 File: tests/images/imagenet/zebra_340.png	Label-K1: 340 (probability: 0.9996)
```
Although labels are correct, probabilities are very different, which needs to be investigated.

**Comment by jfix71** [comment]
I saw something similar a while back when looking at quantized Resnet50: https://github.com/pytorch/glow/issues/1837#issuecomment-429091696

The cause here for quantized Resnext could be something different, but at the time for quantized Resnet50 I assumed this was likely due to differences in quantization implementation. A good place to start would be to compare the first Conv on each backend. We should also run top-k on both backends to compare.

**Comment by artemrakhov** [comment]
I debugged this and found that the difference is indeed in the fist quantized Convolution layer. We have very different Rescaling formulas, for converting accumulated int32 to int8 _(stored and passed further)_

1. Interpreter simply does: `round(int32 * fp)`
https://github.com/pytorch/glow/blob/0f61083a78ec49ee6389958613ffafe86290cf76/lib/Backends/Interpreter/InterpreterNodes.cpp#L242

2. CPU does: `((int32 >> preShift) * uint8) >> postShift`
https://github.com/pytorch/glow/blob/2a8f613aaa642e9cb6c03b10b1c2d56a85bd85ef/lib/Quantization/Base/Base.cpp#L197

3. Caffe2 does: `roundingShift(int32 * int, shift)`
https://github.com/pytorch/FBGEMM/blob/23aa5a35ece04fe31600cce31712214a133166ec/src/QuantUtils.cc#L101

In general, we cannot rely on quantization algorithms being the same. We should realize that some error will always be present and it can accumulate quickly for large nets. 

This particular net gets better results when using `-use-imagenet-normalization` flag:
```
$ resnext_int8/run.sh -use-imagenet-normalization
Model: /home/artem/glow/release/resnext_int8/predict_net.pbtxt
 File: tests/images/imagenet/cat_285.png	Label-K1: 281 (probability: 0.7759)
 File: tests/images/imagenet/dog_207.png	Label-K1: 207 (probability: 0.9341)
 File: tests/images/imagenet/zebra_340.png	Label-K1: 340 (probability: 0.9987)
$ resnext_int8/run.sh -use-imagenet-normalization -cpu
Model: /home/artem/glow/release/resnext_int8/predict_net.pbtxt
 File: tests/images/imagenet/cat_285.png	Label-K1: 281 (probability: 0.7785)
 File: tests/images/imagenet/dog_207.png	Label-K1: 207 (probability: 0.9704)
 File: tests/images/imagenet/zebra_340.png	Label-K1: 340 (probability: 0.9995)
```
Apparently quantized models are less stable, and it's more important to normalize input to the right range.
