### ISSUE TITLE
Check for quantization profile before trying to open it

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2586]
Glow currently crashes if it tries to open a quantization profile file if it doesn't exist (usually because the imported graph is slightly different due to op support problems than the one the one that was saved).

**Comment by rdzhabarov** [comment]
Can you explain the problem in more details?

ONNXIFI graphs (patches in the original original C2 graph) for profiling and loading should be exactly the same graphs. Also, profiling will always use either CPU or Interpreter backend whereas loading should be done with the specific backend for inference.

**Comment by jackm321** [comment]
This line will crash if the quantization profile isn't found. Instead of crashing, code should probably check for the file's existence and if doesn't exist return a ONNXIFI_STATUS_INTERNAL_ERROR (or some other error if there is a more appropriate one)

https://github.com/pytorch/glow/blob/2d7f0f3c674f5e882b8b6544173cf40c22994136/lib/Onnxifi/InlineOnnxifi.cpp#L72
