### ISSUE TITLE
error compiling clang: error: unknown argument: '-wd654'

### ISSUE THREAD

**Issue by stellaywu** [pytorch/glow#2624]
Follow the instruction to compile glow, tried  on both osx Sierra and ubuntu 16.04 , both report error clang: error: unknown argument: '-wd654'.

Below is the errorlog

> int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

> Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/ubuntu/glow/CMakeFiles/CMakeTmp

> Run Build Command:"/usr/bin/ninja" "cmTC_6b8fd"
[1/2] Building C object CMakeFiles/cmTC_6b8fd.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_6b8fd
FAILED: : && /usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create   CMakeFiles/cmTC_6b8fd.dir/CheckFunctionExists.c.o  -o cmTC_6b8fd  -rdynamic -lpthreads && :
/usr/bin/ld: cannot find -lpthreads
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

> Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WD654 failed with the following output:
Change Dir: /home/ubuntu/glow/CMakeFiles/CMakeTmp

> Run Build Command:"/usr/bin/ninja" "cmTC_c5cac"
[1/2] Building CXX object CMakeFiles/cmTC_c5cac.dir/src.cxx.o
FAILED: /usr/bin/c++     -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing -DHAVE_CXX_FLAG_WD654  -wd654 -fPIE   -wd654 -o CMakeFiles/cmTC_c5cac.dir/src.cxx.o -c src.cxx
clang: error: unknown argument: '-wd654'
clang: error: unknown argument: '-wd654'
ninja: build stopped: subcommand failed.

Thanks!!

**Comment by rdzhabarov** [comment]
Interesting. Can you please paste how exactly you generate Ninja files.

**Comment by stellaywu** [comment]
Thank you for the reply. 
On osx I followed the instruction for osx as the following

`submodule update --init --recursive  ` 
`brew install cmake graphviz libpng ninja protobuf wget`
`brew install llvm@7`
`ln -s "/usr/local/opt/llvm/bin/clang-format" "/usr/local/bin/clang-format"`
`ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"`
`mkdir build_Debug `
`cmake -G Ninja ../glow -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@7`

c++ version 

> Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by rdzhabarov** [comment]
ok, so you have failure before actual building.

```cmake -G Ninja ../glow -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@7```

Can you dump the whole output?

**Comment by stellaywu** [comment]
The whole output is the following:
> -- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Tests not explicitly enabled/disabled, default to enable
-- Performing Test HAS_W_NO_PSABI
-- Performing Test HAS_W_NO_PSABI - Failed
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.36") 
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2") 
-- Found LLVM 7.0.1
-- Using LLVMConfig.cmake in: /usr/local/opt/llvm@7/lib/cmake/llvm
Adding CMakeFiles backend.
CMake Error at lib/Backends/CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /Users/stella/glow/lib/Backends/CMakeFiles

  does not contain a CMakeLists.txt file.


> Adding CPU backend.
Adding Interpreter backend.
Adding OpenCL backend.
-- Found Protobuf: /anaconda2/envs/torch/lib/libprotobuf.dylib (found version "3.7.0") 
-- 
-- ******** Summary ********
--   CMake version         : 3.13.4
--   CMake command         : /usr/local/Cellar/cmake/3.13.4/bin/cmake
--   System                : Darwin
--   C++ compiler          : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   C++ compiler version  : 10.0.0.10001145
--   CXX flags             :  -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti -Wnon-virtual-dtor
--   Build type            : Debug
--   Compile definitions   : WITH_PNG;GLOW_WITH_LLVMIRCODEGEN=1;GLOW_WITH_CPU=1;GLOW_WITH_OPENCL=1;GOOGLE_PROTOBUF_NO_RTTI;ONNX_NAMESPACE=glow_onnx
--   CMAKE_PREFIX_PATH     : /usr/local/opt/llvm@7
--   CMAKE_INSTALL_PREFIX  : /usr/local
--   CMAKE_MODULE_PATH     : /Users/stella/glow/cmake/modules
-- 
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : glow_onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : /anaconda2/envs/torch/bin/protoc
--   Protobuf includes     : /anaconda2/envs/torch/include
--   Protobuf libraries    : /anaconda2/envs/torch/lib/libprotobuf.dylib
--   BUILD_ONNX_PYTHON     : OFF
-- LLVM FileCheck Found: /usr/local/opt/llvm@7/bin/FileCheck
-- Found Git: /usr/bin/git (found version "2.17.2 (Apple Git-113)") 
-- git Version: v1.4.0-fae87266
-- Version: 1.4.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Success
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found Threads: TRUE  
-- Found PythonInterp: /anaconda2/envs/torch/bin/python (found version "3.6.8") 
Skipping adding test en2gr_cpu_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
Skipping adding test en2gr_quantization_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
Skipping adding test resnet_runtime_test because it requires a models directory. Configure with -DGLOW_MODELS_DIR.
-- Configuring incomplete, errors occurred!

**Comment by rdzhabarov** [comment]
> The source directory /Users/stella/glow/lib/Backends/CMakeFiles does not contain a CMakeLists.txt file.

Why do you have CMakeFiles dir in /Users/stella/glow/lib/Backends/? it's not supposed to be there.

Can you
```
ls  /Users/stella/glow/lib/Backends/ 
```

You should only have folders which are in glow master or dir with your custom backend in addition, if you have your custom backend you should have `CMakeLists.txt` there.

**Comment by stellaywu** [comment]
The issue was resolved! It was a mistake, I build it within the source directory that's why the lib directory was messed up. Thanks for pointing me to the right direction!

**Comment by venkatacrc** [comment]
@stellaywu @rdzhabarov What is the actual fix for this error. I am hitting this error today.

**Comment by venkatacrc** [comment]
Adding -DLLVM_DIR=/usr/lib/llvm-8/cmake helped to resolve this error for me on Ubuntu 18.04.
`$cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/lib/llvm-8/cmake`

**Comment by weimin** [comment]
Hi,
I tried on ubuntu 18.04 but I am seeing the '-wd654' issue again, I installed it into separate directories and also 
[CMakeError.log](https://github.com/pytorch/glow/files/5699330/CMakeError.log)
[CMakeOutput.log](https://github.com/pytorch/glow/files/5699332/CMakeOutput.log)
[output.txt](https://github.com/pytorch/glow/files/5699314/output.txt)
