### ISSUE TITLE
handle.dump() segfault 

### ISSUE THREAD

**Issue by pshung** [pytorch/glow#2628]
```c++
int main() {
  PseudoRNG PRNG;

  Tensor input(ElemKind::FloatTy, {1, 3});
  auto I = input.getHandle<float>();
  I.at({0, 2}) = 1;
  I.dump();
  return 0;
}

```
message:
```bash
shape: ( 1 3 )
max: Segmentation fault (core dumped)
```

My configuration:
CXX=clang++ CC=clang cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DGLOW_WITH_CPU=1 -DGLOW_WITH_OPENCL=0 -DGLOW_BUILD_EXAMPLES=1  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  ../glow -DGLOW_MODELS_DIR=models -DCMAKE_CXX_FLAGS="-O0 -g3 --save-temps" -DGLOW_BUILD_TESTS=1

My clang version is 7.0.1

Workaround solution: build glow with GNU toolchain.

**Comment by nadavrot** [comment]
@beicy Do you mind taking a look?

**Comment by beicy** [comment]
> @beicy Do you mind taking a look?

Sure!

**Comment by rdzhabarov** [comment]
@pshung can you run under lldb/gdb and `bt` after it crashes and post it here.

**Comment by pshung** [comment]
upgrade clang to 8.0!
