### ISSUE TITLE
Supporting out-of-process compilation for LLVMBackend-based backends

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#2636]
Some users have reported about situations where they cannot use LLVM in-processs as a library to compile LLVM bitcode for their respective targets. It may happen e.g. if they work on a new HW and LLVM support for this target is either provided as a closed-source by 3rd party companies or they use customized versions of LLVM which are not 100% compatible with the version used to build Glow.

To overcome these troubles, these users asked if it would be possible to support out-of-process compilations for LLVMBackend-based backends. In these scenarios, Glow would still produce the LLVM bitcode as usual, but then it would invoke an external LLVM compiler (`llc`?) to compile this bitcode into an object file.

To support such a feature, we'd need to slightly extend the LLVMBackend in Glow. We'd need to add options to specify the external compiler to use and may be the flags to pass to this compiler. 

It seems we don't need to support the JIT functionality for such cases as they are usually performing a cross-compilation.

**Comment by geoffberry** [comment]
Have you explored the possibility of having more than one version of LLVM loaded in-process?  For example, BackendX could link with a different version of LLVM than the CPU backend.  It seems like this would work as long as the Backend-specific LLVM symbols weren't exported by the Backend library, though there may be issues with things like LLVM command-line options.

**Comment by opti-mix** [comment]
@geoffberry 

> Have you explored the possibility of having more than one version of LLVM loaded in-process?

No, we haven't explored this possibility yet. If you are interested in this feature, please file an issue and describe the use-case.
