### ISSUE TITLE
Unsupported Cast Operator in ONNXModelLoader::loadOperator

### ISSUE THREAD

**Issue by srinivas491-oneconvergence** [pytorch/glow#2640]
Trying to use glow to emit bundle for image classifier using resnet50 model, which is converted from tf to onnx. 

Steps followed for conversion:
1. Freeze the graph - sample.pb
2. Convert tf graph to onnx using  [tf2onnx.convert](https://github.com/onnx/tensorflow-onnx)

When I used the converted model with the glow to generated a bundle using the following command
./bin/image-classifier tests/images/imagenet/cat_285.png -image-mode=0to1 -m=resnet50/tf2onnx.onnx -model-input-name=gpu_0/data_0 -cpu -emit-bundle /tmp -dump-graph-DAG=/tmp/resnet50.dot -network-name=static_version -relocation-model=pic

I'm getting an error saying, 
Encountered an error, exiting.
file: /root/srinivas/Glow_Repo/Glow_Code/glow/lib/Importer/ONNXModelLoader.cpp line: 896 error code: MODEL_LOADER_UNSUPPORTED_OPERATOR message: Failed to load operator.

When I tried to debug the error, it is cast operator is causing an issue.

**Comment by jfix71** [comment]
Hi @srinivas491-oneconvergence, can you provide us with the proto containing the operator that isn't supported? Or more details on the cast that is causing the problem?

**Comment by nickgg** [comment]
As an aside, do you need to convert from TF? Can you use the resnet50 model from the Caffe2 Model Zoo?

**Comment by srinivas491-oneconvergence** [comment]
@nickgg, I'm trying to use the glow for the TF models by converting them to ONNX instead of going through Caffe2 Model for the custom hardware.

**Comment by tlepley-cadence** [comment]
We've got the same problem too. There is a discussion ongoing with tf2onnx people (https://github.com/onnx/tensorflow-onnx/issues/322) because in many situations, Cast could be optimized out by tf2onnx. But since Cast is anyway a valid ONNX operator it's IMO relevant to support it in Glow. We added a partial support of Cast in our private Glow repo. I am planning to upstream it in a near future.

**Comment by srinivas491-oneconvergence** [comment]
@jfix71 
Just an overview of the cast operation in the graph. 

![Screen Shot 2019-04-02 at 3 28 30 PM](https://user-images.githubusercontent.com/36420677/55440497-aaa80100-555c-11e9-8e09-0a93471f7da5.png)

**Comment by srinivas491-oneconvergence** [comment]
@tlepley-cadence 

By any chance, is there a way for you share your private repo which has partial support for Cast operator?  Since I need this operator support to continue my training and inference of tf models. 

It would be great if you share that.

**Comment by tlepley-cadence** [comment]
@srinivas491-oneconvergence I can't share the private repo, but I've just created a WIP PR here: #2655

I still need to write few tests before this PR can land, but at least, you can make a try with the branch of this PR. I'll certainly find the time to complete the PR with tests tomorrow.

**Comment by tlepley-cadence** [comment]
@srinivas491-oneconvergence in your graph, it's not clear to me what the `Cast` operation takes as input. It is supposed to have an input tensor, and it's not clear on your graph. Also, there is no type information (what is the source and destination type of the cast ?)
