### ISSUE TITLE
Unhelpful error message: file: ../../lib/Importer/Caffe2ModelLoader.cpp line: 175 message: Can't find the model or network files.

### ISSUE THREAD

**Issue by bertmaher** [pytorch/glow#2647]
Would be nice to print what model/network it is looking for.  Also, are "model" and "network" different things here?  Could we pick one word or the other?

**Comment by nadavrot** [comment]
Related to #2627. (I think)

**Comment by bertmaher** [comment]
Yep!  I just thought it'd be good to document some of the places where our error reporting needs love :-)

**Comment by rdzhabarov** [comment]
@ZchiPitt should be easy and useful for future debugging.

**Comment by SameerAsal** [comment]
Hi @bertmaher 

the  line number you are pointing to seems to be different now (it is not really printing anything). 

Can you please update this issue?

**Comment by SameerAsal** [comment]
I think it is 247 maybe?

**Comment by bertmaher** [comment]
I think it's in these places (both the C2 and ONNX importers do it):
https://github.com/pytorch/glow/search?q=%22can%27t+find+the+model%22&unscoped_q=%22can%27t+find+the+model%22
