### ISSUE TITLE
Currently calling lower twice during profiling/quantization

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#2648]
Right now we call `lower()` twice when doing profiling or quantization. E.g. for the Loader, we're calling `lower()` once prior to profiling or quantization inside `Loader::compile()`, and then again inside `Backend::optimizeFunction()`. We really only need to call `lower()` once.

One simple solution here is to add a new option to `CompilationOptions` for `skipLowering`, set when we know we've already called `lower()` prior to calling `compile()`.

Another more involved solution would be to move `quantizeFunction()`/`profileQuantization()` calls directly into `Backend::optimizeFunction()`, so that it could be done after `lower()`. This would require passing a lot of info through the `ExecutionEngine::compile()`, e.g. `quantizationInfos`, `quantizationSchema`, `bindings`, etc. (could be added to `CompilationOptions`).

**Comment by nickgg** [comment]
it's a nit, but if you go with the first solution it's cleaner to have a `lower` option which defaults true rather than a `skipLowering` which defaults false.

**Comment by jfix71** [comment]
Note that https://github.com/pytorch/glow/pull/2613/ currently implement `fold()` inside `optimizeFunction()`. If it stays there then the first solution above wouldn't work well, because the graph would be optimized and lowered before being folded, which may end up undoing lowering we want to perform, and also may make pattern matching inside folding more difficult.

One other option there is to move `fold()` to the end of importing (e.g. at the end of the `ONNXModelLoader`/`Caffe2ModelLoader`). This means we would be sure that no graph transformations have occurred prior to folding, which I think might make the most sense.

**Comment by tlepley-cadence** [comment]
> One simple solution here is to add a new option to `CompilationOptions` for `skipLowering`, set when we know we've already called `lower()` prior to calling `compile()`.

I don't think this solution will work: the 2 calls to `lower()` serve different purposes and may do different things. The only purpose of the first lower is to control at which granularity the profiling is done. During the first lowering, the lowering for some operations may be disabled with the command line option `do-not-lower-nodes-for-profiling` (useful if the target backend is different from the backend that performs the profiling). Then, we still need to call `lower()` a second time to make sure the IR is compliant to what expects the backend that will perform the profiling.

**Comment by jfix71** [comment]
Fixed via #2700
