### ISSUE TITLE
std::bad_function_call when using HostManager

### ISSUE THREAD

**Issue by bertmaher** [pytorch/glow#2681]
I think https://github.com/pytorch/glow/blob/master/lib/Runtime/HostManager/HostManager.cpp#L157 is guaranteed to cause a std::bad_function_call if evictNetwork actually tries to invoke the callback.  If we don't care about the result of eviction, we should explicitly add a do-nothing callback.

**Comment by nickgg** [comment]
We can make the default ‘[](){}’ and that should take care of this case.
