### ISSUE TITLE
Profile quantization consumes too much memory

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#2697]
The problem of scalability of quantization profile generation is addressed by: #2684 (minibatch)

Nevertheless, at equal batch size, performing quantization profile generation increases a lot the memory requirement, compared to standard float inference. This is a problem I discussed with @opti-mix at the Glow workshop. For instance for a model we tested, it increases from 8GB to 50GB. 

The insertion of QuantizeProfile nodes prevent the merging of elementwise nodes and QuantizeProfile need extra tensors (histogram), but the memory increase should not be as huge.

It turns out that the IR instruction scheduling (`sinkAllocas` ?) that targets reducing the live-range overlap of tensors doesn't work properly with `QuantizationProfile` nodes. When we dump the low-level Glow ir, we can see that `QuantizedProfile` nodes are all scheduled at the end. It has for effect to keep tensors of the model alive almost during the full model execution.

I didn't investigate further yet. Is it a side effect of the in-out param of `QuantizeProfile` nodes, what may disturb the memory optimization (in-out param are alive permanently) ?

**Comment by opti-mix** [comment]
@tlepley-cadence Thanks for reminding about this issue!

**Comment by nadavrot** [comment]
Great analysis @tlepley-cadence !

**Comment by opti-mix** [comment]
@tlepley-cadence Could you try #2698 on your models to check if it solves the issue? Thanks!

**Comment by opti-mix** [comment]
@tlepley-cadence BTW, the PR contains two different approaches to try out. One changes the scheduler and another one changes the IR optimizer. You can easily comment out the invocation of either one to check which ones works better for you.

**Comment by tlepley-cadence** [comment]
As I commented in  #2698, in the experiment I did, both solution give the same (very good) results in term of memory requirement. My preference would be to have a generic optimization pass (not `QuantizationProfile` specific), but it can maybe be done in a second step.

**Comment by opti-mix** [comment]
> My preference would be to have a generic optimization pass (not QuantizationProfile specific), but it can maybe be done in a second step.

@tlepley-cadence Please have a look at the 3rd implementation alternative I pushed and give it a try.
