### ISSUE TITLE
Link Glow executables and tests using LLVM's LLD linker if it is available to speed up builds

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#2741]
LLD is much faster than e.g. GNU ld, in particular on Linux systems. We should try to use it if it is available.

**Comment by opti-mix** [comment]
@compnerd Do you have any idea what would be the easier way to achieve this?

**Comment by compnerd** [comment]
Adding `-fuse-ld=lld` to the `CMAKE_EXE_LINKER_FLAGS` and `CMAKE_SHARED_LINKER_FLAGS` should be sufficient.  This will only work with `clang` unfortunately (since `gcc` hardcodes the supported linkers in the source could and does not accept `lld`, and cl does not allow you to control the linker).

**Comment by opti-mix** [comment]
Fixed by #2744
