### ISSUE TITLE
[Runtime efficiency] Don't use Placeholder names as ids in the runtime

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2775]
After perf profiling, we identified hashing string names for placeholders as a big cost in the runtime during placeholder propagation. Avoid this by using integer ids or preferably Placeholder* in the runtime to uniquely identify placeholders instead for much faster map lookups.

**Comment by opti-mix** [comment]
> After perf profiling, we identified hashing string names for placeholders as a big cost in the runtime during placeholder propagation. Avoid this by using integer ids or preferably Placeholder* in the runtime to uniquely identify placeholders instead for much faster map lookups.

BTW, an alternative could be to store a combination of string and its hash to avoid re-computing hashes. IIRC, this is what Java does.

**Comment by jackm321** [comment]
@opti-mix I think since we have pointers with well-scoped lifespans in this case it might be easier to use those but that's an interesting idea

**Comment by rdzhabarov** [comment]
That's already fixed.
