### ISSUE TITLE
[Runtime efficiency] Don't copy intermediate tensors for DAGNodes with only one child

### ISSUE THREAD

**Issue by jackm321** [pytorch/glow#2776]
We have seen from perf profiling that propagating placeholder in the exeuctor is expensive in large part because of copying tensors from one DAGNode to another. One way to reduce the number of copies that occur is to only copy backing tensors for Placeholders that have multiple children and for DAGNodes with a single child just hand over ownership to that child node.

**Comment by rdzhabarov** [comment]
This is fixed.
