### ISSUE TITLE
HabanaBackendTest fails due to attemt to unload active topology

### ISSUE THREAD

**Issue by sergeigofman** [pytorch/glow#2782]
When running HabanaBackendTest, it fails after the last test:
Unable to unload function main.
Encountered an error, exiting.
Habana log indicates that there was an attempt to unload active topology: 
[2019-04-24 09:02:20.057] [SYN_API] [trace] unloadTopology
[2019-04-24 09:02:20.057] [SYN_API] [trace] _getDeviceIndex
[2019-04-24 09:02:20.057] [SYN_API] [error] _unloadTopology: deleting active topologyId 2 is not allowed

**Comment by rdzhabarov** [comment]
@sergeigofman how do I reproduce that?

Running with 1.7.1 all works as expected? (at least from the high level).
Are those errors when full Habana logs enabled? Is it observable via other means?

**Comment by sergeigofman** [comment]
For me, it reproduces by merely running HabanaBackendTest.
On 0.1.7.1 I haven't observed this behavior but I might be wrong.

**Comment by bertmaher** [comment]
Repro'ed this locally, working on a fix.

**Comment by bertmaher** [comment]
Finally fixed this, in #2920.  HabanaBackendTest should be clean now.
