### ISSUE TITLE
The operator test fails randomly on OpenCL

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#2806]
[       OK ] OperatorTest/OperatorTest.ConvertFromFloatToFloat/1 (1 ms)
[ RUN      ] OperatorTest/OperatorTest.ConvertFromFloatToFloat/2
[       OK ] OperatorTest/OperatorTest.ConvertFromFloatToFloat/2 (1 ms)
[----------] 594 tests from OperatorTest/OperatorTest (14476 ms total)

[----------] Global test environment tear-down
[==========] 681 tests from 2 test cases ran. (16421 ms total)
[  PASSED  ] 681 tests.
*** Error in `./tests/OperatorTest': double free or corruption (!prev): 0x00000000058085f0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f40dc5947e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f40dc59d37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f40dc5a153c]
/lib/x86_64-linux-gnu/libc.so.6(+0x39ff8)[0x7f40dc556ff8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3a045)[0x7f40dc557045]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0x7f40dc53d837]
./tests/OperatorTest[0x4c2da9]
======= Memory map: ========
00400000-0359a000 r-xp 00000000 08:01 2762728                            /var/lib/jenkins/workspace/build/tests/OperatorTest
03799000-03ba8000 r--p 03199000 08:01 2762728                            /var/lib/jenkins/workspace/build/tests/OperatorTest
03ba8000-03bad000 rw-p 035a8000 08:01 2762728                            /var/lib/jenkins/workspace/build/tests/OperatorTest
03bad000-03c0e000 rw-p 00000000 00:00 0 
05750000-05d24000 rw-p 00000000 00:00 0                                  [heap]
7f4034000000-7f4034556000 rw-p 00000000 00:00 0 
7f4034556000-7f4038000000 ---p 00000000 00:00 0 
7f407c000000-7f407e002000 rw-p 00000000 00:00 0 
7f407e002000-7f4080000000 ---p 00000000 00:00 0 
7f4080000000-7f408102f000 rw-p 00000000 00:00 0 
7f408102f000-7f4084000000 ---p 00000000 00:00 0 
7f4084000000-7f4086002000 rw-p 00000000 00:00 0 
7f4086002000-7f4088000000 ---p 00000000 00:00 0 
7f40885f8000-7f40885f9000 r-xp 00000000 08:01 2763485                    /var/lib/jenkins/.cache/pocl/kcache/IJ/AGLIFOIDLPINBLBEKAGOFHCGMFIPLIIGGNFID/dequantizeW/4-1-1/dequantizeW.so
7f40885f9000-7f40887f8000 ---p 00001000 08:01 2763485                    /var/lib/jenkins/.cache/pocl/kcache/IJ/AGLIFOIDLPINBLBEKAGOFHCGMFIPLIIGGNFID/dequantizeW/4-1-1/dequantizeW.so

**Comment by jackm321** [comment]
Is this related to #2742?

**Comment by nadavrot** [comment]
@jackm321 This is a dup of  #2742. Thank you.  Closing.
