### ISSUE TITLE
resnet-runtime example should have configurable backend

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/glow#2812]
The backend kind in `resnet-runtime.cpp` should be configurable. We should not have to manually edit the source file to switch between backends.

**Comment by SplitInfinity** [comment]
(cc: @nickgg)

**Comment by sri-desai** [comment]
I've created a pull request #2925 for this issue.  This is my first PR on Glow platform. 

Let me know any changes needs to be done.
