### ISSUE TITLE
Heterogeneous partitioning example code

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#2814]
Heterogeneous partitioning (where the runtime has devices of different types and operator support levels) is a common ask from users and vendors. We are adding support in #2687, and we should add a example code that demonstrates how to use it effectively.

In an existing example (resnet-runtime?) or as a new one demonstrate how to set up a system that contains one device with limited operator support and a CPU backend which handles any remaining operators.

**Comment by beicy** [comment]
#3197 provides the test code. Will add doc as well.
