### ISSUE TITLE
Support Ahead of Time compilation of partitioned networks

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#2815]
In the Runtime we may partition a network into multiple sub-graphs intended for different cards, or in the case of heterogeneous partitioning, even different backend kinds. Implement bundle saving for a partitioned network and the ability for the HostManager to save and load these bundles.

**Comment by nadavrot** [comment]
I imagine that the usecase that drives this feature is the multi-device support. But it feels like we would need to also pre-compile a part of the runtime into some AOT module. Wouldn't it be better to just provide some low-level building blocks (by compiling one function at a time) that can be stitched by whoever wants to use the AOT compilation on a static device?

**Comment by nickgg** [comment]
duplicate of #1350.
