### ISSUE TITLE
ONNX update

### ISSUE THREAD

**Issue by ayermolo** [pytorch/glow#2878]
Are there any plans to update ONNX in GLOW?

One of my small changes went in to ONNX that streamlines windows build. Would be nice if it was part of GLOW. :)

Thanks.

**Comment by jackm321** [comment]
Hi @ayermolo, I don't think there are any plans at the moment to update onnx in Glow. Glow uses ONNX for some things but uses a fork of ONNX called foxi for onnxifi which gets updated more frequently. Please feel free to update ONNX in Glow if it would be helpful to you.

**Comment by ayermolo** [comment]
Done
