### ISSUE TITLE
[PartitionerUtils] Multi-output nodes not correctly accounted for inMemSize?

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#2885]
In the snippet below, we're using `getType(0)` to update the `inMemSize`. This smells like it will incorrectly account for a multi-output node when calculating `inMemSize`. 

E.g. if we partition such that a `TopK` node's `Indices` output (which is its second output) as feeding the input of another partition, then I believe `inMemSize` will call `getSizeInBytes()` on the `Values` output instead of `Indices`.

FWIW it looks like it's correctly handled in `getOutMemPerNode()`.

@beicy does this appear to be an issue? 

https://github.com/pytorch/glow/blob/f2e37eb88cc2378622dc601afcbe28790cdbf61d/lib/Partitioner/PartitionerUtils.cpp#L189-L197

**Comment by jfix71** [comment]
Same thing appears to occur here:

https://github.com/pytorch/glow/blob/65aa6175548e410e4689da25095d07d4e7bf8abf/lib/Partitioner/Partitioner.cpp#L161-L170

**Comment by beicy** [comment]
> In the snippet below, we're using `getType(0)` to update the `inMemSize`. This smells like it will incorrectly account for a multi-output node when calculating `inMemSize`.
> 
> E.g. if we partition such that a `TopK` node's `Indices` output (which is its second output) as feeding the input of another partition, then I believe `inMemSize` will call `getSizeInBytes()` on the `Values` output instead of `Indices`.
> 
> FWIW it looks like it's correctly handled in `getOutMemPerNode()`.
> 
> @beicy does this appear to be an issue?
> 
> https://github.com/pytorch/glow/blob/f2e37eb88cc2378622dc601afcbe28790cdbf61d/lib/Partitioner/PartitionerUtils.cpp#L189-L197

Thanks for pointing out this one. You are right, this part need to be fixed. So far, only en2gr uses TopK, and I do notice that we have a cut after TopK and the 2 outputs go to different partitions.  But I think since the output size is small compared to the constants, the estimation is not accurate but does not affect the partition result...  Anyway, I will fix this calculation.

**Comment by jfix71** [comment]
Cool, yeah nothing urgent, just noticed it as I was cleaning things up.
