### ISSUE TITLE
Habana CompiledFunction should be stateless

### ISSUE THREAD

**Issue by gcatron** [pytorch/glow#2905]
With the addition of DeviceBindings to the ExecutionContext the Habana compiledFunction should be refactored to be stateless. This way the same compiledFunction can be run on multiple cards. Once this is done we can close #1951 .

**Comment by bertmaher** [comment]
What state needs to be removed, exactly?  There's ctx_ (which is unused), but the rest is not mutated during execute()

**Comment by bertmaher** [comment]
Double checking, HabanaFunction is good to go.  It doesn't contain any device-specific or mutable state.
