### ISSUE TITLE
Glow fails due to the partitioner

### ISSUE THREAD

**Issue by tlepley-cadence** [pytorch/glow#2937]
@beicy I've just rebased our work on top of the latest Glow master branch and it doesn't work anymore with our backend when calling `image-classifier` (we use the `-<backend>` command line option to specify our backend).

I get this strange error.
```
Encountered an error, exiting.
location: /home/tlepley/git/glow/lib/Partitioner/Partitioner.cpp:796 message: Partition failed: the number of given (CPU) devices (1) is fewer than the required minimal partitions (76).
```
Note that we use the  default `DummyDeviceManager`.

I'm currently investigating, but I didn't find yet the source of the problem.

**Comment by tlepley-cadence** [comment]
I think I found the reason. The `DummyDeviceManager` has a too small memory declaration, what I guess ends up generated many partitions.

**Comment by bertmaher** [comment]
Disappointing that "Fixes" no longer works properly now that facebook-github-bot manages this repo, but this was fixed by the linked PR, I believe
