### ISSUE TITLE
Unable to build glow due to undefined reference to symbol

### ISSUE THREAD

**Issue by derekzTu** [pytorch/glow#2939]
Recently my build of Glow have been failing on binaries such as bin/text-translator, bin/ptb, etc. Seems like all of the  binaries defined in https://github.com/pytorch/glow/blob/master/tools/loader/CMakeLists.txt are failing due to the same problem: 
```
/usr/bin/ld: lib/Support/libSupport.a(ThreadPool.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
I've tried manually adding '-lpthread' to the compilation of ThreadPool.cpp.o, but it doesn't seem to help.
I've also tried building with both clang-6.0/clang-6.0++,  and gcc/g++, but both encounter this same error.
For reference this is how I'm trying to build glow:
```
cmake -G Ninja ../glow -DCMAKE_BUILD_TYPE=Release
ninja all
```
and these are the compilation lines for ThreadPool.cpp.o and libSupport.a respectively
```
/usr/bin/c++  -DGLOW_WITH_LLVMIRCODEGEN=1 -DWITH_PNG -I/home/ours/glowEMIT/include -Iinclude -I. -I/home/ours/glowEMIT -I/home/ours/glowEMIT/externalbackends -isystem /usr/local/include -I/home/ours/glowEMIT/thirdparty/fp16/include -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti -Wno-psabi -O3 -DNDEBUG -march=native -ffast-math -fno-finite-math-only -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++14 -MD -MT lib/Support/CMakeFiles/Support.dir/ThreadPool.cpp.o -MF lib/Support/CMakeFiles/Support.dir/ThreadPool.cpp.o.d -o lib/Support/CMakeFiles/Support.dir/ThreadPool.cpp.o -c /home/ours/glowEMIT/lib/Support/ThreadPool.cpp
```
 ```
: && /usr/bin/cmake -E remove lib/Support/libSupport.a && /usr/bin/ar qc lib/Support/libSupport.a  lib/Support/CMakeFiles/Support.dir/Debug.cpp.o lib/Support/CMakeFiles/Support.dir/Error.cpp.o lib/Support/CMakeFiles/Support.dir/Random.cpp.o lib/Support/CMakeFiles/Support.dir/Support.cpp.o lib/Support/CMakeFiles/Support.dir/ThreadPool.cpp.o && /usr/bin/ranlib lib/Support/libSupport.a && :
```
EDIT: I forget to mention that I'm trying to build on Ubuntu 18.04

**Comment by bertmaher** [comment]
It's not supposed to be necessary with C++11, but maybe take a look at https://cmake.org/cmake/help/latest/module/FindThreads.html.

**Comment by derekzTu** [comment]
Thanks Bert! I added  `find_package(Threads REQUIRED)` 
to all CMakeLists.txt that defined binaries that had the problem and added `Threads::Threads`  to each binary's target_link_library and it passed the building phase.

**Comment by bertmaher** [comment]
Awesome, glad that worked!  Please feel free to send a PR, it might help others who run into this case :-)
