### ISSUE TITLE
libjit: remove the memory allocation on un-packed matmuls.

### ISSUE THREAD

**Issue by nadavrot** [pytorch/glow#2940]
libjit: remove the memory allocation on un-packed matmuls. Our matrix multiplication implementation allocates memory for the packed case. We should not allocate memory if we are not going to use it. 

To reproduce: take a look at the implementation of matmul-libjit and grep for malloc.

**Comment by rdzhabarov** [comment]
The only dynamic allocation I currently see in the libjit_matmul is https://github.com/pytorch/glow/blob/master/lib/Backends/CPU/libjit/libjit_matmul.cpp#L229

which is for packed structures.

Is this issue obsolete @nadavrot?

**Comment by bertmaher** [comment]
I think this literally needs an `if (pack)` around the `libjit_aligned_malloc`.
For extra credit we could allocate that buffer in TLS so it doesn't need to be reallocated on subsequent calls.
