### ISSUE TITLE
[Quantization] Why always pass zero offset for destination?

### ISSUE THREAD

**Issue by pshung** [pytorch/glow#2973]
https://github.com/pytorch/glow/blob/d5e0143bf6215d829b8bd2ea4a23e6a3aa2e17dc/lib/LLVMIRCodeGen/LLVMIRGen.cpp#L1686-L1687

Can anyone explain why not pass destTy->getOffset()?
Asymetric quantization can have non-zero offset.

**Comment by jfix71** [comment]
Here's an explanation from the PR that made the change: https://github.com/pytorch/glow/pull/740#issuecomment-373441264

**Comment by pshung** [comment]
thanks for the information.
