### ISSUE TITLE
RecommendationSystemTest fails in Debug+ASAN

### ISSUE THREAD

**Issue by gcatron** [pytorch/glow#2982]
createRandomizedConstant for int32 can result in an integer overflow when running in debug with ASAN
looks like the offending line is 156, INT32_MAX appears to be too large a range.

**Comment by nadavrot** [comment]
I think that @bertmaher had a PR for fixing something similar. Was his change related to this issue?

**Comment by bertmaher** [comment]
This issue is similar (bad ranges in random numbers) but actually in a different place.  I'm hard pressed to see how this particular issue shows up unless there's a bug in uniform_int_distribution, which seems... unlikely.

**Comment by gcatron** [comment]
The exact error: algorithm:3033:35: runtime error: signed integer overflow: 2147483647 - -2147483647 cannot be represented in type 'int'

**Comment by rdzhabarov** [comment]
Should be fixed by @gcatron PR above ^
