### ISSUE TITLE
Mismatch between source and weight dimensions

### ISSUE THREAD

**Issue by derekzTu** [pytorch/glow#2987]
I'm trying to emit a bundle for a Neural Network created using caffe2. I am loading the model by giving Glow an init_net.pb and and predict_net.pb. 
https://github.com/pytorch/glow/blob/1ec602a91466a3df1a5152dca27e12fc99559cc1/lib/Importer/Caffe2ModelLoader.cpp#L1490
fails because due to verifying a fully connected node:
https://github.com/pytorch/glow/blob/1ec602a91466a3df1a5152dca27e12fc99559cc1/lib/Graph/Nodes.cpp#L228
in function
https://github.com/pytorch/glow/blob/1ec602a91466a3df1a5152dca27e12fc99559cc1/lib/Graph/Nodes.cpp#L219

The weights dimension I know is correct from calculating what it should be on my side, but the source dimension is not. Would someone mind pointing me to the code that specifically defines how the source dimension is calculated? Is it using values that Glow calculates or is it grabbed from the init_net.pb/predict_net.pb?

**Comment by nadavrot** [comment]
@derekzTu Thank you for working on this and filing the issue.  Could you print the values that don't match within the assertion?

**Comment by derekzTu** [comment]
@nadavrot 
Here is the error output:
```
In 'dense_0' From <folder_containing_pb_files'
Mismatch between source and weight dimensions
For comparison `LHS Equal RHS` with:
LHS: 1706504
RHS: 4864
Encountered an error, exiting.
```
```
For reference here are the values of filters, and outputs of the different nodes:
Tensor("Reshape:0", shape=(?, 49, 10, 1), dtype=float32) <- Input
<tf.Variable 'Variable:0' shape=(10, 4, 1, 60) dtype=float32_ref> <- First weights dimensions (H,W,C,N)
First conv  Tensor("Conv2D:0", shape=(?, 40, 7, 60), dtype=float32) <- First Convolution Output (N, H, W,C)
<tf.Variable 'Variable_2:0' shape=(10, 4, 60, 76) dtype=float32_ref> <- Second weights dimension
Second conv  Tensor("add_2:0", shape=(?, 16, 4, 76), dtype=float32) <- Second convolution Output
Flattened  Tensor("Reshape_1:0", shape=(?, 4864), dtype=float32) <- Input to dense_0 (FC layer)
```

**Comment by jfix71** [comment]
>The dimensions gotten by the NodeValue at this point for the FC layer are 1, 76, 103, 218 even though they should be 1, 76, 16, 4 

Do you have any idea why this is happening -- are you thinking this is caused by a bug in Glow?

>Would it be possible to just hard code the values to what they're expected be without anything else in Glow crashing?

Not sure what you mean by this -- can you expand on this?

**Comment by derekzTu** [comment]
> Do you have any idea why this is happening -- are you thinking this is caused by a bug in Glow?

I don't think so. By the time we're loading the network into Glow at: https://github.com/pytorch/glow/blob/b0431220be7a67843dcc876a0e58a99830e8be88/lib/Importer/Caffe2ModelLoader.cpp#L1484
and subsequently
https://github.com/pytorch/glow/blob/b0431220be7a67843dcc876a0e58a99830e8be88/lib/Importer/Caffe2ModelLoader.cpp#L1129-L1134

It seems that all the NodeValues have already been declared and created. So either my predict_net.pb is incorrect in the first place or it could be an error when the predict_net.pb is being read in. For the latter my best guess would be the error happens when Glow loads the protofile at:
https://github.com/pytorch/glow/blob/b0431220be7a67843dcc876a0e58a99830e8be88/lib/Importer/Caffe2ModelLoader.cpp#L198-L204
and something goes wrong with the google:protobuf or caffe2::NetDef API's. However, I'm still not quite sure when the NodeValues are created, so if my logic is wrong feel free to tell me.

> Not sure what you mean by this -- can you expand on this?

Sorry, since the the error is caused by incorrect values stored into the NodeValue, I was wondering if I could manipulate a NodeValue object directly in order to set the dimensions stored in it.

**Comment by jfix71** [comment]
These shapes can either come from Constants which are loaded from the init net, or from Placeholders which are specified by the user, representing the images that will be loaded in. A NodeValue represents any result from any node, meaning it could be the "output" from a Placeholder or a Constant. Did you set up the Placeholder shapes correctly? If it's possible to share the protos it would be easier for me to tell.

**Comment by derekzTu** [comment]
Sure, do you mean the init_net.pb, predict_net.pb, and predict_net.pbtxt? If so what would be the best way to share it since github does not support such files?

**Comment by jfix71** [comment]
Yeah, those files. Perhaps you could zip them, I think GH supports zips. Also would need to know how you're feeding the Types/Placeholder names into the `Caffe2ModelLoader` constructor.

**Comment by derekzTu** [comment]
[protos.zip](https://github.com/pytorch/glow/files/3234784/protos.zip)

Run command is: bin/./image-classifier tests/images/imagenet/cat_285.png --image-layout=NCHW -m=<path_to_protos> -model-input-name=data -cpu -emit-bundle ./testDir/ 

Image-classifier is unchanged. Also now that I think about it would be possible that the NCHW values in the png is the problem as they are different values to what the NN expects. But in that case why would it only show up on the FC layer, which is later on in the network.

**Comment by jfix71** [comment]
Yeah so what dimensions are you using for your input image(s)? What's the batch size?

>But in that case why would it only show up on the FC layer, which is later on in the network.

**Comment by derekzTu** [comment]
I've been using your default image with a single image. 

> The data input for your graph has its shape set based on the Placeholder and the actually loaded images/batch size.

If that's the case then it makes sense. I'll try again with an input that matches what the NN expects
