### ISSUE TITLE
AOT Bundles should be regression tested

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#3013]
Currently there is no unit tests or regression tests for Bundle saving and loading, we could probably just write a script that runs the four example bundles lenet_mnist and resnet50 (+ their quantized versions) and checks for expected outcomes.

**Comment by jfix71** [comment]
We currently do test `lenet_mnist` bundles, both float/quantized. See `run_and_check_bundle()` in [.circleci/test.sh](https://github.com/pytorch/glow/blob/master/.circleci/test.sh), which is run as part of the `DEBUG` test currently.
