### ISSUE TITLE
Don't zero tensors unnecessarily

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#3037]
Tensors are allocated and zeroed in their constructor, but usually we're going to copy/move data into them anyway without reading the initialized values. Remove this unnecessary step.

Probably requires going through the code for Tensor creation, working out which stuff relies on zeroing and adding a manual zero().

**Comment by jackm321** [comment]
dup of #2773

**Comment by nickgg** [comment]
Oh weird, I never looked into this so not sure why I closed it - maybe typo'd the issue number.
