### ISSUE TITLE
Proposal: constant folding on model load

### ISSUE THREAD

**Issue by Max-K-cadence** [pytorch/glow#3048]
Hi,

I have a proposal for a feature and I'd like to know if it can be accepted. The motivating example I have is following:

`Reshape(X, Gather(Shape(Y), const))`

Currently, GLOW is unable to load models with such pattern. The reason is following: GLOW needs to statically know shapes of all output tensors. To know the output shape of Reshape, it needs its shape argument to be a constant. In my example, the model gets rejected because it is a Gather and not a constant.

However, `Shape(Y)` is always a constant, and `Gather(const, const)` can actually be constant-folded. When it is done, we can load such model.

More general statement of the problem: GLOW sometimes requires that some parameters are constants, but does not perform early constant-folding. Therefore, it rejects some models that it could load if it was done.

The solution is following: we can introduce API to add method `constantFold` to a node. Iff all node inputs are constant, we can acquire their tensors and perform the same logic as in Interpreter backend. This will allow us to get static constant for such nodes instead of Instruction on load stage.

The idea of code changes is following:
- Introduce special flag to node builder that will add constant folding method on request;
- For each node for which we want to constant-fold, factor out its evaluation method from Interpreter backend to a separate function some ConstantFolding.h file;
- Now, both constant-fold method and Interpreter backend call this same function;
- In Model Loader, add logic like: `if (Tensor *CF = node->tryConstantFold()) { <register constant for node>}`.

I already have an implementation of this for Gather node that enables the said class of models. This can be expanded into a wider number of nodes incrementally.

What do you guys think of that?

**Comment by jfix71** [comment]
Hi @Max-K-cadence, thanks for the interesting proposal. We have discussed similar things in the past -- see https://github.com/pytorch/glow/issues/1469 where some of these ideas are referenced. IMO this would be a good feature to have in Glow. I am a bit wary of the complexities here, though -- since you mention you already have an implementation of this for Gather, it would be great to see a branch/PR with those changes so we can evaluate the pros/cons.

**Comment by Max-K-cadence** [comment]
Thanks for quick reply @jfix71! It's not as complex as it sounds. :) I'll polish the patch and put it for public review within next few days.

**Comment by Max-K-cadence** [comment]
https://github.com/pytorch/glow/pull/3063
