### ISSUE TITLE
Question: MaxPoolWithArgmax - new node or new output to existing node?

### ISSUE THREAD

**Issue by Max-K-cadence** [pytorch/glow#3053]
Hi, I'm working on #2974, and I have a design question to discuss before I come up with final version. In ONNX, MaxPool has an optional output that calculates ArgMax that we need to support. In GLOW, I did not find a mechanism to specify that an output is optional for some node. It means that if we have specified the output, we should at least initialize it correctly.

There are two possible ways to implement this optional output.

Approach 1 (which I currently have):
I've introduced a new node MaxPoolWithArgmax and did not touch the existing node MaxPool. When we parse ONNX file, we create one or another node, depending on whether the 2nd output is specified. Then I hacked the computation methods in CPU and Interpreter backends so that the same functions can be used to handle both kinds of nodes.
The upside of this approach is that it does not break any existing code.
The downside is that we have some code duplication in sense of node declaration.

Approach 2 (which we internally discuss):
We could instead tweak MaxPool node to have 2 outputs, add a Boolean field signaling whether or not the 2nd output is actually calculated. It means that we should always initialize this 2nd output with some tensor, even if we never use it.
The upside of that is less code duplication, and node's API will match those in ONNX.
The downsides are:
- We have this dummy type initialization whenever we create a node;
- Other (maybe downstream) backends may not compile if they create these nodes inside, so this may disrupt someone's work.
- If some backend is not aware that there can be this 2nd output, this may cause a more sneaky bug than just failure with unsupported node kind.

What do you guys think would be a better way to do it?

**Comment by Max-K-cadence** [comment]
P.S. I noticed that a related duscussion is already ongoing: #3044

**Comment by jfix71** [comment]
Hi @Max-K-cadence -- so when thinking about an answer I realized that we already do have some support for argmax, but it's only used right now for training after we differentiate, and we only have an Instruction for it: `MaxPoolWithXYInst`. We also have `MaxPoolInst`, which does not save the indices.

What happens here is, this `MaxPoolWithXYInst` is always IRGen'd from a `MaxPoolNode`, and then in our IROptimizations we will swap out the `MaxPoolInst` if a later `MaxPoolGradNode` did not use the `SrcXY` output from `MaxPoolWithXYInst`.

I think it would make more sense to add this `SrcXY` output to the `MaxPoolNode`, similar to your approach 2, and then do this selection between `MaxPoolInst` vs. `MaxPoolWithXYInst` at IRGen time. I don't think it's necessary to add the boolean; I believe it's sufficient to simply check if the output has any users to decide which kernel (instruction) to use. WDYT?

**Comment by Max-K-cadence** [comment]
Hi @jfix71, I think this might work. I'll try to prototype that.

**Comment by Max-K-cadence** [comment]
I tried this approach, and so far it seems much harder than solution with new node. After adding 2nd output and fixing all failures that are related to creation of NodeValue(MaxPool), there are still failures in many tests that are all related to graph optimization in presence of MaxPoolGrad node. I don't understand what the failures are, it will take time to investigate. I'd rather stick to non-invasive approach 1 that will not change anything at least in existing tests.

Maybe it makes sense to introduce a new node MaxPoolWithArgmax now and then consider merging it together with MaxPool if it is possible. So far I am not sure that it is possible because of Gradient, and I don't quite understand what the problem with it is.

@jfix71 would that work?

**Comment by jfix71** [comment]
Hi @Max-K-cadence, I was curious about what issues that would be hit here, so I took a pass at implementing this too, and I was able to get it to pass all of our unit tests. Here's a branch: https://github.com/pytorch/glow/compare/master...jfix71:add_srcxy_maxpool. Let me know what issues you might have with it, and how it compares to your other suggested implementation in terms of complexity.

**Comment by Max-K-cadence** [comment]
Hi @jfix71, it looks pretty much the same. Seems that I missed the logic from `Fix grad stuff` that protects from null input. I'll try to make the same fixup and see if it works, thanks!

**Comment by Max-K-cadence** [comment]
I've looked into MaxPoolWithXY instruction a bit more, and now I think that this entire instruction should be removed. X and Y indies are used for training, that's why it exists. We need to calculate ONNX Argmax, which means that we should somehow store this Flattened Index. The most natural way for it is to either create a new type of instruction, or add it as output to existing instructions.

Either approach is bad. We will need:
- MaxPoolInst;
- MaxPoolWithXYInst (for training);
- MaxPoolWithArgmaxInst (what we are trying to do);
- MaxPoolWithArgmaxAndXYInst (which we will create in IRGen and then turn to whatever we need).

But in fact, Argmax is a flattened NCHW index. To get X and Y out of it, you can use simple formulae:
`X = (Argmax / size.w) % size.c, Y = Argmax % size.h;`

We should just calculate Argmax, and whenever we need X and Y for training, we can restore them using this formula. This will make GLOW instructions in sync with ONNX actually has, and we will need 2x less memory to store this extra data.

WDYT?

**Comment by Max-K-cadence** [comment]
My summary so far:

With @jfix71 's fix for Grad, I'm able to add a new input Argmax to MaxPool node so that all existing tests pass. Now I am trying to understand the best way to map it on instruction. The straightforward way with 4 of instructions from post above looks ridiculous and overcomplicated. So far I'm swaying towards replacement of MaxPoolWithXYInst with MaxPoolWithArgmaxInst. What bugs me here is that this would be a super-invasive change that also touches OpenCL, and I'm not sure if delinearization is possible/profitable in OpenCL.

**Comment by jfix71** [comment]
@Max-K-cadence Thanks for investigating this. Yeah I think it makes sense to replace `MaxPoolWithXYInst` with `MaxPoolWithArgmaxInst` and then inside all of our MaxPoolWithXYGradInst kernels in the backends just modify them to expect a flattened input instead of x/y. I think there should be a way to do this without a perf impact on the backends, as in the end they use the `{x, y}` inputs as indices inside SrcGrad, and so they get implicitly get flattened in the end when calculating the offset into SrcGrad. It actually might save us a MAC in addition to memory savings 🙂does this make sense?

**Comment by Max-K-cadence** [comment]
Yeah, it does. I'm currently trying to do that. :)

**Comment by Max-K-cadence** [comment]
Implementation on review.
