### ISSUE TITLE
How to support TensorFlow operators that cannot be easily converted to ONNX?

### ISSUE THREAD

**Issue by Max-K-cadence** [pytorch/glow#3153]
Hi,

Sorry for long wall of text, I just want to give a comprehensive description of a problem I have and a solution I see.

I have a conceptual question about how we can support nodes that are not described in ONNX format, but are described in TensorFlow format and there is no easy way to convert one to another. Specifically, I am working with a model that has ScatterNd node which is described here:

https://www.tensorflow.org/api_docs/python/tf/scatter_nd

Conceptually, ScatterNd is pretty similar to Glow's ScatterAssign node, with two significant differences:

1) ScatterAssign only assigns `(N-1)`-dimensional slices to `N`-dimensional dest by `1`-dimensional indices. ScatterNd may assign `K`-dimensional slices to `N`-dimensional dest by `(N-K)`-dimensional indices;
2) ScatterNd allows duplication of indices. If some index is seen twice, their updates are summed.

Otherwise it does the same thing as ScatterAssign. Due to property 1), it is more generic. Along with property 2), ScatterNd is virtually a generalized version of "Scatter add" to a new destination.

There are three possible ways how we can bring support of ScatterNd in glow:

_Approach 1: support it in tf2onnx converter_
There is an ongoing discussion about it here: https://github.com/onnx/tensorflow-onnx/issues/455
Unfortunately, there is no simple mapping between ScatterNd and anything that ONNX currently supports. I've been studying it myself and came to same conclusion as @chinhuang007: implementing this conversion is going to be a lot of pain. I don't really believe it's going to happen soon.

_Approach 2: add this node to ONNX standard_
There is also a discussion about adding this node to ONNX standard: https://github.com/onnx/onnx/issues/2074#issuecomment-500511404. There is some idea about mapping it to ONNX Scatter node, however the complexity of index conversion that needs to be done before it is very high. I don't see much progress on this way either.

_Approach 3: support ScatterNd as if it was an ONNX node, using TensorFlow specification_
We may just pretend that Approach 2 has worked, and ScatterNd is described in ONNX standard, and its description is a perfect match with that in TensorFlow. Then we can just support it in Glow.

Given that Approaches 1 and 2 give no results for quite a time, I wanted to ask, can I follow Approach 3 in Glow project? Implementation here is not super-hard, I already have a working prototype for interpreter, however it is a conceptual question: can we create a precedent of introducing an "not yet described ONNX node"? Or we should only add nodes that are described in ONNX standard in Glow?

If the answer to that is *yes*, then I'd like to describe how we can design the solution. After making a prototype (that uses a custom node lowered to custom instruction), I realized that it has a lot of common with existing ScatterAssign node. So the solution plan I suggest is the following:
- We can change semantics of ScatterAssign so that it has property 1) (can set by multi-dimensional indices);
- We add a new node ScatterAdd that will be similar to ScatterAssign, with difference of supporting property 2) (accumulation for duplicating indices);
- Lower ScatterNd to this ScatterAdd node.

What do you think? Can we do this upstream? :)

**Comment by jfix71** [comment]
CC: @putivsky RE: Approach 3 mentioned here.

Assuming ScatterNd is somehow represented to Glow as an op to build, I think it makes sense to add ScatterAdd with the semantics you described to implement it. I'm not sure why we need to modify ScatterAssign though, it wouldn't be used at all when lowering ScatterNd right?

**Comment by Max-K-cadence** [comment]
> I'm not sure why we need to modify ScatterAssign though, it wouldn't be used at all when lowering ScatterNd right?

Yes, but it will be strange to have ScatterAdd working with multi-dimensional indices and ScatterAssign working with 1D indices only. So it's just for unification reasons.

Alternatively, they can actually be one node with Boolean flag switching between Set and Add. WDYT?

**Comment by jfix71** [comment]
I think I like adding the boolean flag better, essentially the only difference between them is whether to accumulate or assign, and I think virtually all optimizations we'd want to perform would apply to both.

**Comment by Max-K-cadence** [comment]
Allright! I'm on the way of preparing this solution. :) Thanks!

**Comment by Max-K-cadence** [comment]
> I think virtually all optimizations we'd want to perform would apply to both.

Not all of I can imagine, for example:
```
ScatterAssign(dest, indices, upd1)
ScatterAssign(dest, indices, upd2)
```
can be optimized to 
```
ScatterAssign(dest, indices, upd2)
```
But for Add, the right thing would be
```
ScatterAdd(dest, indices, upd1 + upd2)
```
But I think the opts we are currently doing are not too numerous, I'll review them and see if any of them needs amendment.

**Comment by jfix71** [comment]
RE:

```
ScatterAssign(dest, indices, upd1)
ScatterAssign(dest, indices, upd2)
```

ScatterAssign doesn't zero `dest` or necessarily fully overwrite all of `dest`, so I think the same optimizations would still apply. I.e. the second ScatterAssign in your example doesn't necessarily totally kill the first, because they could be writing to different indices.

But yeah they would have different optimizations here, I agree.

**Comment by Max-K-cadence** [comment]
I meant two consecutive scatters of different values by same indices, like
```
dest1 = ScatterAssign(dest, indices, upd1)
dest2 = ScatterAssign(dest1, indices, upd2)
```
can be turned to
```
dest2 = ScatterAssign(dest, indices, upd2)
```

**Comment by Max-K-cadence** [comment]
I guess we still need to decide whether or not the "Approach 3" from the initial post is an acceptable solution (after all these things are done to ScatterAssign/Add).
@putivsky

**Comment by jfix71** [comment]
@Max-K-cadence I believe @putivsky is adding Glow extensions to the ONNX standard in #3167 to be able to export a Glow graph in ONNX. I think you could follow a similar path he is taking.

**Comment by ayermolo** [comment]
Well Approach 3 is what I am currently taking to support ONNX NMS and TF V4 NMS that was converted as custom layer.

**Comment by Max-K-cadence** [comment]
Thank you for your answers!
