### ISSUE TITLE
debuging on run

### ISSUE THREAD

**Issue by ezimmer9** [pytorch/glow#3187]
Hi,

i'm creating a new network from the C++ API and i want to debugging the network while it is running. (see the tensors outputs, no only the outputs on the end).
is there any way to do this?

thanks

**Comment by opti-mix** [comment]
@ezimmer9 You could try to use the `-instrument-debug` options. It should print the content of all inputs tensors before an instruction and of all outputs after an instruction.

**Comment by nickgg** [comment]
@opti-mix does that flag work on all backends or only those using Glow IR ?

**Comment by opti-mix** [comment]
@nickgg 

> does that flag work on all backends or only those using Glow IR ?

This flag is only for the backends working on low-level Glow IR. We do not support it for graph based IR, though it should be pretty straight-forward given that you introduced the tracing machinery recently.

**Comment by ezimmer9** [comment]
@opti-mix 
i'm currently working on CPU backend. on this it should work?

thanks.

**Comment by opti-mix** [comment]
@ezimmer9 
> i'm currently working on CPU backend. on this it should work?

Yes, `-instrument-debug` should work out of the box on CPU backend. Just pass this option to image-classifier or whatever you use to run your models.

**Comment by ezimmer9** [comment]
i'm using with the -instrument-debug-only flag.
thanks!
