### ISSUE TITLE
ONNX Importer loadConv doesn't return error when bias is not found but is expected.

### ISSUE THREAD

**Issue by vuzelac-cadence** [pytorch/glow#3216]
When bias is expected, `getConstantByNameOrNull `allows for bias not to be found, which will result in the zero bias being created. Isn't returned NULL supposed to be an error ?
Actually, this was an error until PR #2865. The code before this change was:
`ASSIGN_VALUE_OR_RETURN_ERR(b, getTensorByName(biasTensorName));
`
https://github.com/pytorch/glow/blob/cb7c305923902f375522771379b77ac93210367e/lib/Importer/ONNXModelLoader.cpp#L604-L608

**Comment by vuzelac-cadence** [comment]
@jfix71 , @jackm321

**Comment by jfix71** [comment]
Good catch! Yes, I agree this should be an error. Are you interested in putting up a fix?

**Comment by vuzelac-cadence** [comment]
Sorry for the delay. At the moment, I can't spend time upstreaming. if it's not fixed in about a month or so, I'll upstream.
