### ISSUE TITLE
Loader must guard against unsupported backends in interpreter mode

### ISSUE THREAD

**Issue by wyessen** [pytorch/glow#3221]
When running `model-runner` (or in fact any model builder that uses the loader) in non-bundle-emitting mode, specifying `-backend=CPU` causes SIGSEGV. The loader (perhaps in `Loader::runInference`) must guard against this to make sure that the correct backend is created. That is, if `emittingBundle()` returns `false` and if `backend` is not set to `Interpreter`, the `Loader` should throw an exception. A corresponding test should be added to the test suite.

A minimal reproducible example is below.

**The Model**
```
import numpy as np
import torch
import random

class FeedForwardNN(torch.nn.Module):
    def __init__(self, nx, nh, ny, depth, hidden_activation = torch.nn.ReLU(), 
                 output_activation = torch.nn.Sigmoid(), seed = None, dtype = torch.FloatTensor):
        super().__init__()
    
        if seed is not None:
            torch.manual_seed(seed)
        
        self.params = torch.nn.ParameterList()

        self.layers = [torch.nn.Linear(nx, nh).type(dtype)]
        self.layers.append(hidden_activation)
        
        for _ in range(depth):
            self.layers.append(torch.nn.Linear(nh, nh).type(dtype))
            self.layers.append(hidden_activation)
            
        self.layers.append(torch.nn.Linear(nh, ny).type(dtype))
        self.layers.append(output_activation)
        
        for layer in self.layers:
            self.params.extend(layer.parameters())
        
    def forward(self, x):
        y = x
        for layer in self.layers:
            y = layer(y)

        return y

ffnn = FeedForwardNN(2, 2, 1, 1)
ffnn.train(False)
inp = torch.autograd.Variable(torch_test_input[:1])
input_names = ["in"]
output_names = ["out"]
torch.onnx.export(ffnn, inp, "ffnn.onnx", input_names=input_names, 
                  output_names=output_names, verbose=True, export_params=True)
```

**The Model Runner**
```
#include "Loader.h"

#include "glow/Graph/Nodes.h"
#include "glow/Importer/Caffe2ModelLoader.h"
#include "glow/Importer/ONNXModelLoader.h"

#include "llvm/Support/raw_ostream.h"

#include <memory>

using namespace glow;

int main(int argc, char **argv) {
  parseCommandLine(argc, argv);
  Loader loader;
  Type inputType(ElemKind::FloatTy, {1, 2});
  PlaceholderBindings bindings{};

  std::unique_ptr<ProtobufLoader> LD;
  LD.reset(new ONNXModelLoader(loader.getOnnxModelFilename(), {"in"}, {&inputType},
                                *loader.getFunction()));

  bindings.allocate(loader.getModule()->getPlaceholders());
  loader.compile(bindings);
  loader.runInference(bindings);

  return 0;
}
```

**The Test (using the correct backend, or omitting backend specification)**
```
vagrant@ubuntu-clean-for-test:~/dts/nn/xgmr/build/debug$ ./bin/model-runner -model=../../../pytorch_tuts/ffnn.onnx -backend=Interpreter
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0711 00:54:44.736732  1499 Partitioner.cpp:959] The model is too small for applying partition.
Model size : 716
Device memory: 2000000000
```

**The Test (using an incorrect backend)**
```
vagrant@ubuntu-clean-for-test:~/dts/nn/xgmr/build/debug$ ./bin/model-runner -model=../../../pytorch_tuts/ffnn.onnx -backend=CPU
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0711 00:54:50.249296  1504 Partitioner.cpp:959] The model is too small for applying partition.
Model size : 716
Device memory: 2000000000
./bin/model-runner[0x6d251a]
./bin/model-runner[0x6d0be4]
./bin/model-runner[0x6d0d22]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f780dcf0890]
Segmentation fault (core dumped)
```

**Comment by jfix71** [comment]
Thanks for reporting this @wyessen. So when you try using any of the Loader-based runners without emitting a bundle and with the CPU backend you're seeing a segfault?

I run this regularly with no issues (e.g. executing `./tests/images/run.sh -backend=CPU`), nor other models using the `model-runner`. Can you try running the `run.sh` and report if that works?

Perhaps you could share the `ffnn.onnx` proto so we can check it on our end?

**Comment by wyessen** [comment]
@jfix71 That's correct. Well, actually, I've only confirmed this with `model-runner` (rather a slight modification thereof pasted in the original issue post above). I may also be a few commits behind, so I should resync. 

I'm sharing `ffnn.onnx`, hopefully that will suffice. The input tensor name is "in", the output tensor name is "out", and the input tensor dimensions are `{1, 2}`. 

[ffnn.onnx.zip](https://github.com/pytorch/glow/files/3379922/ffnn.onnx.zip)

**Comment by wyessen** [comment]
On the other hand, my initial assessment is probably wrong. It may be that there is a bug in the CPU backend.

**Comment by jfix71** [comment]
Hmm, so I am able to run it on my machine. I do want to note though that the unmodified `model-runner` is intended to be used with models that have *no inputs* -- that is, all inputs are "Constants" in Glow parlance and defined in the proto. That doesn't seem to be the case for the `ffnn.txt` proto you provided; `in` is a Node, meaning its values are inputs passed in at runtime. I think it should instead be an initializer along with `raw_data` in the proto. As this is not the case, I'm seeing random results, regardless of whether I use the Interpreter or CPU backend. I've put up #3222 to check that the loaded model by the ModelRunner has no inputs.

Perhaps your machine is segfaulting because values are uninitialized?

**Comment by wyessen** [comment]
@jfix71 Thanks for checking this. Of course, I realize that `model-runner` should not take input, which is the reason why I modified it to provide a minimal example. The logic in the modified version is essentially the same as the logic one would implement to run models with input.

Hmm, this is turning into a witch hunt, and it is probably because something is off on my end. I can think of two possible reasons:

- Somehow, unintentionally, I introduced some changes in the CPU backend (highly unlikely)
- Somehow the fact that I'm running on Ubuntu 18.04 in a VM (VirtualBox) is affecting it (also unlikely)

I began observing this behavior after https://github.com/pytorch/glow/commit/96dc43b7f184de30ac1251fe0edaad6bdd3c4455, but at this point it is hard to say if that is the reason. 

I'll create a fresh clone, rebuild, and retry. Again, I don't believe the issue is with the modified `model-runner`.

**Comment by wyessen** [comment]
@jfix71 Also, as long as the bindings are properly allocated, whether input is initialized shouldn't really matter as far as I understand. But just to be sure, here is the minimal example where input is being initialized (problem persists): 

```
int main(int argc, char **argv) {
  parseCommandLine(argc, argv);
  Loader loader;
  Type inputType(ElemKind::FloatTy, {1, 2});
  PlaceholderBindings bindings{};

  std::unique_ptr<ProtobufLoader> LD;
  LD.reset(new ONNXModelLoader(loader.getOnnxModelFilename(), {"in"}, {&inputType},
                                *loader.getFunction()));

  bindings.allocate(loader.getModule()->getPlaceholders());
  loader.compile(bindings);

  /*** Initialize input. ***/
  Placeholder *inputPH = llvm::cast<glow::Placeholder>(EXIT_ON_ERR(LD->getNodeValueByName("in")));
  Tensor *inputT = bindings.get(inputPH);
  for (auto iter = inputT->getHandle().begin(); iter != inputT->getHandle().end(); ++iter)
    *iter = 0.0;

  loader.runInference(bindings);

  return 0;
}
```

**Comment by wyessen** [comment]
Pulled latest, rebuilt, rerun. The problem persists.

**Comment by wyessen** [comment]
Alright, so this is total snafu. `gdb` was pointing at what felt like stack corruption (`$rbp` smashed to address `0x0` upon exit from the `loader::runInference()` function). `Valgrind` was also reporting similar issues with invalid access of `0x0`. This was when I was compiling with `clang-7`. Upgrading to `clang-8`, the problem went away. Moreover, I am no longer observing issues in `Valgrind` or `gdb`. 

This isn't really a solution, because it would still be nice to understand what the original issue was. Was there some bug in LLVM that was fixed in version 8? 

The more likely problem was that LLVM was picking up the wrong runtime somehow (I have quite a few cross-compile libs installed for different targets). Anyway, whatever it was, it seems to have been an effect of my build environment (beats me, though, since everything worked like a charm prior to https://github.com/pytorch/glow/commit/96dc43b7f184de30ac1251fe0edaad6bdd3c4455).

Embarrassing, but it is what it is. Thanks again for your time @jfix71 !

**Comment by jfix71** [comment]
Well that's unsatisfying 🙂but glad it was resolved. If you ever find out what the issue was, please reopen!
