### ISSUE TITLE
Runtime Bundle should not be copiable. 

### ISSUE THREAD

**Issue by gcatron** [pytorch/glow#3259]
Recently a bug was found where the runtime bundle was copied and then collectConstants was called on the copy that was thrown away, it might make sense for the Bundle to either not have a copy constructor or invalidate the old copy.

**Comment by gcatron** [comment]
@SplitInfinity

**Comment by SplitInfinity** [comment]
I tried this today and it went well until

```
            auto compiled = std::move(*compiledOrErr);
            node->runtimeBundle =
                llvm::make_unique<RuntimeBundle>(compiled->getRuntimeBundle());
            functions_.emplace(node->name, std::move(compiled));
```

in the provisioner. What's the right thing to do here?
