### ISSUE TITLE
Verify module Storage node ownership/usage

### ISSUE THREAD

**Issue by geoffberry** [pytorch/glow#3428]
Are Placeholders/Constants supposed to be owned/referenced by only one Module?  If so, it would be nice if this was verified by the verification functions.

We have run into a few test cases where Placeholders from one module were being used in a Function from a different module, which breaks one of our backend-specific optimizations that adds new Placeholders.

**Comment by jfix71** [comment]
Yeah, they are private to a Module. It may make sense to add a Module parent to Storage nodes to represent their containing Module.

**Comment by SplitInfinity** [comment]
I think it is verified by `Function::verify()`. Examine this excerpt below from `Graph.cpp`:
```
...
/// \returns True if \p n is a storage node (constant or placeholder) of the
/// function \p F.
static bool isGraphStorageNode(Node *n, const Function *F) {
  auto &vars = F->getParent()->getConstants();
  auto &placeholders = F->getParent()->getPlaceholders();

  if (Constant *V = dyn_cast<Constant>(n)) {
    return std::find(vars.begin(), vars.end(), V) != vars.end();
  }

  if (Placeholder *P = dyn_cast<Placeholder>(n)) {
    return std::find(placeholders.begin(), placeholders.end(), P) !=
           placeholders.end();
  }

  return false;
}
...
  // Any node referenced by one of the graph nodes should be part of the
  // Graph.
  for (const auto &N : nodes_) {
    for (size_t idx = 0, e = N.getNumInputs(); idx < e; ++idx) {
      auto &input = N.getNthInput(idx);
      // Verify each input of N.
      isValid &= verifyNodeInput(N, idx);
      bool foundNode =
          std::find(nodes_.begin(), nodes_.end(), *input) != nodes_.end();
      isValid &= expectCompareTrue(
          "Every node referenced by one of the graph nodes should be part of "
          "the graph",
          foundNode || isGraphStorageNode(input, this), true, &N);
    }
  }
...
```

The following test case passes without making any additional changes to the codebase:
```
/// Check that verification can detect that Storage nodes are being used by Functions in a Module that doesn't own the Storage nodes.
TEST(Graph, moduleLink) {
  ExecutionEngine EEA, EEB;

  auto &modA = EEA.getModule();
  auto &modB = EEB.getModule();

  auto *FA = modA.createFunction("FA");
  auto *FB = modB.createFunction("FB");

  auto *C = modA.createConstant(ElemKind::FloatTy, {1}, "C");
  auto *P = modA.createPlaceholder(ElemKind::FloatTy, {1}, "P", false);

  auto *AA = FA->createAdd("AA", C, P);
  FA->createSave("SA", AA);

  // These nodes use Storage nodes that reside in modA
  auto *AB = FB->createAdd("AB", C, P);
  FB->createSave("SB", AB);

  EXPECT_TRUE(modA.verify());
  EXPECT_FALSE(modB.verify());    // Module::verify calls Function::verify on all functions within the module, so this should fail
}
```

Does this meet your needs, @geoffberry?

**Comment by geoffberry** [comment]
@SplitInfinity Thanks for looking into this.  The situation we were running into was like that of the above test, but the Constants/Placeholders were in both modules lists.  So if you added the following code before verifying:
```
modB.addConstant(C);
modB.addPlaceholder(P);
```
I believe the `modB.verify()` would pass and this test would fail.

**Comment by SplitInfinity** [comment]
@geoffberry 

I attempted to address this in #3495. Please take a look and let me know your thoughts.

Interestingly enough, `~Module` will crash if a `Constant` or `Placeholder` is added to more than one `Module`. `~Module` attempts to `delete` all elements of `constants_` and `placeholders_`, so if a `Storage` is in more than one `Module`, it will be `delete`d twice.

**Comment by geoffberry** [comment]
@SplitInfinity this looks reasonable to me.  Perhaps you could also add checks in `addConstant`/`addPlaceholder` that check that the constant/placeholder have the proper ownership?

FWIW, I did a little digging and found the original case that led me to file this issue.  An older version of QuanitzaionTest was cloning a function from one module and adding it to a different module, leading to the situation described above.  The test has since been fixed to avoid this behavior.

**Comment by SplitInfinity** [comment]
@geoffberry 

What do you think of removing `addConstant/addPlaceholder` or making them `private` at the very least? That way it is impossible to create a `Storage` in one `Module` and add it to another? These functions aren't widely used either.
