### ISSUE TITLE
[Quantization] Fused 4-bit quantization support

### ISSUE THREAD

**Issue by beicy** [pytorch/glow#3463]
This issue is created to track fused 4-bit quantization support in Glow.  
The fused 4-bit quantization tensor is represented as follows:
```
|   .... int4 data ...       | scale | offset |                                                                                           
|num_of_input_columns * 0.5B |  2B   |   2B   | 
```
The plan is:
Step1 : implement an tensor fused 4-bit quantization/dequantization
Step2: Based on model requests, support fused 4-bit quantization/dequantization in Glow nodes.
Step3: implement  Glow fused4BitQuantizationNode (Optional).
Step4: 4-bits Quantized model testing.
cc @rdzhabarov @hyuen @bertmaher

**Comment by opti-mix** [comment]
Can it be closed now or is there anything to be done yet?

**Comment by beicy** [comment]
@opti-mix On my project side, the current support should be OK. If no more update from @jfix71 , I think it can be closed.

**Comment by jfix71** [comment]
Yeah think this is done.
