### ISSUE TITLE
downloading and compiling from zip files (offline compilation) 

### ISSUE THREAD

**Issue by GalMoore** [pytorch/glow#3485]
I'm trying to compile glow from zip. I've downloaded the main project and all submodules - I got the right tree for each and unzipped the contents in the existing folders in /test and /thirdparty.  When I try to compile I get CMake Error at CMakeLists.txt:148 "no google benchmark git submodule run git submodule". 

Any ideas what is missing or any suggestions how I could get glow to work on a computer that can not run "git clone" or run the "git submodule ..." command?

**Comment by StephenLeeUSTC** [comment]
I just wonder where is "no google benchmark git submodule" CMakeLists.txt file. Maybe you can list all the version of your env?
