### ISSUE TITLE
ONNX Scan operator support needed

### ISSUE THREAD

**Issue by ilyply** [pytorch/glow#3488]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Scan
Used in CRNN & LSTM models.
or What should I know if I intend to implement the operator by myself? Any hint is helpful, Thank you.

**Comment by jfix71** [comment]
Hi @ilyply -- it looks like this operator requires control flow. Glow does not currently support control flow (see #2738), so the best you can do here for now is unroll the graph body multiple times to some maximum length.

We have [this doc](https://github.com/pytorch/glow/blob/master/docs/NewOperators.md) describing how to implement an individual op, but it might not be very useful in this case -- for this op I believe you'll need to do something like iterate over the graph body and recursively call `ONNXModelLoader::loadOperator()` to create all of the required Nodes. The harder part here will actually be figuring out how to unroll it nicely like I mentioned above, and I think it would need to happen at model loading time, i.e. when you load a Scan in `ONNXModelLoader::loadOperator()`.

**Comment by ilyply** [comment]
I see. Thank you very much.
