### ISSUE TITLE
[GraphOptimizer] Fix bug in post-lowering optimizations for OpenCL

### ISSUE THREAD

**Issue by shajrawi** [pytorch/glow#3493]
As part of #3452 I created a layout verifier for the `OpenCL` backend. It caught a bug in our optimizations: see `smallConv` backend correctness test with the `OpenCL` backend for a tiny repro. We have a `NHWC` conv. which we turn into `NCHW` with a transpose of the inputs (which is fine). then the bug occurs when we optimize post lowering: `OptimizeTransposeIntoReshape` turns the transpose (of a placeholder) into a reshape and `DCE` removes the reshape. this is obviously incorrect because the placeholder is in `NHWC` format.

**Comment by nadavrot** [comment]
Great catch @shajrawi !

**Comment by shajrawi** [comment]
Found out why DCE deletes the Reshape node, at some point the conv. is no longer its user: it is done in the `OptimizeReshape` optimization, we do `Reshape(Constant) -> Constant'`. after the placeholder has been turned into a constant in placeholder->constant optimization.
This is fine, the verifier complained because it needs to know the layout of any constants / placeholders. The original constant had `NHWC` layout, and if we try to find out the layout of Constant->Conv. using Glow's canonical layout requirements then the new layout is `NHWC` too. `OptimizeRehsape` is not aware that it is running on `OpenCL` backend and as such it created a constant with `NHWC` instead.
