### ISSUE TITLE
[Question] Helper function to create external calls in LLVM

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#3494]
When creating bundles (AOT mode) we found useful to use an utility function to create calls to external functions (outside of libjit). The code is attached here:
[createExternalCall.txt](https://github.com/pytorch/glow/files/3585793/createExternalCall.txt)

The reason why we needed to make external calls was to specialize some kernels during LLVMIRGen with some optimized kernels which are compiled with other toolchains (other than the LLVM, e.g. gcc). Using the helper function creates some symbols in the bundle which are later resolved during link-time.

If you consider this function useful I can create a PR ... the main problem is that I cannot figure out how to create a unit test.

**Comment by opti-mix** [comment]
@mciprian13 

> When creating bundles (AOT mode) we found useful to use an utility function to create calls to external functions (outside of libjit). 
> The reason why we needed to make external calls was to specialize some kernels during LLVMIRGen with some optimized kernels which are compiled with other toolchains (other than the LLVM, e.g. gcc).

I have a couple of questions & comments about this:

- Why do you need to form the declaration of an external function during the codegen phase? Couldn't you just declare those functions in your libjit C files, e.g. like `extern int myExternalFunc(uint64_t a, float b, uint8_t *buf);`. I usually do it this way. Then you'd just need to lookup the function by name in the llvm::Module and you should be able to call it. Or may be you don't know in advance declarations of functions you are going to call and need to form them dynamically?

- If you do need to create such function declarations dynamically at the codegen phase, I'd suggest to introduce a helper that takes the name, the return type and the types of arguments as inputs and returns a llvm::Function object for such a function (either newly created or looked up in the the module). I'm not sure that deriving the types of arguments from the list of passed arguments like you do now is the best idea. Plus it does not allow you to declare a return type of the function. If you'd change your helper to work this way, we could include it into Glow.

**Comment by mciprian13** [comment]
I tried what you recommended: I put (e.g. in libjit_conv.cpp" the following line:
`extern void my_external_function(int32_t val);`

Then I put somewhere in the LLVMIRGen.cpp (e.g. convolution instruction) the following line;
    `F = llmodule_->getFunction("my_external_function");`
    `CHECK(F) << "Unable to load the function: my_external_function";`
    `auto *val = emitConstI32(builder, 123);`
    `createCall(builder, F, {val});`

It seems it cannot find the function (the CHECK() throws the error).

**Comment by opti-mix** [comment]
> Does the compilation flow throw away the unused declaration?

Yes, indeed. It seems like the clang compilation flow used to compile libjit into the LLVM IR throws away the unused declaration. To avoid this, you can add to libjit a dummy function that refers to the external function you need.
