### ISSUE TITLE
[Training] resnet-training example not working "Invalid slice size"

### ISSUE THREAD

**Issue by pfierek** [pytorch/glow#3497]
`resnet-training` example not working. Currently, when I run it, I get the "Invalid slice size" error. Full execution log:

    ./bin/resnet-training
    loading resnet50 model.
    Preparing for training.
    Differentiating graph.
    Compiling backend.
    Loading the CIFAR-10 database.
    Assigning images/labels bytes.
    Training - epoch #0 from total 32
    .resnet-training: ./glow/include/glow/Base/Tensor.h:551: void glow::Tensor::copyConsecutiveSlices(const glow::Tensor*, size_t): Assertion `onceSliceDim == dims().slice(1) && "Invalid slice size"' failed.
    Aborted (core dumped)

After a quick check, it looks like this: [4a3e29f](https://github.com/pytorch/glow/commit/4a3e29f1084714a2b6f36a39610aebc41543b295) commit has broken resnet50 training.

**Comment by SplitInfinity** [comment]
Closed by PR #3560

**Comment by SplitInfinity** [comment]
@putivsky 

Looks like this is still broken on CPU

**Comment by putivsky** [comment]
https://github.com/pytorch/glow/pull/3564
