### ISSUE TITLE
Unchecked Expected introduced in 3706588

### ISSUE THREAD

**Issue by chadrosier** [pytorch/glow#3505]
The below commit introduced a number of unchecked llvm::Expected errors:
Partitioner refactoring 3 (#3384)

https://github.com/pytorch/glow/blob/d12d6d09b6ab994df271231f5c4a5bab44c3dae5/tests/unittests/PartitionerTest.cpp#L252
Needs something like EXPECT_TRUE((bool)dagList);

https://github.com/pytorch/glow/blob/d12d6d09b6ab994df271231f5c4a5bab44c3dae5/tests/unittests/PartitionerTest.cpp#L346
IIUC, this is a negative test with an Error.  The bool operator for Expected sets Unchecked = true if there's an actual Error.  Therefore, this expect remains unchecked.

https://github.com/pytorch/glow/blob/d12d6d09b6ab994df271231f5c4a5bab44c3dae5/tests/unittests/PartitionerTest.cpp#L893
Same as previous.

https://github.com/pytorch/glow/blob/d12d6d09b6ab994df271231f5c4a5bab44c3dae5/tests/unittests/PartitionerTest.cpp#L922
Same as previous.

https://github.com/pytorch/glow/blob/d12d6d09b6ab994df271231f5c4a5bab44c3dae5/tests/unittests/PartitionerTest.cpp#L954
Same as previous.

This requires a build of LLVM with asserts enabled.

Would you mind taking a look @beicy?

**Comment by beicy** [comment]
Sure! Thanks! @chadrosier

**Comment by chadrosier** [comment]
Fixed in 16dd2fd.
