### ISSUE TITLE
RecommendationSystemTest should use HostManager instead of ExecutionEngine

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#3521]
RecommendationSystemTest currently uses ExecutionEngine, which is OK. But due to this fact the functionality of this test are a bit limited for the following scenarios:

- It is impossible to test with concurrent requests, because ExecutionEngine does not support concurrent execution

- It is impossible to test with heterogeneous partitioning, because ExecutionEngine supports only a single backend at a time. But heterogeneous partitioning use-cases are very important for bringing up new backends, which support only a subset of operations required by the full RecommendationSystemTest model.

Therefore, it would be better to use HostManager instead of ExecutionEngine to overcome the limitations mentioned above.

**Comment by opti-mix** [comment]
@gcatron 

> It is impossible to test with heterogeneous partitioning, because ExecutionEngine supports only a single backend at a time. But heterogeneous partitioning use-cases are very important for bringing up new backends, which support only a subset of operations required by the full RecommendationSystemTest model.

You closed this issue, but this bullet is not implemented yet. Would be nice to get this covered rather soon.

**Comment by gcatron** [comment]
Apologies for that, I meant to remove the fixes tag from the PR, Added #3556 to specifically track this, I'll try to get to it soon.

**Comment by gcatron** [comment]
Now that the config support is landed which should enable testing with heterogeneous devices,  re-closing the issue.
