### ISSUE TITLE
Optimize Transpose operator to Reshape

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#3532]
In this kind of situation the graph optimizer should replace the Tranpose operator with a Reshape (no op at run-time):
![image](https://user-images.githubusercontent.com/29785908/65244155-8b913180-daf2-11e9-9380-17f0683adef7.png)

**Comment by jackm321** [comment]
@mciprian13 thanks for raising this, would you be interested in adding this optimization?

**Comment by mciprian13** [comment]
I could do it although graph optimizations in Glow is something I have never studied in detail. I assume the steps for doing this would be:
- add a pass in the graph optimization pipeline
- add a unit test
Is there something else?
Thanks!

**Comment by jackm321** [comment]
@mciprian13 yes that's about it

**Comment by jfix71** [comment]
@mciprian13 We actually already have an optimization that should be doing this -- see `OptimizeTransposeIntoReshape` in the GraphOptimizer. 

If you have a repro for when this optimization isn't occurring when it should, it would be great to add as a unit test to GraphOptzTest along with a fix if you're interested in helping fix this. Thanks!

**Comment by mciprian13** [comment]
My bad ... I was running some older version of Glow which didn`t have the optimization you mentioned.
I will close this issue.
