### ISSUE TITLE
Can anyone provide complete detailed information of installing Glow in Ubuntu 16.0.4

### ISSUE THREAD

**Issue by ponnamsairam** [pytorch/glow#3571]
Please provide installation guide for Glow 
Ubuntu 16.0.4
I had installed LLVM 8.0.1 and Clang 8.0.1 but iam unable to configure glow in my system it will be more helpful if i get detailed info!

**Comment by jfix71** [comment]
Hi @ponnamsairam, we have instructions [here](https://github.com/pytorch/glow#ubuntu), though they may be a bit out of date. If you can follow those instructions and provide more information/logs on what is causing you issues we can help try to debug. Thanks!

**Comment by ponnamsairam** [comment]
Hi @jfix71 ,
I followed same instructions but the installation went hanging off my system 

/Desktop$ cd LLVM/
~/Desktop/LLVM$ cd glow/
~/Desktop/LLVM/glow$ cd build_Debug/
~/Desktop/LLVM/glow/build_Debug$ sudo ninja all
[10/107] Linking CXX executable bin/lenet-loader
 

At this step system is not responding can you guide me through this.

previously i got so many errors like ERROR: without a user defined constructor
ninja subcommand failed.

**Comment by jfix71** [comment]
Hm, I don't think you need sudo to run ninja. Can you try building a specific binary, for example `ninja InterpreterOperatorTest`, and then post  the build log?

**Comment by ponnamsairam** [comment]
i finally installed glow, Can you tell me how to run programs using glow?

**Comment by jfix71** [comment]
Great! We have a wiki section on how to run things [here](https://github.com/pytorch/glow#testing-and-running). Going to close this issue as it has been resolved.
