### ISSUE TITLE
Quantization seg falut

### ISSUE THREAD

**Issue by ezimmer9** [pytorch/glow#3708]
Hi,

I'm trying to quantize through glow quantization flow and get seg fault. 
the quantization flow works for me (few weeks ago) before i update to latest master.
even the example fr2en doesn't qauntize for me.
the cmd:  ./bin/fr2en -backend=CPU -dump-profile=test.yaml

thx

**Comment by jfix71** [comment]
@ezimmer9 Thanks for raising this issue -- I've put up a fix in #3712.
