### ISSUE TITLE
how to run inference form Pytorch side through glow on CPU backend?

### ISSUE THREAD

**Issue by zhaify** [pytorch/glow#3709]
hi I'm new to glow but  have used pytorch for 2 years, now I notice that glow has CPU backend with optimization for users, but I don't know how to run a pytorch model from pytorch through glow (want use glow's optimization), is there some do or someone help me?

I have compiled glow and successfully run `torch_glow/examples/resnet_example.py` but only use  `torch_glow.enableFusionPass()`.

**Comment by jackm321** [comment]
Hi @zhaify, I'm not sure if I understand the question.

If you want to switch from the Glow interpreter backend to the Glow CPU backend, you should be able to once #3698 is landed (or you can manually turn [this](https://github.com/pytorch/glow/blob/c8de4b061b5d23bbffff608238908a630f2a1c5a/torch_glow/src/PyTorchCommon.h#L45) to "CPU" now). Then you should be able to run that in the same way that you were able to run resnet_example.py with the interpreter backend.

Does that answer your question or no?

**Comment by zhaify** [comment]
@jackm321 that's what I want, thank you very much!

**Comment by zhaify** [comment]
i will close this issue.
