### ISSUE TITLE
Unable to locate package clang-8 llvm-8

### ISSUE THREAD

**Issue by billamiable** [pytorch/glow#3711]
Hi, I am using docker for mac to create Ubuntu 16.04 environment.

During installing the packages for glow, I encountered the problem of "unable to locate package clang-8. llvm-8". Have anyone also saw this error before?

Thanks!

**Comment by jfix71** [comment]
Hi @billamiable -- maybe a silly question, but do you have `clang-8` and `llvm-8` installed? If not you can follow the [instructions here](https://github.com/pytorch/glow#ubuntu) to install.

If they are installed then for some reason CMake isn't finding it. You need to point CMake to them, e.g. for LLVM you can use `-DLLVM_DIR=[path_to_llvm_install_dir]/lib/cmake/llvm`.

**Comment by billamiable** [comment]
Hi @jfix71, i fixed the problem by following instructions from [here](https://github.com/pytorch/xla/issues/589#issuecomment-482929272). Thanks!
