### ISSUE TITLE
Any benchmark compares with tvm on same tasks?

### ISSUE THREAD

**Issue by jinfagang** [pytorch/glow#3722]
Does there any benchmark compares with tvm and glow based on same hardware and same task?

**Comment by jfix71** [comment]
In our [arXiv paper](https://arxiv.org/abs/1805.00907) we compared CPU backend performance running Resnet50 and VGG19 against XLA and TVM. An important note from the numbers in the paper:

> Note that we did not use autotuning and improved schedules with TVM; we expect this would improve TVM’s performance
