### ISSUE TITLE
[Optimization] Transpose sink/optimization near Clip - optimization lost versus older Glow version

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#3742]
Currently there is a problem with optimizing away the Transpose around the lowered Clip Node.
All the MobileNe tv1/v2 models in ONNX format (which have Clip as non-linearity instead of Relu) are now full of Tranpose nodes (which is obviously not good).

**Can you please fix this?**

Asumming a section of a ONNX MobileNet v1 model which looks like this:
![image](https://user-images.githubusercontent.com/29785908/68316781-b21b2400-00c2-11ea-9ccb-87bc05fbbfb5.png)
The model compiled with Glow for the CPU backend with NEWEST Glow build looks like this:
![image](https://user-images.githubusercontent.com/29785908/68316910-e5f64980-00c2-11ea-973e-5d6ac629e7ad.png)
The model compiled with Glow for an OLDER (~April) Glow version looks like this:
![image](https://user-images.githubusercontent.com/29785908/68318248-2a82e480-00c5-11ea-802e-b9b7b2a7fb1d.png)

**Comment by mciprian13** [comment]
I`ll fix it.

**Comment by jfix71** [comment]
Thanks for catching and reporting this @mciprian13! Let's keep this open to track the issue and we can close it once we have the fix landed.
