### ISSUE TITLE
Missing BatchMatMul tests in FP16

### ISSUE THREAD

**Issue by nickgg** [pytorch/glow#3793]
We only test BatchMatMul in float, but support other types. Extend the unit tests to cover those cases.

**Comment by muhdmud** [comment]
Hi, is still up for grabs? if so i would like to try it out

**Comment by jfix71** [comment]
Hi @muhdmud -- we have a test for this now, but thanks for volunteering
https://github.com/pytorch/glow/blob/ac0b537ddda042a0724f0eeb55f23fe31ee678ed/tests/unittests/OperatorTest.cpp#L2565-L2570

**Comment by muhdmud** [comment]
no problem! @jfix71 thanks for sharing this, can see how the tests are being implemented 👍
