### ISSUE TITLE
[Debug] Option to dump all graph intermediate computations during inference as binaries

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#3845]
It would be nice to have this feature while using (for example) image-classifier.
For debugging purposes of course it would be nice for the tool to dump all the intermediate tensors during inference in separate named binaries.

**Comment by opti-mix** [comment]
@mciprian13 Could it be something like the current `-instrument-debug` option, which dumps all the intermediate tensors in the textual format?

**Comment by mciprian13** [comment]
OK I didn`t know about that.
I tried it, but I think it would be more useful with a couple of features:
- print every tensor in a separate file (and print the entire tensor because currently the large ones are not printed entirely)
- flexibility in the format (binary or text)

**Comment by opti-mix** [comment]
> I tried it, but I think it would be more useful with a couple of features:

PRs are welcome! :-)

> print every tensor in a separate file (and print the entire tensor because currently the large ones are not printed entirely)

Should be trivial to add.

> flexibility in the format (binary or text)

Should not be too hard too.

**Comment by mciprian13** [comment]
Solved in #4392. Closing this issue.
