### ISSUE TITLE
[Interpreter] Unexpected results when using ffast-math

### ISSUE THREAD

**Issue by et-nivard** [pytorch/glow#3856]
Current Release mode build uses ffast-math. This is producing unexpected results in some cases with respect to Debug mode compilation. There is a related PR going on but won't be fixing this issue  #2960 
One clear example that shows this kind of issues is the AdaptiveAvgPoolInst implementation. It contains this define:
`#define END_IND(a, b, c) (size_t) std::ceil((float)(((a) + 1) * (c)) / (b))`
When a = 2, c = 7, and b = 7, it outputs 4 instead of 3 provided last iteration loop runs on c. ffast-math will approximate (a+1)/b increment and cause small error that gets maximized by ceil function. 
Provided that Interpreter is usually regarded as a reference we could skip ffast-math flag at least when compiling this backend.

**Comment by jfix71** [comment]
@et-nivard Thanks for highlighting this -- I agree that we should disable fast-math for the Interpreter at the very least. Some people had objections in the past to disabling it for any backend, but the fact that it is a reference backend is another point in favor of disabling it.

**Comment by bertmaher** [comment]
Wow, I would not have expected -ffast-math to mess that expression up.  I'm also very suspicious of doing floating-point math on indices!  But anyways, here's my vote for nuking -ffast-math.

**Comment by nickgg** [comment]
@et-nivard does the change to #2960 work for you?

**Comment by et-nivard** [comment]
Yes, that should work. Thanks!
