### ISSUE TITLE
Tensor::isEqual() not aware of padding

### ISSUE THREAD

**Issue by et-nivard** [pytorch/glow#3898]
Current implementation of Tensor::isEqual() does not support tensors with padding. It just performs a plain traverse https://github.com/pytorch/glow/blob/master/include/glow/Base/Tensor.h#L817 without skipping padding positions. Also, it uses size() instead of actualSize() so it misses last elements when padding exists. An update is required to iterate over all valid elements while skipping pad-elements.

**Comment by opti-mix** [comment]
cc @shajrawi

**Comment by et-nivard** [comment]
In case it helps, these two tests should be passing and they are not because of this issue:

TEST(Tensor, differentAlignment) {
  Type Ty1(ElemKind::Float16Ty, {2, 1}, {4, 1});
  Type Ty2(ElemKind::Float16Ty, {2, 1}, {2, 1});
  Tensor T1(Ty1);
  Tensor T2(Ty2);
  auto T1H = T1.getHandle<float16_t>();
  auto T2H = T2.getHandle<float16_t>();
  T1H.at({0, 0}) = T2H.at({0, 0}) = 1;
  T1H.at({1, 0}) = T2H.at({1, 0}) = 2;

  EXPECT_TRUE(T1.isEqual(T2));
}

TEST(Tensor, sameAlignmentDifferentValues) {
  Type Ty1(ElemKind::Float16Ty, {2, 1}, {4, 1});
  Type Ty2(ElemKind::Float16Ty, {2, 1}, {4, 1});
  Tensor T1(Ty1);
  Tensor T2(Ty2);
  auto T1H = T1.getHandle<float16_t>();
  auto T2H = T2.getHandle<float16_t>();
  T1H.clear(0);
  T2H.clear(1);
  T1H.at({0, 0}) = T2H.at({0, 0}) = 1;
  T1H.at({1, 0}) = T2H.at({1, 0}) = 2;

  EXPECT_TRUE(T1.isEqual(T2));
}

**Comment by shajrawi** [comment]
Should be an easy fix - will take a look after I am done with some high priority stuff on my plate, probably after the holidays, but if someone else wants to take a crack at it in the meanwhile, feel free to do so.

**Comment by et-nivard** [comment]
Thanks @shajrawi for taking care of this.
