### ISSUE TITLE
calculateTensorViewOffset should take strides/padding into account

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#3915]
calculateTensorViewOffset currently does not take strides/padding into account and thus produces wrong offsets for tensors which are not densely packed and have non-trivial alignment requirements. This in turn leads to wrong results during the computation.

**Comment by SameerAsal** [comment]
@opti-mix  You mentioned there is a file to look at for this. can you please point it out.

**Comment by opti-mix** [comment]
@SameerAsal `calculateTensorViewOffset` is defined in `lib/LLVMIRCodeGen/AllocationsInfo.cpp`
