### ISSUE TITLE
Compilation problem due to type macro usage in DimType.h

### ISSUE THREAD

**Issue by Max-K-cadence** [pytorch/glow#3929]
Hi,

I'm having a build problem with the following commit

https://github.com/pytorch/glow/commit/d2794f48c2eeeab3fb279a55f29a43257059ef4a

Uses some type-qualifying macros like `PRId64` to define its own custom macos:

```
#define PRIdDIM PRId64
#define PRIuDIM PRIu64
```

These macros (`PRId64` and such) are defined in https://en.cppreference.com/w/cpp/header/cinttypes only if __STDC_FORMAT_MACROS is defined. I'm getting the following compilation problem:

```
glow/lib/LLVMIRCodeGen/BundleSaver.cpp: In member function â€˜void glow::BundleSaver::saveHeader(llvm::StringRef)â€™:
glow/include/glow/Base/DimType.h:41:17: error: expected â€˜)â€™ before â€˜PRIu64â€™
 #define PRIuDIM PRIu64
                 ^
glow/lib/LLVMIRCodeGen/BundleSaver.cpp:293:35: note: in expansion of macro â€˜PRIuDIMâ€™
         shapeStr += strFormat("%" PRIuDIM ", ", dims[idx]);
```

The reason of this is that at the point where `<cinttypes>` was *first* included to this file, __STDC_FORMAT_MACROS was not defined. As result, PRIu64 is not defined at this point.

Note than there is a precedent where __STDC_FORMAT_MACROS was defined explicitly:
```
./tests/googlebenchmark/src/benchmark_register.cc:37:#define __STDC_FORMAT_MACROS
```

Note: defining __STDC_FORMAT_MACROS  in DimType.h does not work, because there are multiple possible ways how `<cinttypes>` may come to the destination file. If `<cinttypes>` was first included before DimTypes.h was included, the macros like `PRIu64` will not be defined.

I can work around it by defining __STDC_FORMAT_MACROS in *above all includes* to BundleSaver.cpp, but it does not sound like the correct solution because we'll need to do it in each file that uses these macros.

So it seems that this commit messes with macros in a way it shouldn't. I'm not sure what is the correct solution for that.

**Comment by Max-K-cadence** [comment]
@pjaaskel as a patch author, could you please take a look?

**Comment by pjaaskel** [comment]
I think Glow now requires C++14, and starting from C++11 the macro should not be needed according to this: https://sourceware.org/bugzilla/show_bug.cgi?id=15366

Which compiler are you using? I believe the fix in your case would be to add -D__STDC_FORMAT_MACROS to the build command.

**Comment by Max-K-cadence** [comment]
The main page of Glow says it uses C++11: https://github.com/pytorch/glow. I use gcc 5.5.0 to build Glow.


I believe Glow should be able to build on this version without adding any extra options, it looks like a hack to me.

**Comment by pjaaskel** [comment]
If that's the case then the correct fix would be to detect if __STDC_FORMAT_MACROS is needed due to the faulty glibc by CMake and add it automatically. To my understanding DimType.h uses the macros correctly as per C++11, which should not require the __STDC_FORMAT_MACROS. I can fix this if I find a box with that bug in the glibc to test with.

**Comment by pjaaskel** [comment]
Can you test if https://github.com/pytorch/glow/pull/3998 fixes it for you?

**Comment by Max-K-cadence** [comment]
Yes it does, thanks!
