### ISSUE TITLE
[GraphOptz] Sink Transpose below Dequantize

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#3966]
Sink tranpose below dequantize in order to favor merging multiple transpose together like in the example below:
![image](https://user-images.githubusercontent.com/29785908/71816493-6f0e0a80-308b-11ea-9e80-f1af1a0be480.png)
Maybe this applies also for the Quantize node.

**Comment by UncleGene** [comment]
AFAIK Quantize is already covered

**Comment by mciprian13** [comment]
Thanks a lot for solving this!
Cheers😃
