### ISSUE TITLE
Versioning the GLOW

### ISSUE THREAD

**Issue by peter197321** [pytorch/glow#4045]
Hi guys,

I scan through glow code base I wonder if there some scheme/branching for it aka ver.x.x on tags or stable branch?
Let me understand how it works with GLOW.

Thank you.

**Comment by jfix71** [comment]
Hi @peter197321, we don't currently have any stable branches/tags/releases etc. This may be something we revisit in the future. I'd suggest just trying out latest master -- we have decent CI coverage so things shouldn't be too broken at any given time 🙂
