### ISSUE TITLE
caffe2.pb.h:1342:53: error:        only virtual member functions can be marked 'final'       ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;

### ISSUE THREAD

**Issue by bviyer** [pytorch/glow#4082]
Hello, I am getting the following issue when I am trying to build glow:

[ 39%] Building CXX object lib/Importer/CMakeFiles/Importer.dir/Caffe2ModelLoader.cpp.o
In file included from /Users/balaji.iyer/Documents/Glow/glow/lib/Importer/Caffe2ModelLoader.cpp:25:
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:17:2: error: 
      This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:18:2: error: 
      incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers. Please
 ^
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:19:2: error: 
      regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:319:61: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
                                                            ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:322:69: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
                                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:324:53: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:532:61: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
                                                            ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:535:69: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
                                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:537:53: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:683:61: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
                                                            ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:686:69: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
                                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:688:53: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:1079:61: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
                                                            ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:1082:69: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
                                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:1084:53: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:1337:61: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
                                                            ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:1340:69: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
                                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:1342:53: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
                                                    ^~~~~
/Users/balaji.iyer/Documents/Glow/b-glow/caffe2/proto/caffe2.pb.h:1482:61: error: 
      only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;

Any help is greatly appreciated! Removing the final seem to cause issues on other files.

**Comment by ponnamsairam** [comment]
hello @bviyer  make sure that you have installed libprotobuf-2.6.1 version throughout the installation

**Comment by bviyer** [comment]
> hello @bviyer make sure that you have installed libprotobuf-2.6.1 version throughout the installation

I have the following protobuf. Won't that be enough?
Warning: protobuf 3.11.2 is already installed and up-to-date

**Comment by jfix71** [comment]
Hmm. Not sure why that's an issue. I'm using 3.11.1 on my MBP and it's fine. Any way you can try that so we can try to narrow down the problem?
