### ISSUE TITLE
Add a flag to image-classifier for converting a model from fp32 into fp16, similar to glow_global_fp16 in Repro

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#4090]
It would be convenient if image-classifier would support the same functionality as Repro, so that you can run any fp32 NN model in fp16.

**Comment by opti-mix** [comment]
@kunmingho

**Comment by kunmingho** [comment]
This has already been implemented: "--convert-to-fp16" is the command line option for image-classifier for running all floating point computation in fp16.
