### ISSUE TITLE
Bool operations

### ISSUE THREAD

**Issue by ezimmer9** [pytorch/glow#4099]
Hi,

I have 2 bool Nodes (e.g {true , false ,true ,false}  ,  {true , true  , true , false})
How can i do the and (&) operation? (e.g {true , false , true , false }) 
How can i do the not (!) operation on 1 Node? {true , false ,true ,false } -> {false ,true ,false , true}

thanks

**Comment by jfix71** [comment]
Hi @ezimmer9 -- I don't think we have a straightforward way to do this right now 🙁. One hacky thing you could do is do this with integers and then use some select/comparison to convert them between bool and integer. The right thing to do is add functionality for bools for this, probably via new Nodes/Instructions.
