### ISSUE TITLE
Trouble about installing torch_glow

### ISSUE THREAD

**Issue by ybai62868** [pytorch/glow#4124]
Hello,

I have successfully compiled the Debug and Release version of Glow.
Now, I want to test the "torch_glow" with Python code. But when I install PyTorch by all kinds of ways, it always has some questions about it.
Can you tell me the specific version of Pytorch installed if I want to use "torch_glow" successfully?
Using pip or conda or from soucre?

Thanks

**Comment by jfix71** [comment]
CC: @jackm321

**Comment by jackm321** [comment]
Hi @ybai62868,

The method that normally works the best is conda installing PyTorch nightly build.
Let me know if that works for you or if not what error you're running into.

**Comment by ybai62868** [comment]
Hello @jackm321 
I follow your instructions and install PyTorch nightly build by conda.
Using the python setup.py install

It has the following error messages.


[ 80%] Built target HyphenTest
[ 81%] Built target CPUJITTest
[ 82%] Built target CPUOperatorTest
[ 82%] Built target InterpreterDeferredWeightLoaderTest
[ 84%] Built target InterpreterBackendCorrectnessTest
[ 85%] Built target InterpreterTraceEventsTest
[ 86%] Built target CPUGradCheckTest
[ 86%] Built target CPUMLTest
[ 88%] Built target CPUTraceEventsTest
[ 88%] Built target InterpreterOperatorGradTest
[ 89%] Built target CPUBackendTest
[ 90%] Built target CPUOperatorGradTest
[ 92%] Built target CPUBackendCorrectnessTest
[ 93%] Built target InterpreterOperatorTest
[ 93%] Built target GraphOptzTest
[ 94%] Built target CPUDeviceManagerTest
[ 95%] Built target InterpreterBackendTest
[ 96%] Built target InterpreterDeviceManagerTest
[ 96%] Built target Repro
[ 96%] Built target InterpreterMLTest
[ 96%] Built target CPUTypeAToTypeBFunctionConverterTest
[ 97%] Built target InterpreterGradCheckTest
[ 97%] Built target CPURecommendationSystemTest
[ 97%] Built target InterpreterTypeAToTypeBFunctionConverterTest
[ 98%] Built target InterpreterTensorLayoutTest
[ 98%] Built target CPUDeferredWeightLoaderTest
[ 98%] Built target InterpreterRecommendationSystemTest
[100%] Built target GlowOnnxifiManagerTest
dst /root/glow_2/glow/torch_glow/build/lib.linux-x86_64-3.7/torch_glow/_torch_glow.cpython-37m-x86_64-linux-gnu.so
error: can't copy '/root/glow_2/glow/build/torch_glow/src/_torch_glow.cpython-37m-x86_64-linux-gnu.so': doesn't exist or not a regular file

**Comment by dinkdeep** [comment]
Hi ybai62868  were you able to build the glow/glow_torch , I am getting llvm undefined reference errors too  while building the torch_glow.

**Comment by ybai62868** [comment]
@dinkdeep 
Hi,
I didn't solve this problem. Looking forward to hearing from you.

**Comment by dinkdeep** [comment]
Oh yes Please look at the issue #4211 
Mneily had suugested to build with these versions 
glow: 0546c76
pytorch: bc6005281b5eb1e82f0af2652c157091052dd6ad
I'm currently using: glow master 
with pytorch: bc6005  and both built fine and was able to run couple of applications .
In addition I saw 2 minor errors in libjit.cpp with latest master of glow some how commented them and kept moving 
And also you may have to build LLVM 9.0 with RTTI ON (must ) 

+FAILED: cd /home/ddeepani/Work/dkd/training/pyglow/glow/tests/unittests && /usr/bin/clang++ -emit-llvm -c -o /home/ddeepani/Work/dkd/training/pyglow/glow/build/tests/test_libjit.bc test_libjit.cpp
+test_libjit.cpp:21:1: error: unknown type name 'size_t'; did you mean '__gnu_cxx::size_t'?
[1/73] cd /home/ddeepani/Work/dkd/training/pyglow/glow/lib/Backends/CPU && /usr/bin/clang++ -c /home/ddeepani/Work/dkd/training/pyglow/glow/lib/Backends/CPU/libjit/libjit.cpp -std=c++14 -ffast-math -fno-finite-math-only -g -I/home/ddeepani/Work/dkd/training/pyglow/glow/include -emit-llvm -O0 -o /home/ddeepani/Work/dkd/training/pyglow/glow/build/lib/Backends/CPU/CPURuntime/libjit.o
FAILED: lib/Backends/CPU/CPURuntime/libjit.o
cd /home/ddeepani/Work/dkd/training/pyglow/glow/lib/Backends/CPU && /usr/bin/clang++ -c /home/ddeepani/Work/dkd/training/pyglow/glow/lib/Backends/CPU/libjit/libjit.cpp -std=c++14 -ffast-math -fno-finite-math-only -g -I/home/ddeepani/Work/dkd/training/pyglow/glow/include -emit-llvm -O0 -o /home/ddeepani/Work/dkd/training/pyglow/glow/build/lib/Backends/CPU/CPURuntime/libjit.o
/home/ddeepani/Work/dkd/training/pyglow/glow/lib/Backends/CPU/libjit/libjit.cpp:1034:31: error: variable length array of non-POD element type '(anonymous namespace)::ClassBox'
ClassBox selectedIndices[numBoxes];
^
/home/ddeepani/Work/dkd/training/pyglow/glow/lib/Backends/CPU/libjit/libjit.cpp:1035:30: error: variable length array of non-POD element type '(anonymous namespace)::ClassBox'
ClassBox potentialBoxes[numBoxes];
Some how for the time being i commented the code in "libjit_nms_generic" to keep moving an added std:: before size size_t

**Comment by ybai62868** [comment]
@dinkdeep  Thanks a lot!
My buddy!

**Comment by dinkdeep** [comment]
@ybai62868  My pleasure, you are welcome  .

**Comment by ybai62868** [comment]
@dinkdeep 
Hi, buddy! 
Can we make friends? I am also a new player for glow and I want to get a good understanding of glow. Maybe we can learn it together. Can you tell me what's your email? We can discuss lots of questions together. 
Thanks,
Yang

**Comment by dinkdeep** [comment]
Hi Yang, 
Sure to be honest I am also very new to glow and Machine Learning and AI but am trying to learn, Yes it would be fine if we can discuss  and share our findings  and enhance the understanding.
Please do find the email id as  dkdeepani@gmail.com .

**Comment by dinkdeep** [comment]
Enhance the understanding of Glow, torch_glow, and pytorch, specifically I am interested and inclined towards the Training Part.
