### ISSUE TITLE
[GraphOptzTest] Verification failure for some padding tests

### ISSUE THREAD

**Issue by jfix71** [pytorch/glow#4128]
In https://github.com/pytorch/glow/pull/4127 I added a verification check for the final module at the end of GraphOptzTest. This is causing a few tests to fail: 

- fusePadIntoConv
- fusePadIntoConvNeg1
- fusePadIntoConvNeg2

@tlepley-cadence @vuzelac-cadence Since you guys added these, can someone on your end look into fixing them, based on top of https://github.com/pytorch/glow/pull/4127? Thanks!

**Comment by tlepley-cadence** [comment]
@jfix71 just fixed it here: #4137
