### ISSUE TITLE
[Glow build] Error when building with "-DGLOW_BUILD_TESTS=OFF"

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4135]
@SameerAsal After the commit #4053 the Glow build fails when disabling the tests via the CMake option "-DGLOW_BUILD_TESTS=OFF":
- When the tests are disabled the "BackendTestUtils" library is not build. But this is a dependency for the "network-debugger" application which fails to link.

Therefore you should put a condition in the CMake to build the "network-debugger" only when the tests are also build (or remove the "BackendTestUtils" dependency entirely).

**Comment by SameerAsal** [comment]
Thanks for report this!

NetworkDwbugger shouldn't even need BackendTestUtils IIUC. I'll update the dependencies.

**Comment by mciprian13** [comment]
Thanks for fixing this so quickly!
Cheers!
