### ISSUE TITLE
Example MNIST erroring on assertion

### ISSUE THREAD

**Issue by christywarden734** [pytorch/glow#4210]
Hello!

I am trying to run the MNIST example and am running into an error here: https://github.com/pytorch/glow/blob/master/examples/mnist.cpp#L170

With the error being 

> Assertion failed: (indices.size() <= strides.size() && "Invalid number of indices"), function getFlattenedOffset, file /Users/christywarden/differentiable/thirdparty/glow/include/glow/Base/Tensor.h, line 967.
Abort trap: 6

I added a statement right before the assertion: 
`if (indices.size() > strides.size()) {
    LOG(INFO) << "Indices size: #" << indices.size();
    LOG(INFO) << "Strides size: #" << indices.size();
  }`

which printed 

> I0224 11:32:14.609498 138560960 Tensor.h:968] Indices size: #2
I0224 11:32:14.609501 138560960 Tensor.h:969] Strides size: #2

before erroring. 

Any help understanding what could be going on would be greatly appreciated :) Thanks so much!

**Comment by maxwillzq** [comment]
change this line https://github.com/pytorch/glow/blob/0546c76b95cfd2a312ae3b6ac1955f1e4501f1f3/examples/mnist.cpp#L170

to 
```c++
auto correct = label.getHandle<sdim_t>().at({0});
```

because label is 1D tensor

**Comment by jfix71** [comment]
@christywarden734 Yes, as @maxwillzq noted this should be changed. Would either of you like to put up this easy fix?

**Comment by maxwillzq** [comment]
@jfix71  can you assigned to me? I can fix it?

**Comment by maxwillzq** [comment]
add PR https://github.com/pytorch/glow/pull/4598 to fix this small bug

**Comment by maxwillzq** [comment]
My fix #4598 already solve this problem. It passes the test.  However, I have no authority to merge code. see #4598
