### ISSUE TITLE
Bundle Saver issue with multiple functions

### ISSUE THREAD

**Issue by ayermolo** [pytorch/glow#4214]
This is exposed by testSaveMultipleFunctions when asserts are enabled in LLVM.

Symptom is assert in LLVMIRGen::emitConstOffsetsArray when old global is being replaced by new global. It asserts because size of globals are mismatched.

Looking briefly at it seems like root issue is that Weights/allocas are keep being "appended" to valueNumbers data structure in allocationsInfo_. It's a map but valueIdx keeps getting incremented which is then used in emitConstOffsetsArray to find maxOffset.  

This happens in BundleSaver::performBundleMemoryAllocation() when it calls allocationsInfo_.allocateActivations(F);

Haven't looked further. Not sure if this appending behavior is intended or data structure needs to be cleared between each function. Since I don't know what assumptions are for bundlesaver with multiple functions.

**Comment by opti-mix** [comment]
@ayermolo Thanks for the bug report! I've seen this issue before and thought I had fixed it. But apparently this is not the case! ;-) I'll see how to fix this.

**Comment by ayermolo** [comment]
@opti-mix thanks. Sorry just did the most superficial dive.

**Comment by opti-mix** [comment]
@ayermolo Could you please check if #4215 fixes the issue for you?
