### ISSUE TITLE
[torch_glow] Need method for determining the version of PyTorch tracked by Glow

### ISSUE THREAD

**Issue by mneilly-et** [pytorch/glow#4216]
It isn't clear what version of PyTorch is tracked by Glow. A mechanism for indicating the currently supported version would be helpful as simply pulling the latest versions of both glow and pytorch often does not work.

**Comment by dinkdeep** [comment]
Yes this is true atleast glow/torch_glow should have a version of last working pytorch, as  pytorch seems very fast moving target and allied developers are left clueless with undefined linker errors

**Comment by jackm321** [comment]
torch_glow tracks against master for pytorch and glow. Despite having a couple layers of testing for this it does get broken fairly frequently unfortunately. I'm not sure that we could easily version torch_glow without also versioning Glow however.

**Comment by mneilly-et** [comment]
It looks like the build status badge in the README is for Travis not CircleCI. IIUC, CircleCI does provide badges too but it isn't clear to me if there is a "last passing" badge and if that would be able to provide the hashes for glow and pytorch for the last passing build. If so, that would be useful.

**Comment by jackm321** [comment]
@mneilly-et thanks for pointing that out, #4319 should fix that. For a last passing badge, I don't see anything available for it but there's the circleci history linked from that badge

**Comment by mneilly-et** [comment]
Thanks @jackm321. It looks like selecting the last successful PYTORCH build readily reveals the glow hash and the pytorch hash can be found under the Build section by searching for "^Copying torch.egg-info". It'd be great if the info could be obtained via the REST API but this is very helpful.
