### ISSUE TITLE
[Bundle][Feature] Error handling in LIBJIT with a return error code.

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4263]
This is more like a nice to have feature of having LIBJIT functions to do some error handling
and dropping a value of 0 (no error) vs something else to report problems.
For example the main bundle entry function could have the following prototype:
`uint32_t resnet50(uint8_t *constantWeight, uint8_t *mutableWeight, uint8_t *activations);`
that is to return an error code if something happens.
For the main LIBJIT math functions this is not necessarily very useful but for custom LIBJIT functions (e.g. DMA transfers, Remote Procedure Calls, etc) this is extremely useful.

The main bundle function could have a local variable `uint32_t errorCode` initialized with 0 and maybe have an option in LLVMIRgen for `createCall` called `errorCheck` which does bitwise OR between `errorCode` and the `uint32_t` returned by the function (or this could be done unconditionally by `createCall` for all the libjit functions which return an `uint32_t`). Lastly the bundle would return `errorCode`.

**Comment by opti-mix** [comment]
@mciprian13 

Implementing this feature shouldn't be too hard. But I'd like to understand a bit better your intent here.

1) Do you suggest all kernels/libjit functions should return an error code that is 0 (no-error) by default? Or do you suggest just some of them may return error codes?

2) IIUC, you want to perform some error checking inside the main function of the bundle to propagate the errors if needed. I suspect you want to return the error code as soon as it was returned by a libjit function? Or do you plan to collect all errors (by doing `errorCode |= libjitCall(...)`) and then return `errorCode` at the end.

3) Do you suggest to bail on any error or only on a subset of expected errors specified by the client?

**Comment by mciprian13** [comment]
@opti-mix I thing it would make sense something like this:
```
uint32_t main(uint8_t *constantWeight, uint8_t *mutableWeight, uint8_t *activations) {

  // Call kernel which has a uint32_t return type in its API.
  if (uint32_t errCode = kernel1(args)) {
    return errCode;  
  }

  // Call kernel which does not have a return in its API.
  kernel2(args);

  return 0;
}
```
So to respond to your questions:
1. I think we should NOT force that all the kernels to have a return type. After all for 99% of the kernels (math related) the return code is not necessary (and we don't want to modify all the current libjit kernel APIs if not needed). The procedure which generates the function call could inspect the function API and:
   - if the kernel has a `uint32_t` return type then it generates the code to bail out immediately if the return code is different than 0.
   - if the kernel does not have a return type then it generates a simple call.
   - I'm not sure we need or should allow other return types other than `void` and `uint32_t`

2. I don't need other error checking mechanism other than the auto-generated code to bail out immediately if the returned error code (if any) is different than 0. I'm not sure why I mentioned the bitwise OR'ing stuff ... this simple mechanism is sufficient since it does not make sense to go on with the execution if at least one kernel returned an error. I'm not sure we need something more complicated like critical vs non-critical (recoverable) errors for now.

3. Bail out any error is ok.

In addition it would be a nice feature to have a separate header file called (let's say) `libjit_errors.h`
with a potential content like this:
```
#define GLOW_ERROR_BUFFER_OVERFLOW   1
#define GLOW_ERROR_NAN_ENCOUNTERED 2
```
which can be used by the libjit kernels and simultaneously is automatically printed in the auto-generated header file by the `BundleSaver` something like this:
```
// Bundle error codes.
#define GLOW_ERROR_BUFFER_OVERFLOW   1
#define GLOW_ERROR_NAN_ENCOUNTERED 2

// Bundle entry point (inference function)
uint32_t main(uint8_t *constantWeight, uint8_t *mutableWeight, uint8_t *activations);
```
What do you say?

**Comment by opti-mix** [comment]
@mciprian13 Thanks for clarifications, I think I understand what you are after and it totally makes sense.
