### ISSUE TITLE
CPU Backend supports Arm or RISC-V?

### ISSUE THREAD

**Issue by ybai62868** [pytorch/glow#4325]
Does the CPU backend of Glow support ARM or RISC-V?

**Comment by opti-mix** [comment]
Yes, the CPU backend supports any architecture that is supported by the LLVM build it was linked against.

**Comment by mciprian13** [comment]
You can check this document [AOT.md](https://github.com/pytorch/glow/blob/master/docs/AOT.md) which explains how to build a model for a given architecture (you have the flags required for different ARM architectures).
For RISC-V I think the supports comes from LLVM 9.0 (Glow currently operates with LLVM 8.0).

**Comment by opti-mix** [comment]
> For RISC-V I think the supports comes from LLVM 9.0 (Glow currently operates with LLVM 8.0).

Glow can be built with LLVM 9.0 just fine. Some users have been using this setup for a while.

**Comment by ybai62868** [comment]
Hi, @opti-mix  @mciprian13 
Thanks for your information. I have followed the instructions posted on the AOT.md and it can run glow bundles successfully. I built glow with LLVM@7 so that means my CPU backend doesn't support the RISC-V. If I re-built glow with LLVM@9, my CPU backend will support the RISC-V?

**Comment by opti-mix** [comment]
> If I re-built glow with LLVM@9, my CPU backend will support the RISC-V?

Yes, RISC-V will be supported once you build using LLVM >= 9.0
