### ISSUE TITLE
Different outputs between Glow and ONNXruntime

### ISSUE THREAD

**Issue by leejaymin** [pytorch/glow#4331]
I ran [Yolov2](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov2-coco) model on Glow and ONNXruntime. I got different outputs between Glow and ONNXruntime. To pinpoint why it is different, I ran first layer (conv+batch+activation+maxpooling) on Glow and ONNXruntime respectively. As shown in the following screenshot, each value shows 1~2 bit differences.

I would like to know whether little difference would be allowed.

![image](https://user-images.githubusercontent.com/1924507/77231861-e100e500-6be0-11ea-96f6-e7edc378c23c.png)

**Comment by mciprian13** [comment]
I am not sure why do you expect to obtain exactly the same results (bit exactness). Assuming the model is floating-point you should note that, for example, floating-point addition is NOT associative. Here`s an exercise for you:
- in either C, Python etc, define an array of 1000 float32 random values. Compute **sum1** as being the sum of the array by summing the values in the increasing order of the index (add array[0] then array[1] and so on). Then compute **sum2** as being the sum of the same array by summing the values in the decreasing order of the index (reverse order) (add array[999] then array[998] and so on). By the end you should compare **sum1** and **sum2** and see that these sums are not exactly the same (bit exact).

Back to your question, bit exactness between 2 framework for floating point operation can exist only if the backing implementations are EXACTLY the same (and not just mathematically the same). Glow might just sum some operands in some other order than OnnxRuntime (mathematically is the same but floating-point wise is not the same).
If this response is satisfying for you, you should close this issue!
Thanks!

**Comment by leejaymin** [comment]
@mciprian13 Thank you for your kind comments. Your answer helps me to figure out why two outputs are different. Along with your advice, I implemented the `sum` of Float array and replicated those outputs. Therefore, I close this issue.

![image](https://user-images.githubusercontent.com/1924507/77303449-56ca9500-6d36-11ea-815d-43fdf92863d1.png)

Thanks.
