### ISSUE TITLE
[InstrGen] Add capability to query operand name

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4396]
Modify InstrGen in order to have the capability to query the name of a positional operand:
- For example `instr.getOperandName(2)` would retrieve `Filter` for a convolution instruction.

The method should be accessible from the base class for Instruction (when iterating through instructions we should be capable to call the method without upcasting the objects). This would be useful for debugging/printing procedures.

**Comment by mciprian13** [comment]
@opti-mix Would you be interested in doing this? I`m not sure what is the proper way to do it in terms of memory/run-time overhead, whether to modify the definition of the InstructionOperand type to include a string, etc.

**Comment by SameerAsal** [comment]
Hi, 

one comment on this:

> For example node.getOutputName(0) would retrieve Result for a convolution node.

IIUC you can get  the output name of a GLOW node using: 

 `node.getOutputName(idx)` Look at this code snippet https://github.com/pytorch/glow/blob/00c4b150b657ca0de288ba14bec25531d111ffb8/tools/Debugger/NetworkComparator.cpp#L166:

```
void IntermediateLayerComparator::hookSingleNodeInPlace(
    Node &node, std::list<SaveNode *> &saveNodes,
    std::list<Placeholder *> &hookPlaceholders) {
  std::string layerName = node.getName();
  for (unsigned i = 0; i < node.getNumResults(); ++i) {
    std::string saveName = node.getOutputName(i);
    saveName += "_" + layerName + "_hook";
    SaveNode *save =
        node.getParent()->createSave(saveName, node.getNthResult(i));
    saveNodes.emplace_back(save);
    hookPlaceholders.emplace_back(save->getPlaceholder());
  }
}
```

**Comment by mciprian13** [comment]
Ok thanks for the info! I`ll update the description to reflect this only for the Instructions.
