### ISSUE TITLE
Provide pass pipeline mechanisms for low-level IR passes

### ISSUE THREAD

**Issue by opti-mix** [pytorch/glow#4404]
Glow provides pass pipeline mechanisms for graph-level optimizations and transformations. We've got some requests to provide similar mechanisms for low-level IR passes.

Ideally, it would be nice to have a general pass pipeline mechanism that can work with any kind of IR, e.g. with backend-specific IRs as well.

It seems like an easy way to achieve it would be to copy & adjust the existing graph-level pass pipeline machinery for low-level IR pass pipelines. But it may introduce a lot of code duplication.

Alternatively, one could try to generalize the existing  pass pipeline machinery  to support any kind of passes and IRs (e.g. by parameterizing pipeline-related classes using template parameters representing the IR related types, etc). This would be more future-proof, but may eventually complicate the code and also introduce some linking issues or unwanted dependencies.

**Comment by opti-mix** [comment]
cc @jfix71 

IIRC, you played with similar ideas when you worked on the pass pipeline mechanisms for graph-level optimizations. Could you remind about the issues you were running into?

What is your overall opinion about moving forward on this topics? What would be the best way?

**Comment by jfix71** [comment]
Added my comments to #4411, sorry for the delay!
