### ISSUE TITLE
Retrieving LLVM IR using glow

### ISSUE THREAD

**Issue by shipperzhang** [pytorch/glow#4434]
Is it possible to get LLVM intermediate representation (.ll) files or binary of compiled model using glow? If so, how can it be done? Are there any existing examples or tutorials?

**Comment by jfix71** [comment]
Hi @shipperzhang -- we have a couple cl options `-dump-llvm-ir` and `-dump-llvm-asm` to see the LLVM IR and resulting assembly, assuming you're using an LLVM-based backend such as the CPU backend (i.e. use `-backend=CPU`). FYI these options will just print to stdout.
