### ISSUE TITLE
[Build] Optional Folly usage

### ISSUE THREAD

**Issue by aturetsk** [pytorch/glow#4467]
I grep'ed the code, and the only place I see Folly used in the generic part of Glow is ThreadPool:
```
Runtime/Executor/ThreadPoolExecutor.cpp:                  std::make_shared<folly::NamedThreadFactory>(name)),
Support/CMakeLists.txt:                        folly_jemalloc
Support/ThreadPool.cpp:#include "folly/system/ThreadName.h"
Support/ThreadPool.cpp:          folly::setThreadName(name);
```

That's not much and from the looks of it not every Glow use case might need that. Are there any plans to use Folly somewhere else in Glow?

Otherwise, is it possible to restrict Folly usage in the generic part of Glow to ThreadPool and make it an optional dependency? I wonder if it's possible to have something simple like SingleThreadExecutor (not using ThreadPool), and if Glow is compiled with a flag ENABLE_THREADPOOL_RUNTIME=OFF runtime would fallback to it? I'm not very familiar with DeviceManager/ThreadPool, but from what I see in the code ThreadPool usage is very local, so it should be possible to substitute.

Does this sound doable/reasonable?

**Comment by aturetsk** [comment]
@jfix71, @opti-mix, @bertmaher, any thoughts  on this?

**Comment by jfix71** [comment]
If you can get it to work correctly then I think it's reasonable. I know @bertmaher tried quite a bit to restrict usage of folly but couldn't get it to work. Also CC: @gcatron in case some any potential runtime refactoring we're considering has an impact here/would make folly easier to keep out of the rest of the codebase.

**Comment by gcatron** [comment]
I think it will be used more widely through the Runtime going forward, another example just added is #4482, so it may be difficult.

**Comment by aturetsk** [comment]
@jfix71, @gcatron, thanks for your feedback. I played a bit with this and didn't find any easy way to remove folly dependency. Taking into account that folly is going to be used more, to achieve this we'd need to have non-folly based implementation for all runtime interfaces. I don't this is something we want to do. Closing the issue.
