### ISSUE TITLE
[AvgPool] Add flag to not include pads when normalizing

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4565]
The current implementation of AvgPool always normalizes by the window size regardless of whether the window includes padding or not. Even the ONNX format specifies a boolean flag **count_include_pad** which defaults to 0 which means that the normalization is done by the number of samples within the window excluding pads (this means the current implementation of AvgPool does not comply to the ONNX definition).
For generality we should have a flag **countPads** which should allow both flavors of the implementation.

**Comment by 842974287** [comment]
Hi, I've created a PR for this issue. I'm new to Glow Project. Feel free to leave any comments!

**Comment by mciprian13** [comment]
This was done in #4915. Closing this issue.
