### ISSUE TITLE
Loss of Operator Names

### ISSUE THREAD

**Issue by ksaurabh-cadence** [pytorch/glow#4600]
We have noticed for certain models where there is a `__ ` present in operator names e.g Conv__435 gets renamed by glow to Conv__734 ( expected was Conv__435__1 or  Conv__435__2 or so on).  This kinds of makes it hard to analyze the intermediate graphs, correlating it to the original model.  It seems that the root cause for this issue is that glow treats `__` as a kind of delimiter added by glow (wrong to assume that input model will not have `__`), but can't distinguish it from `__` present in the original names. So it always strips the last `___` and puts it's own numbering messing up the original names. 

One way I could think to avoid this, is to append `__` to the original names in loadOperator, so the stripping of last `__` will leave the original name unchanged.

Any simple ideas / solutions for this issue that folks at glow can provide?

**Comment by jfix71** [comment]
Appending `__` when we import seems sane to me. Maybe would make the most sense to check the string for `__[0-9]+$` and only append `__` in such cases.

**Comment by saurabh-shandilya** [comment]
Since we have an agreement, are you expecting me to create a PR or folks at FB will be doing this? :-)

**Comment by ksaurabh-cadence** [comment]
Since we have an agreement, are you expecting me to create a PR or folks at FB will be doing this? :-)

**Comment by jfix71** [comment]
We haven't encountered this as an issue so there's not much pressure/motivation on our end for someone to do it 🙂 -- I can leave it as a good first issue in case someone else wants to handle it.

**Comment by ksaurabh-cadence** [comment]
I will be submitting a PR.

**Comment by ksaurabh-cadence** [comment]
PR created https://github.com/pytorch/glow/pull/4640
