### ISSUE TITLE
A new GLOW backend

### ISSUE THREAD

**Issue by peter197321** [pytorch/glow#4709]
Hello all,

I am a newbie to GLOW development enviremont, Id like to know if there are some examples and doc for developing a new backend of GLOW e.g. NPU accelerator?
If so, please can you point me or link appropriate documentation?'

Thank you.

**Comment by jfix71** [comment]
Hi @peter197321 -- I don't think we have a good current example in code. We had a previous PR which intended to be an example in https://github.com/pytorch/glow/pull/3991, but it never landed and is probably a bit out of date by now. Still, probably worth taking a look and reading the discussion there, including looking at `docs/Backends.md`.
