### ISSUE TITLE
Question about Test #53 in the Unit test

### ISSUE THREAD

**Issue by jinz2014** [pytorch/glow#4757]
Test #53: OpenCLHostManagerTest .................***Failed  390.04 sec

I don't know if others observe the failure of the test. All other tests pass!

Thanks

**Comment by jfix71** [comment]
Hi @jinz2014 -- I don't see any issues on my macbook for this test. Perhaps it's a platform-dependent issue. Do the other OpenCL tests work for you, e.g. OpenCLOperatorTest? Anyway, if you figure out the issue please report back.
