### ISSUE TITLE
[GraphOptz] Eliminate Slice nodes that slice across the entire input

### ISSUE THREAD

**Issue by Squadrick** [pytorch/glow#4759]
Currently, if a single Slice node cuts across the entirety of the input, it not removed. A simple fix would be to remove the Node entirely:

```
PH[10, 10, 10] -> SLICE[{0, 0, 0}..{10, 10, 10}] -> OUTPUT
```
should be converted to:
```
PH[10, 10, 10] -> OUTPUT
```

This optimization case would arise after some other optimizations that replace multiple consecutive slices with a single merged slice.

Related to #4628 
cc @jfix71

**Comment by Squadrick** [comment]
Correction: This happens in the pipeline by `EliminateNoop`. I wasn't able to optimize away the merged slice because of the order of operations in the pipeline runs `EliminateSliceConcat` at the very end followed by a dead code removal. 

https://github.com/pytorch/glow/blob/c095b25748e640cc5aabcf27d6970b127b57e3ca/lib/Optimizer/GraphOptimizerPipeline/FunctionPassPipeline.cpp#L168-L171

Shouldn't there by a final `EliminateNoop` after all the optimizations? 

```
EliminateNoop;
// other optimzations
EliminateNoop;
RemoveDCE;
```

**Comment by jfix71** [comment]
@Squadrick Good catch. Yeah, this is just a phase ordering problem, no big deal to add another pass at the end if it's helpful since optimization happens pretty quickly and that's a pretty safe pass.
