### ISSUE TITLE
[Convolution] Add support for non-square dilation

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4768]
Currently the convolution operators have only one `dilation` scalar parameter whereas the more generic definition should have one dilation value for each axis (2 values for Conv2D, 3 values for Conv3D, etc).

**Comment by 842974287** [comment]
So sorry I forgot to mention the PR here. Got a PR https://github.com/pytorch/glow/pull/4975 for this issue and is already closed early today.

**Comment by mciprian13** [comment]
This was solved in #4975. Closing this issue.
