### ISSUE TITLE
[GraphOptz] Fold Min + Max into Clip/Relu

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4769]
Add logic to fold Min + Max nodes (or Max + Min nodes) into Clip or Relu nodes.
Backends can then opt to lower them again or not when it is desired to provide atomic implementations or to fuse Clip/Relu into Convolution etc.

**Comment by 842974287** [comment]
@mciprian13 I've put up a PR for this https://github.com/pytorch/glow/pull/5013. Feel free to leave some comment!
