### ISSUE TITLE
[DottyPrinter] Print less values for Node vector member

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#4805]
For a backend specific node I end up with the following graph plot:
![image](https://user-images.githubusercontent.com/29785908/90042495-6fcae700-dcd3-11ea-82cb-7c89e26970b0.png)
For the `FilterScales` node vector member it would be nicer if only a couple of values would be printed.

**Comment by 842974287** [comment]
I've create a pull request https://github.com/pytorch/glow/pull/4903 for this issue. It's my first time working on Glow. Feel free to leave some comments!

**Comment by jfix71** [comment]
Fixed via https://github.com/pytorch/glow/pull/4903
