### ISSUE TITLE
Adding support to infer FasterRCNN Model

### ISSUE THREAD

**Issue by sladwa** [pytorch/glow#4891]
Hey @jfix71 

We need to enable support of infering model like FasterRCNN which has dynamic operators like NMS and NonZero. Reference model from onnx model zoo is https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-10.onnx . We see two ways to address this problem

1. Add support for handling dynamic tensor shape. We wanted to know what is the road map of Glow team for this ? This will address issues of multiple models which require dynamic tensor shapes
2. Second solution is specific to FasterRCNN model i.e., instead of taking models from onnx model zoo, We take FasterRCNN model from detectron2 of FB with config https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml where new operators like GenerateProposals, CollectRpnProposals and Distribute FPN Proposals are added. 

![image](https://user-images.githubusercontent.com/60548566/93445657-b2916780-f8ee-11ea-87aa-6361bd7274c7.png)

Kindly let us know your thoughts regarding above options or any other options that are possible. 

This question is extenstion https://github.com/pytorch/glow/issues/4815

**Comment by jfix71** [comment]
Hi @sladwa -- for dynamic tensor shapes, we do not have current plans for generic support for this. One way we are intending on overcoming this for the more specialized case of different batch sizes is to just compile many of the same model as different Functions in a single Module, but with different batch sizes for each Function. This way they can share weights, and we'd mostly just be able to switch at runtime to the specific batch size. Not sure if this is sufficient for you.

**Comment by sladwa** [comment]
Hey @jfix71 , The deployable fasterRCNN model of detectron2 https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml will require more than supporting specialized case of dynamic tensors specific to batch size. Following is the requirement of FasterRCNN kind of models which have operators that require dynamic tensors of inputs or outputs:

- GenerateProposal Operator output of FasterRCCN has dynamic output tensor.
- Since this operator has dynamic output this dynamicity trickles down to all the subsequent operators post that.

Now to address this dynamic output or input tensor, i see that following layers of glow needs to be updated:

- Graph Layer to handle dynamic tensor behavior
- Operator and function verification layer needs to updated
- Have a mechanism to handle dynamic memory at LLVM layer.

Since currently this support is not available, We plan to have a fused operator which supports GenerateProposals, CollectRpnProposals, DistributeFpnProposals, RoIAligns, Concat and BatchPermutation. By doing so dynamicity of these operators can be handled like the way it is currently done in NMS glow operator where we provide another output to know which of the boxes are valid.

We plan to go ahead with fused node implementation. Kindly let us know your thoughts.

**Comment by jfix71** [comment]
Sounds reasonable to me. CC: @jackm321 @mortzur @zrphercule

**Comment by sladwa** [comment]
Hey @jfix71 , After further study we decided take following approach:

1. Do not go for fused operator implementation. That way each backend can do single operator optimization rather than fused node optimization.
2. To resolve dynamic output tensor behavior for each operators we plan to fix there sizes.
3. For GenerateProposal operator fix output size to be batchsize*post_nms_topN. For invalid RoIs set scores to zero so that they can be ignored in CollectRpnProposal operator
4. For CollectRpnProposal operator fix output size to batchsize*rpn_post_nms_topN. For invalid RoIs set there area to zero so that they can be ignored in DistributeFpnProposal operator
5. In DistributeFpnProposal operator for invalid RoIs we will set sentinal values to the output that goes as input to BatchPermutation operators. Also each input to RoiAlign will be of size batchsize*rpn_post_nms_topN.
6. The BatchPermutation operator will be generic compared to caffe2 definition where output size of batchpermutation will be batchsize*indices_size. This way output of BatchPermutation will still be capped to rpn_post_nms_topN RoIs as set by CollectRpnProposal operator.

We have begun implementation of these operators and end-to-end functional verification. Once completed we will start upstreaming the changes.

**Comment by sladwa** [comment]
We will start raising code reviews for supporting operators of RCNN models.
