### ISSUE TITLE
[Question] Link automatically to bundle objects/libraries

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#5162]
@opti-mix I have a question for you. Is it possible in the current bundle compilation pipeline to link some objects/libraries pre-compiled with other compilers?
The problem I have is this: the current flow of bundle is to have all kernel code (libjit) pre-compiled to LLVM IR using clang. But for some targets (e.g. ARM Cortex-M) the native compiler (GCC based) makes a better job for some kernels (more optimal code). What I want is to have Glow emit calls for external functions and have a mechanism which links to the bundle pre-compiled object/binary code. In principle this could be well done manually by the user in the application code when integrating the bundle but linking those dependencies automatically make a better user experience.
Is there a place in the compilation pipeline where we can link some objects right after the binary code has been emitted? Of course the linking will be done conditionally based on the target architectures and/or other CLI flags.

**Comment by opti-mix** [comment]
@mciprian13 Good question!

>  Is it possible in the current bundle compilation pipeline to link some objects/libraries pre-compiled with other compilers?

When you say link, do you mean using a real linker to produce an executable in AOT fashion? Glow currently does not link final executables as you know. It just produces object files. It can load some libraries if you use GlowJIT.

But some closed-source LLVMBackend-based backends have extended the functionality to do actual linking and produce executable files. They do link a bunch of libraries, including libraries pre-compiled by other compilers.  Here is the idea of how it could be done:

```c++
void MyBackend::saveExecutable(Function *F) const {
  // Generate IR first.
  auto IR = generateAndOptimizeIR(F, *this, shouldShareBuffers());
  // Save the bundle into an object file.
  auto bundleSaver = createBundleSaver(*this, outputDir, bundleName);
  bundleSaver->save(mainEntryName, IR.get());
  bundleSaver->produceBundle();
  // Link the executables.
  std::string linkCmd = "command-line to link executables, which can do anything you want";
  CHECK(!system(linkCmd.c_str())) << "Could not link the NN model executable";
}

glow::Expected<std::unique_ptr<CompiledFunction>>
MyBackend::compile(Function *F, const BackendOptions &opts) const {
  // Compile the network.
  std::unique_ptr<CompiledFunction> compiledFunction;
  ASSIGN_VALUE_OR_RETURN_ERR(compiledFunction, LLVMBackend::compile(F, opts));
  // Produce the executables.
  saveExecutable(F, ...);
  return compiledFunction;
}

**Comment by mciprian13** [comment]
@opti-mix When I say link I`m not thinking about creating an executable but inserting some extra binary code (produced by some other compiler) inside the bundle object file.

**Comment by opti-mix** [comment]
@mciprian13 

> inserting some extra binary code (produced by some other compiler) inside the bundle object file.

I see. Hmm. I don't think it is supported out of the box currently because this use-case was never required so far. But you can propose how to extend the APIs to support that.

Maybe something like `BundleSaver::addResource(name, content)`? And then this content will be included into bundle and accessed via this name o something like that?

**Comment by mciprian13** [comment]
Done in #5275.
