### ISSUE TITLE
Why use by default 64-bit dims for tensors when 32-bit would be more than enough?

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#5380]
Using by default 64-bit dimensions for tensors significantly affects performance.
Not sure why it is even necessary.

**Comment by jfix71** [comment]
Do you mean why `dim_t` is `uint64_t` by default? I think we initially used `size_t` which is commonly 64-bit on modern CPUs, and then when `dim_t` was added we kept it as 64-bit for consistency, but I don't think there's a real reason why we keep it 64-bit.

**Comment by mciprian13** [comment]
@jfix71 Yes, I mean why Glow defines the `TENSOR_DIMS_32_BITS` option by default to OFF? We receive a lot of questions on our side why building Glow out-of-the-box (from github) has such a poor performance for 32-bit micro-controllers. The answer seems to be the 64-bit data type used for tensor indices, loop counters, etc.
Do you think we could switch the parameter from the top CMakelists.txt to ON? I think the 64-bit architectures won't have problems with this since I think such architectures always have native instructions to process 32-bit words.

**Comment by jfix71** [comment]
> Do you think we could switch the parameter from the top CMakelists.txt to ON?

So I went back to look and it was discussed this previously in the PR where `dim_t` was added, see https://github.com/pytorch/glow/pull/3542

Some models include large embedding tables where we may actually need 64bit dims. So I think should keep it by default 64bit, and we keep the status quo where if users know their models don't need 64bit dims they can change the build flag to get better perf w/ 32bit dims.

**Comment by mciprian13** [comment]
Ok thanks for the response. Now I know the details. I will close this issue.
