### ISSUE TITLE
Upsample not wrapped in transposes

### ISSUE THREAD

**Issue by dspmihai** [pytorch/glow#5501]
When loading an ONNX model with upsample, it is also needed to transpose the input and the output of the upsample node to follow Glow's NHWC layout requirements. For some reason this wrapping was deleted at some point and the loading started to fail. I created #5460 to add it back. But then I saw that the in/out can also be from 3D to 6D, so I need to also add these. I understand 3D (NHC), 4D (NHWC) and 5D (NTHWC), but I don't understand how 6D looks like. I can't find something similar in pytorch or caffe2. How does it look like? Or is it something which can be found only in glow and not when importing?

**Comment by jfix71** [comment]
CC: @842974287

**Comment by 842974287** [comment]
Hey @dspmihai, thanks for fixing this. For ONNX model loader I think we probably only need to take care of 3D to 5D. 6D doesn't seem to make sense.
