### ISSUE TITLE
Build fails on creating standalone executable bundles

### ISSUE THREAD

**Issue by wuruoyu** [pytorch/glow#5727]
Hi,

I am trying to build Glow with `GLOW_WITH_BUNDLES` option to create standalone executable bundles and I am following the instructions here: [Creating standalone executable bundles](https://github.com/pytorch/glow/blob/master/docs/AOT.md). It successfully generates ninja build file but fail during building with the following error: 

`
[528/725] Generating ../../../bundles/bundle_with_multiple_entries/testBundle.o
FAILED: bundles/bundle_with_multiple_entries/testBundle.o 
cd /root/dev/build_Debug/examples/bundles/bundle_with_multiple_entries && /root/dev/build_Debug/bundles/bundle_with_multiple_entries/bundle_with_multiple_entriesBundleSaver -emit-bundle /root/dev/build_Debug/bundles/bundle_with_multiple_entries -bundle-api=dynamic -g
bundle_with_multiple_entriesBundleSaver: /root/dev/glow/lib/Backend/BackendUtils.cpp:559: void glow::allocateActivations(const glow::IRFunction::InstListTy &, glow::MemoryAllocator &, glow::runtime::SymbolTableTy &): Assertion !symbolTable.count(std::string(TV->getName())) && "Allocation already made!"' failed.
Aborted (core dumped)
`

I tried with both my host and docker, and they all failed. This issue happens when `DCMAKE_BUILD_TYPE=Debug`. 
The full cmake log and ninja log are attached:
[build_log.txt](https://github.com/pytorch/glow/files/6666185/build_log.txt)
[cmake_log.txt](https://github.com/pytorch/glow/files/6666186/cmake_log.txt)

Could anyone give me some hints on building it? Thanks in advance! 

Respectfully,
Ruoyu

**Comment by levindabhi** [comment]
Quick and naive fix: From  `glow/examples/bundles/CMakeLists.txt` ,<br>
remove `add_subdirectory(bundle_with_multiple_entries)`

**Comment by wuruoyu** [comment]
thanks!
