### ISSUE TITLE
Potential small issue in Readme.md->"Configure and Build" section

### ISSUE THREAD

**Issue by nikola-suljagic** [pytorch/glow#5818]
Hi everyone,
I am starting with Glow compiler setup, maybe there is small issue in description of executing cmake  in section "Configure and Build".
Here is steps described in main Readme.md

`mkdir build_Debug`
`cd build_Debug`
`cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../glow`
`ninja all`

I got path error in third command, because when I follow previous steps I got error that there isn't CMakeLists.txt file. 
shouldn't it be:
`cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..` ?
without **/glow** or maybe to skip command 
`cd build_Debug`
but if we skip `cd build_Debug` we will pollute root dir?

**Comment by thiagolcmelo** [comment]
That is a bit misleading indeed, but it says that the `build_Debug` directory is expected to be outside the source directory :)

> It's also a good idea to build the project outside of the source directory.

So:

```
├── glow/
├── build_Debug/
```

**Comment by nikola-suljagic** [comment]
Clear clear, thanks :)
