### ISSUE TITLE
Fix commit

### ISSUE THREAD

**Issue by mciprian13** [pytorch/glow#5939]
@jfix71 The latest commit broke the build:
[5b8248a](https://github.com/pytorch/glow/commit/5b8248ae6cdf4051293efb3d6c379df959fb2591)
Can one from your side revert/fix it? Thanks!

**Comment by jfix71** [comment]
Yep, sorry about that, on it!

**Comment by jfix71** [comment]
Fixed in https://github.com/pytorch/glow/pull/5943.
