### ISSUE TITLE
Where Glow invokes llvm ?

### ISSUE THREAD

**Issue by Theoo1997** [pytorch/glow#6029]
Hi,
I am working with Glow and I would like to know :

1. Where the compiler invokes llvm to compile the llvm IR into the target platform.
2. I also wont to see the llvm passes of the above step like "optimization_level = -O2", etc.
3. And print the llvm IR.

**Comment by kbkarthikeyan** [comment]
Hi Theo, 
You can use these options in the model-compiler. 
- use the option "--dump-ir" to get the LLVM IR
- use the option "--target=<ARCHITECTURE>" - to set the target. 

To get the target list of the installed <ARCHITECTURE> of your LLVM, 
- use "llvm-objdump -version"
