### ISSUE TITLE
Is the Glow still under development and maintenance?

### ISSUE THREAD

**Issue by jikechao** [pytorch/glow#6170]
Hi community, I saw that the latest merged PR at Sep 28, 2023. For a long time, I did not see any new PR merged. Thus, I wonder if this project is still under development or maintenance.
BTW, I saw many open PRs with the label "[fb-exported](https://github.com/pytorch/glow/pulls?q=is%3Apr+is%3Aclosed+label%3Afb-exported)", what is the meaning of this label?

I'm looking forward to your response. Thanks!

**Comment by pawan-nirpal-031** [comment]
I would like to know the answer to this question too! However, the motivations or use cases for this to be a viable project which undergoes active development are unclear. I guess it's not clear enough why this is required in the first place. Why can't LLVM IR be generated directly? Also, there seems to be a lot of overlap in what glow is trying to do, with what another project ( torch-mlir ) is trying to do, If I'm not wrong. I'd like to hear from folks who started this project about their motivations. If I'm not wrong MLIR tried to achieve the same goals with two-level IR, MIR and LLVM IR, If yes then reusing existing infra might make a whole lot of sense. Still curious to know the motivations behind this project.

**Comment by jfix71** [comment]
We're not maintaining Glow much anymore. Glow pre-dated MLIR. See the original arxiv paper here: https://arxiv.org/abs/1805.00907

I'd suggest looking into to PyTorch 2 technologies like Dynamo and Inductor for newer options for graph compilation from PyTorch.
