### ISSUE TITLE
Performance compared with NNVM/TVM

### ISSUE THREAD

**Issue by knsong** [pytorch/glow#980]
Except for the performance of Glow on Resnet50 etc compared with TensorFlow1.7, will there be some more benchmarks such as comparing Glow with NNVM/TVM on CPU/GPU?

**Comment by rdzhabarov** [comment]
@knsong thanks for looking into the project. Currently, we do not have such benchmarks, but I imagine we'd have this later at some point.

**Comment by nadavrot** [comment]
@ZchiPitt recently benchmarked TVM to Glow on Resnet50. Glow is faster. Chi's numbers: 

Glow: 0.14982 sec  TVM: 0.23045 sec

**Comment by knsong** [comment]
@nadavrot What hardware was the benchmark performed on?
